import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {Client} from 'pg';

jest.setTimeout(180_000);
const previous='migrations/node-pg/1719560000000_add_booking_change_requests.js';

describe('BookingChangeRequest deferrable context FK corrective migration',()=>{
  it('preserves definitions and populated rows across UP -> DOWN -> UP while retaining immediate enforcement',async()=>{
    const configured=process.env.DATABASE_URL;if(!configured)throw new Error('DATABASE_URL is required');
    const admin=new Client({connectionString:configured});const name=`vethelp_w5c1_fk_${process.pid}_${Date.now()}`;const target=new URL(configured);target.pathname=`/${name}`;let client:Client|null=null;const checksum=sha(previous);
    await admin.connect();try{
      await admin.query(`CREATE DATABASE "${name}"`);run('up',target.toString());run('down',target.toString());client=new Client({connectionString:target.toString()});await client.connect();
      const id={owner:'11000000-0000-4000-8000-000000000011',clinic:'21000000-0000-4000-8000-000000000011',location:'31000000-0000-4000-8000-000000000011',service:'41000000-0000-4000-8000-000000000011',pet:'51000000-0000-4000-8000-000000000011',slot:'61000000-0000-4000-8000-000000000011',slot2:'61000000-0000-4000-8000-000000000012',hold:'71000000-0000-4000-8000-000000000011'};
      await client.query(`INSERT INTO identity_schema.users(id) VALUES($1)`,[id.owner]);await client.query(`INSERT INTO pet_schema.pets(id,owner_id,name,species) VALUES($1,$2,'W5C1','DOG')`,[id.pet,id.owner]);await client.query(`INSERT INTO clinic_schema.clinics(id,legal_name,public_name) VALUES($1,'W5C1','W5C1')`,[id.clinic]);await client.query(`INSERT INTO clinic_schema.clinic_locations(id,clinic_id,address,timezone) VALUES($1,$2,'W5C1','Europe/Moscow')`,[id.location,id.clinic]);await client.query(`INSERT INTO clinic_schema.clinic_services(id,clinic_location_id,code,display_name,duration_minutes) VALUES($1,$2,'W5C1','W5C1',30)`,[id.service,id.location]);await client.query(`INSERT INTO clinic_schema.appointment_slots(id,clinic_location_id,service_id,starts_at,ends_at,capacity,booked_count,state,publication_state) VALUES($1,$3,$4,clock_timestamp()+interval '1 day',clock_timestamp()+interval '1 day 30 minutes',1,1,'OPEN','PUBLISHED'),($2,$3,$4,clock_timestamp()+interval '2 days',clock_timestamp()+interval '2 days 30 minutes',1,0,'OPEN','PUBLISHED')`,[id.slot,id.slot2,id.location,id.service]);await client.query(`INSERT INTO booking_schema.booking_holds(id,slot_id,owner_id,pet_id,state,expires_at) VALUES($1,$2,$3,$4,'CONFIRMED',clock_timestamp()+interval '1 day')`,[id.hold,id.slot,id.owner,id.pet]);const appointment=(await client.query(`INSERT INTO booking_schema.appointments(hold_id,owner_id,pet_id,clinic_location_id,slot_id,status) VALUES($1,$2,$3,$4,$5,'CONFIRMED') RETURNING id::text`,[id.hold,id.owner,id.pet,id.location,id.slot])).rows[0].id;const request=(await client.query(`INSERT INTO booking_schema.booking_change_requests(request_type,status,booking_hold_id,appointment_id,owner_id,clinic_id,location_id,slot_id,idempotency_key,correlation_id) VALUES('RESCHEDULE','PROCESSING',$1,$2,$3,$4,$5,$6,gen_random_uuid(),gen_random_uuid()) RETURNING id::text`,[id.hold,appointment,id.owner,id.clinic,id.location,id.slot])).rows[0].id;
      run('up',target.toString());expect(await definitions(client)).toEqual(expected(true));await expect(client.query(`UPDATE booking_schema.booking_change_requests SET slot_id=gen_random_uuid() WHERE id=$1`,[request])).rejects.toMatchObject({code:'23503'});
      await client.query('BEGIN');await client.query('SET CONSTRAINTS booking_schema.booking_change_requests_hold_owner_slot_fkey, booking_schema.booking_change_requests_appointment_context_fkey DEFERRED');await client.query(`UPDATE booking_schema.booking_change_requests SET slot_id=$2 WHERE id=$1`,[request,id.slot2]);await expect(client.query('COMMIT')).rejects.toMatchObject({code:'23503'});await client.query('ROLLBACK').catch(()=>undefined);expect((await client.query(`SELECT slot_id::text FROM booking_schema.booking_change_requests WHERE id=$1`,[request])).rows[0].slot_id).toBe(id.slot);
      run('down',target.toString());expect(await definitions(client)).toEqual(expected(false));expect((await client.query(`SELECT count(*)::int count FROM booking_schema.booking_change_requests WHERE id=$1`,[request])).rows[0].count).toBe(1);run('up',target.toString());expect(await definitions(client)).toEqual(expected(true));expect(sha(previous)).toBe(checksum);
    }finally{await client?.end();await admin.query(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=$1`,[name]);await admin.query(`DROP DATABASE IF EXISTS "${name}"`);await admin.end();}
  });
});
function run(direction:'up'|'down',databaseUrl:string){execFileSync(join(process.cwd(),'node_modules/.bin/node-pg-migrate'),[direction,'--migrations-dir','migrations/node-pg','--migrations-schema','public','--migrations-table','schema_migrations','--single-transaction'],{cwd:process.cwd(),env:{...process.env,DATABASE_URL:databaseUrl},stdio:'pipe'});}
async function definitions(client:Client){return(await client.query(`SELECT conname,condeferrable,condeferred,pg_get_constraintdef(oid) definition FROM pg_constraint WHERE conname IN ('booking_change_requests_hold_owner_slot_fkey','booking_change_requests_appointment_context_fkey') ORDER BY conname`)).rows;}
function expected(deferrable:boolean){return[{conname:'booking_change_requests_appointment_context_fkey',condeferrable:deferrable,condeferred:false,definition:`FOREIGN KEY (appointment_id, booking_hold_id, owner_id, location_id, slot_id) REFERENCES booking_schema.appointments(id, hold_id, owner_id, clinic_location_id, slot_id) ON DELETE RESTRICT${deferrable?' DEFERRABLE':''}`},{conname:'booking_change_requests_hold_owner_slot_fkey',condeferrable:deferrable,condeferred:false,definition:`FOREIGN KEY (booking_hold_id, owner_id, slot_id) REFERENCES booking_schema.booking_holds(id, owner_id, slot_id) ON DELETE RESTRICT${deferrable?' DEFERRABLE':''}`}];}
function sha(path:string){return createHash('sha256').update(readFileSync(path)).digest('hex');}
