import 'reflect-metadata';
import type { INestApplication } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { JwtService } from '@nestjs/jwt';
import { randomUUID } from 'node:crypto';
import request from 'supertest';
import { Role } from '../src/auth/auth.types';
import { BookingErrorFilter } from '../src/common/booking-error.filter';
import { config } from '../src/config';
import { DatabaseService } from '../src/database/database.service';
import { NestRoot } from '../src/nest-root-full';

jest.setTimeout(90_000);
describe('v1.5 appointment lifecycle real Nest runtime',()=>{
 let app:INestApplication,db:DatabaseService,jwt:JwtService;
 beforeAll(async()=>{process.env.WORKERS_ENABLED='false';app=await NestFactory.create(NestRoot,{logger:false});app.useGlobalFilters(new BookingErrorFilter());await app.init();db=app.get(DatabaseService);jwt=app.get(JwtService);}); afterAll(()=>app.close());
 const token=(actor:any)=>jwt.signAsync(actor,{secret:config.jwtSecret,issuer:config.jwtIssuer,audience:config.jwtAudience,algorithm:'HS256'});

 it('enforces clinic authority/reason and exposes authoritative Owner cancellation readback',async()=>{const f=await seed(db);const path=`/v1/clinic/${f.clinic}/locations/${f.location}/appointments/${f.appointment}/cancel`;const headers={'Authorization':`Bearer ${await token(f.employee)}`,'Idempotency-Key':randomUUID(),'If-Match':'"1"'};
  await request(app.getHttpServer()).post(path).set(headers).send({}).expect(400);
  await request(app.getHttpServer()).post(path).set('Authorization',`Bearer ${await token({sub:f.owner,roles:[Role.OWNER]})}`).set('Idempotency-Key',randomUUID()).set('If-Match','"1"').send({reasonCode:'X'}).expect(403);
  await request(app.getHttpServer()).post(path).set(headers).send({reasonCode:'CLINIC_UNAVAILABLE'}).expect(200).expect((r)=>expect(r.body.lifecycle).toBe('CANCELLED_BY_CLINIC'));
  const read=await request(app.getHttpServer()).get(`/v1/owner/appointments/${f.hold}`).set('Authorization',`Bearer ${await token({sub:f.owner,roles:[Role.OWNER]})}`).expect(200);expect(read.body.appointmentLifecycle).toMatchObject({state:'CANCELLED_BY_CLINIC',cancelledBy:'CLINIC',reasonCode:'CLINIC_UNAVAILABLE'});
 });

 it('keeps original slot until authenticated Owner accepts the clinic proposal',async()=>{const f=await seed(db);const clinicToken=await token(f.employee),ownerToken=await token({sub:f.owner,roles:[Role.OWNER]});const proposed=await request(app.getHttpServer()).post(`/v1/clinic/${f.clinic}/locations/${f.location}/appointments/${f.appointment}/reschedule-proposals`).set('Authorization',`Bearer ${clinicToken}`).set('Idempotency-Key',randomUUID()).set('If-Match','"1"').send({targetSlotId:f.target,expectedTargetSlotVersion:1}).expect(200);expect((await db.query<any>('SELECT slot_id::text FROM booking_schema.appointments WHERE id=$1',[f.appointment])).rows[0].slot_id).toBe(f.source);
  const snapshot=await request(app.getHttpServer()).get(`/v1/owner/bookings/${f.hold}/alternative`).set('Authorization',`Bearer ${ownerToken}`).expect(200);expect(snapshot.body.aggregateVersion).toBe(2);
  await request(app.getHttpServer()).post(`/v1/owner/bookings/${f.hold}/alternative/${proposed.body.proposalId}/accept`).set('Authorization',`Bearer ${ownerToken}`).set('Idempotency-Key',randomUUID()).set('If-Match',`"${snapshot.body.aggregateVersion}"`).set('X-Correlation-ID',randomUUID()).expect(200);
  expect((await db.query<any>('SELECT slot_id::text,lifecycle_state FROM booking_schema.appointments WHERE id=$1',[f.appointment])).rows[0]).toEqual({slot_id:f.target,lifecycle_state:'CONFIRMED'});
 });

 it('marks no-show only for authorized clinic staff after start and exposes Owner readback',async()=>{const f=await seed(db,-1),path=`/v1/clinic/${f.clinic}/locations/${f.location}/appointments/${f.appointment}/no-show`,ownerToken=await token({sub:f.owner,roles:[Role.OWNER]});await request(app.getHttpServer()).post(path).set('Authorization',`Bearer ${ownerToken}`).set('Idempotency-Key',randomUUID()).set('If-Match','"1"').expect(403);await request(app.getHttpServer()).post(path).set('Authorization',`Bearer ${await token(f.employee)}`).set('Idempotency-Key',randomUUID()).set('If-Match','"1"').expect(200).expect((r)=>expect(r.body.lifecycle).toBe('NO_SHOW'));const read=await request(app.getHttpServer()).get(`/v1/owner/appointments/${f.hold}`).set('Authorization',`Bearer ${ownerToken}`).expect(200);expect(read.body.appointmentLifecycle.state).toBe('NO_SHOW');});

 it('allows Owner rejection through the public runtime and keeps the original slot',async()=>{const f=await seed(db),clinicToken=await token(f.employee),ownerToken=await token({sub:f.owner,roles:[Role.OWNER]});const proposed=await request(app.getHttpServer()).post(`/v1/clinic/${f.clinic}/locations/${f.location}/appointments/${f.appointment}/reschedule-proposals`).set('Authorization',`Bearer ${clinicToken}`).set('Idempotency-Key',randomUUID()).set('If-Match','"1"').send({targetSlotId:f.target,expectedTargetSlotVersion:1}).expect(200);const snapshot=await request(app.getHttpServer()).get(`/v1/owner/bookings/${f.hold}/alternative`).set('Authorization',`Bearer ${ownerToken}`).expect(200);await request(app.getHttpServer()).post(`/v1/owner/bookings/${f.hold}/alternative/${proposed.body.proposalId}/decline`).set('Authorization',`Bearer ${ownerToken}`).set('Idempotency-Key',randomUUID()).set('If-Match',`"${snapshot.body.aggregateVersion}"`).set('X-Correlation-ID',randomUUID()).expect(200);expect((await db.query<any>('SELECT slot_id::text,lifecycle_state FROM booking_schema.appointments WHERE id=$1',[f.appointment])).rows[0]).toEqual({slot_id:f.source,lifecycle_state:'CONFIRMED'});});
});

async function seed(db:DatabaseService,hours=3){await db.query('TRUNCATE clinic_schema.clinics,pet_schema.pets,identity_schema.users CASCADE');const owner=randomUUID(),staff=randomUUID(),pet=randomUUID();await db.query('INSERT INTO identity_schema.users(id) VALUES($1),($2)',[owner,staff]);await db.query("INSERT INTO pet_schema.pets(id,owner_id,name,species) VALUES($1,$2,'HTTP W2','DOG')",[pet,owner]);const clinic=(await db.query<any>("INSERT INTO clinic_schema.clinics(legal_name,public_name) VALUES('HTTP W2','HTTP W2') RETURNING id")).rows[0].id;const location=(await db.query<any>("INSERT INTO clinic_schema.clinic_locations(clinic_id,address) VALUES($1,'HTTP W2') RETURNING id",[clinic])).rows[0].id;await db.query("INSERT INTO clinic_schema.employee_location_memberships(employee_id,clinic_location_id,role) VALUES($1,$2,'CLINIC_RECEPTIONIST')",[staff,location]);const service=(await db.query<any>("INSERT INTO clinic_schema.clinic_services(clinic_location_id,code,display_name,duration_minutes) VALUES($1,'HTTPW2','HTTP W2',30) RETURNING id",[location])).rows[0].id;const source=(await db.query<any>("INSERT INTO clinic_schema.appointment_slots(clinic_location_id,service_id,starts_at,ends_at,capacity,booked_count,status,integration_mode) VALUES($1,$2,clock_timestamp()+$3*interval '1 hour',clock_timestamp()+($3+1)*interval '1 hour',1,1,'BOOKED','LEVEL_C') RETURNING id",[location,service,hours])).rows[0].id;const target=(await db.query<any>("INSERT INTO clinic_schema.appointment_slots(clinic_location_id,service_id,starts_at,ends_at,capacity,status,integration_mode) VALUES($1,$2,clock_timestamp()+interval '5 hour',clock_timestamp()+interval '6 hour',1,'AVAILABLE','LEVEL_C') RETURNING id",[location,service])).rows[0].id;const hold=(await db.query<any>("INSERT INTO booking_schema.booking_holds(slot_id,owner_id,pet_id,state,expires_at) VALUES($1,$2,$3,'CONFIRMED',clock_timestamp()+interval '1 day') RETURNING id",[source,owner,pet])).rows[0].id;const appointment=(await db.query<any>("INSERT INTO booking_schema.appointments(hold_id,owner_id,pet_id,clinic_location_id,slot_id) VALUES($1,$2,$3,$4,$5) RETURNING id",[hold,owner,pet,location,source])).rows[0].id;return{owner,clinic,location,source,target,hold,appointment,employee:{sub:staff,roles:[Role.CLINIC_RECEPTIONIST],clinicIds:[clinic],locationIds:[location]}};}
