import { randomUUID } from 'node:crypto';
import { Role } from '../src/auth/auth.types';
import { AppointmentLifecycleService } from '../src/booking-core/appointment-lifecycle.service';
import { ClinicEmployeeAccessService } from '../src/booking-core/clinic-employee-access.service';
import { OwnerAlternativeAcceptanceService } from '../src/booking-core/owner-alternative-acceptance.service';
import { DatabaseService } from '../src/database/database.service';

jest.setTimeout(45_000);
describe('v1.5 appointment lifecycle (real PostgreSQL)',()=>{
 const db=new DatabaseService(); const lifecycle=new AppointmentLifecycleService(db,new ClinicEmployeeAccessService()); const ownerResolution=new OwnerAlternativeAcceptanceService({} as never,db);
 afterAll(()=>db.onModuleDestroy());

 it('requires and persists an auditable clinic cancellation reason with scope and replay safety',async()=>{const f=await fixture(db);const base=command(f);
  await expect(lifecycle.cancelByClinic({...base,reasonText:' '})).rejects.toMatchObject({status:400,response:{code:'VALIDATION_ERROR'}});
  await expect(lifecycle.cancelByClinic({...base,employee:{...f.employee,clinicIds:[randomUUID()]},reasonCode:'CLINIC_UNAVAILABLE'})).rejects.toMatchObject({status:403});
  const result=await lifecycle.cancelByClinic({...base,reasonCode:'CLINIC_UNAVAILABLE',reasonText:'Doctor unavailable'});
  await expect(lifecycle.cancelByClinic({...base,reasonCode:'CLINIC_UNAVAILABLE',reasonText:'Doctor unavailable'})).resolves.toEqual(result);
  const row=(await db.query<any>(`SELECT status,lifecycle_state,cancelled_by,cancelled_by_actor_id::text,cancellation_reason_code,cancellation_reason_text,(SELECT booked_count FROM clinic_schema.appointment_slots WHERE id=a.slot_id) booked,(SELECT count(*)::int FROM booking_schema.appointment_events WHERE appointment_id=a.id) events FROM booking_schema.appointments a WHERE id=$1`,[f.appointment])).rows[0];
  expect(row).toMatchObject({status:'CLINIC_CANCELLED',lifecycle_state:'CANCELLED_BY_CLINIC',cancelled_by:'CLINIC',cancelled_by_actor_id:f.employee.sub,cancellation_reason_code:'CLINIC_UNAVAILABLE',cancellation_reason_text:'Doctor unavailable',booked:0,events:1});
 });

 it.each(['ACCEPT','DECLINE'] as const)('keeps original authoritative until Owner %s and resolves atomically',async(decision)=>{const f=await fixture(db);const proposal=await lifecycle.propose({...command(f),targetSlotId:f.target,expectedTargetSlotVersion:1});
  let state=(await db.query<any>('SELECT slot_id::text,lifecycle_state FROM booking_schema.appointments WHERE id=$1',[f.appointment])).rows[0]; expect(state).toEqual({slot_id:f.source,lifecycle_state:'RESCHEDULE_PROPOSED'});
  const result=await ownerResolution.resolve(proposal.proposalId as string,f.owner,decision,{expectedVersion:2,idempotencyKey:randomUUID(),correlationId:randomUUID()},f.hold);
  state=(await db.query<any>(`SELECT a.slot_id::text,a.lifecycle_state,(SELECT booked_count FROM clinic_schema.appointment_slots WHERE id=$2) source_booked,(SELECT booked_count FROM clinic_schema.appointment_slots WHERE id=$3) target_booked,(SELECT held_count FROM clinic_schema.appointment_slots WHERE id=$3) target_held FROM booking_schema.appointments a WHERE a.id=$1`,[f.appointment,f.source,f.target])).rows[0];
  expect(result.state).toBe('CONFIRMED'); expect(state.lifecycle_state).toBe('CONFIRMED'); expect(state.slot_id).toBe(decision==='ACCEPT'?f.target:f.source); expect(state.target_held).toBe(0); expect(state.source_booked).toBe(decision==='ACCEPT'?0:1); expect(state.target_booked).toBe(decision==='ACCEPT'?1:0);
 });

 it('serializes clinic cancel versus Owner accept without split capacity',async()=>{const f=await fixture(db);const proposal=await lifecycle.propose({...command(f),targetSlotId:f.target,expectedTargetSlotVersion:1});const settled=await Promise.allSettled([ownerResolution.resolve(proposal.proposalId as string,f.owner,'ACCEPT',{expectedVersion:2,idempotencyKey:randomUUID(),correlationId:randomUUID()},f.hold),lifecycle.cancelByClinic({...command(f),expectedVersion:2,idempotencyKey:randomUUID(),reasonCode:'CLINIC_UNAVAILABLE'})]);expect(settled.filter(x=>x.status==='fulfilled')).toHaveLength(1);const row=(await db.query<any>(`SELECT lifecycle_state,(SELECT sum(booked_count) FROM clinic_schema.appointment_slots WHERE id=ANY($2::uuid[])) booked,(SELECT sum(held_count) FROM clinic_schema.appointment_slots WHERE id=ANY($2::uuid[])) held FROM booking_schema.appointments WHERE id=$1`,[f.appointment,[f.source,f.target]])).rows[0];expect(['CONFIRMED','CANCELLED_BY_CLINIC']).toContain(row.lifecycle_state);expect(Number(row.booked)).toBe(row.lifecycle_state==='CONFIRMED'?1:0);expect(Number(row.held)).toBe(0);});

 it('marks no-show only after authoritative start time and replays idempotently',async()=>{let f=await fixture(db);await expect(lifecycle.markNoShow(command(f))).rejects.toMatchObject({status:422});f=await fixture(db,-1);const cmd=command(f);const result=await lifecycle.markNoShow(cmd);await expect(lifecycle.markNoShow(cmd)).resolves.toEqual(result);const row=(await db.query<any>('SELECT status,lifecycle_state,no_show_at,no_show_by_actor_id::text FROM booking_schema.appointments WHERE id=$1',[f.appointment])).rows[0];expect(row).toMatchObject({status:'NO_SHOW',lifecycle_state:'NO_SHOW',no_show_by_actor_id:f.employee.sub});});
});

const command=(f:Awaited<ReturnType<typeof fixture>>)=>({appointmentId:f.appointment,clinicId:f.clinic,locationId:f.location,employee:f.employee,expectedVersion:1,idempotencyKey:randomUUID(),correlationId:randomUUID()});
async function fixture(db:DatabaseService,hours=3){await db.query('TRUNCATE clinic_schema.clinics,pet_schema.pets,identity_schema.users CASCADE');const owner=randomUUID(),staff=randomUUID(),pet=randomUUID();await db.query('INSERT INTO identity_schema.users(id) VALUES($1),($2)',[owner,staff]);await db.query("INSERT INTO pet_schema.pets(id,owner_id,name,species) VALUES($1,$2,'Wave2','DOG')",[pet,owner]);const clinic=(await db.query<any>("INSERT INTO clinic_schema.clinics(legal_name,public_name) VALUES('W2','W2') RETURNING id")).rows[0].id;const location=(await db.query<any>("INSERT INTO clinic_schema.clinic_locations(clinic_id,address) VALUES($1,'W2') RETURNING id",[clinic])).rows[0].id;await db.query("INSERT INTO clinic_schema.employee_location_memberships(employee_id,clinic_location_id,role) VALUES($1,$2,'CLINIC_RECEPTIONIST')",[staff,location]);const service=(await db.query<any>("INSERT INTO clinic_schema.clinic_services(clinic_location_id,code,display_name,duration_minutes) VALUES($1,'W2','W2',30) RETURNING id",[location])).rows[0].id;const source=(await db.query<any>("INSERT INTO clinic_schema.appointment_slots(clinic_location_id,service_id,starts_at,ends_at,capacity,booked_count,status,integration_mode) VALUES($1,$2,clock_timestamp()+$3*interval '1 hour',clock_timestamp()+($3+1)*interval '1 hour',1,1,'BOOKED','LEVEL_C') RETURNING id",[location,service,hours])).rows[0].id;const target=(await db.query<any>("INSERT INTO clinic_schema.appointment_slots(clinic_location_id,service_id,starts_at,ends_at,capacity,status,integration_mode) VALUES($1,$2,clock_timestamp()+interval '5 hour',clock_timestamp()+interval '6 hour',1,'AVAILABLE','LEVEL_C') RETURNING id",[location,service])).rows[0].id;const hold=(await db.query<any>("INSERT INTO booking_schema.booking_holds(slot_id,owner_id,pet_id,state,expires_at) VALUES($1,$2,$3,'CONFIRMED',clock_timestamp()+interval '1 day') RETURNING id",[source,owner,pet])).rows[0].id;const appointment=(await db.query<any>("INSERT INTO booking_schema.appointments(hold_id,owner_id,pet_id,clinic_location_id,slot_id) VALUES($1,$2,$3,$4,$5) RETURNING id",[hold,owner,pet,location,source])).rows[0].id;return{owner,clinic,location,source,target,hold,appointment,employee:{sub:staff,roles:[Role.CLINIC_RECEPTIONIST],clinicIds:[clinic],locationIds:[location]}};}
