import { randomUUID } from 'node:crypto';
import { Role } from '../src/auth/auth.types';
import { AppointmentLifecycleService } from '../src/booking-core/appointment-lifecycle.service';
import { ClinicEmployeeAccessService } from '../src/booking-core/clinic-employee-access.service';
import { OwnerAlternativeAcceptanceService } from '../src/booking-core/owner-alternative-acceptance.service';
import { BookingSecurityService } from '../src/booking-core/booking-security.service';
import { DatabaseService } from '../src/database/database.service';
import { OwnerAppointmentsService } from '../src/auth/owner-appointments.service';

jest.setTimeout(45_000);
describe('v1.5 appointment lifecycle (real PostgreSQL)',()=>{
 const db=new DatabaseService(); const access=new ClinicEmployeeAccessService(); const lifecycle=new AppointmentLifecycleService(db,access); const ownerResolution=new OwnerAlternativeAcceptanceService({} as never,db); const ownerRead=new OwnerAppointmentsService(db); const security=new BookingSecurityService(db,access);
 afterAll(()=>db.onModuleDestroy());

 it('requires and persists an auditable clinic cancellation reason with scope and replay safety',async()=>{const f=await fixture(db);const base=command(f);
  await expect(lifecycle.cancelByClinic({...base,reasonText:' '})).rejects.toMatchObject({status:400,response:{code:'VALIDATION_ERROR'}});
  await expect(lifecycle.cancelByClinic({...base,employee:{...f.employee,clinicIds:[randomUUID()]},reasonCode:'CLINIC_UNAVAILABLE'})).rejects.toMatchObject({status:403});
  const result=await lifecycle.cancelByClinic({...base,reasonCode:'CLINIC_UNAVAILABLE',reasonText:'Doctor unavailable'});
  await expect(lifecycle.cancelByClinic({...base,reasonCode:'CLINIC_UNAVAILABLE',reasonText:'Doctor unavailable'})).resolves.toEqual(result);
  const row=(await db.query<any>(`SELECT status,lifecycle_state,cancelled_by,cancelled_by_actor_id::text,cancellation_reason_code,cancellation_reason_text,(SELECT booked_count FROM clinic_schema.appointment_slots WHERE id=a.slot_id) booked,(SELECT count(*)::int FROM booking_schema.appointment_events WHERE appointment_id=a.id) events FROM booking_schema.appointments a WHERE id=$1`,[f.appointment])).rows[0];
  expect(row).toMatchObject({status:'CLINIC_CANCELLED',lifecycle_state:'CANCELLED_BY_CLINIC',cancelled_by:'CLINIC',cancelled_by_actor_id:f.employee.sub,cancellation_reason_code:'CLINIC_UNAVAILABLE',cancellation_reason_text:'Doctor unavailable',booked:0,events:1});
  await expect(ownerRead.read({sub:f.owner,roles:[Role.OWNER]},f.hold)).resolves.toMatchObject({appointmentLifecycle:{state:'CANCELLED_BY_CLINIC',cancelledBy:'CLINIC',reasonCode:'CLINIC_UNAVAILABLE',reasonText:'Doctor unavailable'}});
 });

 it.each(['ACCEPT','DECLINE'] as const)('keeps original authoritative until Owner %s and resolves atomically',async(decision)=>{const f=await fixture(db);const proposal=await lifecycle.propose({...command(f),targetSlotId:f.target,expectedTargetSlotVersion:1});
  let state=(await db.query<any>('SELECT slot_id::text,lifecycle_state FROM booking_schema.appointments WHERE id=$1',[f.appointment])).rows[0]; expect(state).toEqual({slot_id:f.source,lifecycle_state:'RESCHEDULE_PROPOSED'});
  const resolutionCommand={expectedVersion:2,idempotencyKey:randomUUID(),correlationId:randomUUID()};
  const result=await ownerResolution.resolve(proposal.proposalId as string,f.owner,decision,resolutionCommand,f.hold);
  await expect(ownerResolution.resolve(proposal.proposalId as string,f.owner,decision,resolutionCommand,f.hold)).resolves.toEqual(result);
  state=(await db.query<any>(`SELECT a.slot_id::text,a.lifecycle_state,(SELECT booked_count FROM clinic_schema.appointment_slots WHERE id=$2) source_booked,(SELECT booked_count FROM clinic_schema.appointment_slots WHERE id=$3) target_booked,(SELECT held_count FROM clinic_schema.appointment_slots WHERE id=$3) target_held FROM booking_schema.appointments a WHERE a.id=$1`,[f.appointment,f.source,f.target])).rows[0];
  expect(result.state).toBe('CONFIRMED'); expect(state.lifecycle_state).toBe('CONFIRMED'); expect(state.slot_id).toBe(decision==='ACCEPT'?f.target:f.source); expect(state.target_held).toBe(0); expect(state.source_booked).toBe(decision==='ACCEPT'?0:1); expect(state.target_booked).toBe(decision==='ACCEPT'?1:0);
 });

 it('serializes clinic cancel versus Owner accept without split capacity',async()=>{const f=await fixture(db);const proposal=await lifecycle.propose({...command(f),targetSlotId:f.target,expectedTargetSlotVersion:1});const settled=await Promise.allSettled([ownerResolution.resolve(proposal.proposalId as string,f.owner,'ACCEPT',{expectedVersion:2,idempotencyKey:randomUUID(),correlationId:randomUUID()},f.hold),lifecycle.cancelByClinic({...command(f),expectedVersion:2,idempotencyKey:randomUUID(),reasonCode:'CLINIC_UNAVAILABLE'})]);expect(settled.filter(x=>x.status==='fulfilled')).toHaveLength(1);const row=(await db.query<any>(`SELECT lifecycle_state,(SELECT sum(booked_count) FROM clinic_schema.appointment_slots WHERE id=ANY($2::uuid[])) booked,(SELECT sum(held_count) FROM clinic_schema.appointment_slots WHERE id=ANY($2::uuid[])) held FROM booking_schema.appointments WHERE id=$1`,[f.appointment,[f.source,f.target]])).rows[0];expect(['CONFIRMED','CANCELLED_BY_CLINIC']).toContain(row.lifecycle_state);expect(Number(row.booked)).toBe(row.lifecycle_state==='CONFIRMED'?1:0);expect(Number(row.held)).toBe(0);});

 it('allows only one proposal to reserve the final target capacity for two Owners',async()=>{const f=await fixture(db),owner2=randomUUID(),pet2=randomUUID();await db.query('INSERT INTO identity_schema.users(id) VALUES($1)',[owner2]);await db.query("INSERT INTO pet_schema.pets(id,owner_id,name,species) VALUES($1,$2,'Wave2 second','DOG')",[pet2,owner2]);const source2=(await db.query<any>("INSERT INTO clinic_schema.appointment_slots(clinic_location_id,service_id,starts_at,ends_at,capacity,booked_count,status,integration_mode) SELECT clinic_location_id,service_id,clock_timestamp()+interval '4 hour',clock_timestamp()+interval '5 hour',1,1,'BOOKED','LEVEL_C' FROM clinic_schema.appointment_slots WHERE id=$1 RETURNING id",[f.source])).rows[0].id;const hold2=(await db.query<any>("INSERT INTO booking_schema.booking_holds(slot_id,owner_id,pet_id,state,expires_at) VALUES($1,$2,$3,'CONFIRMED',clock_timestamp()+interval '1 day') RETURNING id",[source2,owner2,pet2])).rows[0].id;const appointment2=(await db.query<any>("INSERT INTO booking_schema.appointments(hold_id,owner_id,pet_id,clinic_location_id,slot_id) VALUES($1,$2,$3,$4,$5) RETURNING id",[hold2,owner2,pet2,f.location,source2])).rows[0].id;const settled=await Promise.allSettled([lifecycle.propose({...command(f),targetSlotId:f.target,expectedTargetSlotVersion:1}),lifecycle.propose({...command(f),appointmentId:appointment2,targetSlotId:f.target,expectedTargetSlotVersion:1,idempotencyKey:randomUUID()})]);expect(settled.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect((await db.query<any>('SELECT held_count FROM clinic_schema.appointment_slots WHERE id=$1',[f.target])).rows[0].held_count).toBe(1);});

 it('allows one authoritative Owner decision in an accept-versus-reject race',async()=>{const f=await fixture(db);const proposal=await lifecycle.propose({...command(f),targetSlotId:f.target,expectedTargetSlotVersion:1});const settled=await Promise.allSettled(['ACCEPT','DECLINE'].map((decision)=>ownerResolution.resolve(proposal.proposalId as string,f.owner,decision as 'ACCEPT'|'DECLINE',{expectedVersion:2,idempotencyKey:randomUUID(),correlationId:randomUUID()},f.hold)));expect(settled.filter(x=>x.status==='fulfilled')).toHaveLength(1);const state=(await db.query<any>(`SELECT a.lifecycle_state,(SELECT state FROM booking_schema.alternative_swap_groups WHERE id=$2) proposal_state,(SELECT sum(booked_count) FROM clinic_schema.appointment_slots WHERE id=ANY($3::uuid[])) booked,(SELECT sum(held_count) FROM clinic_schema.appointment_slots WHERE id=ANY($3::uuid[])) held FROM booking_schema.appointments a WHERE a.id=$1`,[f.appointment,proposal.proposalId,[f.source,f.target]])).rows[0];expect(state.lifecycle_state).toBe('CONFIRMED');expect(['ACCEPTED','DECLINED']).toContain(state.proposal_state);expect(Number(state.booked)).toBe(1);expect(Number(state.held)).toBe(0);});

 it('rolls back the confirmed appointment switch when an intermediate event write fails',async()=>{const f=await fixture(db);const proposal=await lifecycle.propose({...command(f),targetSlotId:f.target,expectedTargetSlotVersion:1});await db.query(`CREATE OR REPLACE FUNCTION booking_schema.wave2_fail_reschedule_event() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.event_type='RESCHEDULE_ACCEPTED' THEN RAISE EXCEPTION 'injected'; END IF; RETURN NEW; END $$; CREATE TRIGGER wave2_fail_reschedule_event BEFORE INSERT ON booking_schema.appointment_events FOR EACH ROW EXECUTE FUNCTION booking_schema.wave2_fail_reschedule_event()`);try{await expect(ownerResolution.resolve(proposal.proposalId as string,f.owner,'ACCEPT',{expectedVersion:2,idempotencyKey:randomUUID(),correlationId:randomUUID()},f.hold)).rejects.toBeDefined();const state=(await db.query<any>(`SELECT a.slot_id::text,a.lifecycle_state,(SELECT booked_count FROM clinic_schema.appointment_slots WHERE id=$2) source_booked,(SELECT booked_count FROM clinic_schema.appointment_slots WHERE id=$3) target_booked,(SELECT held_count FROM clinic_schema.appointment_slots WHERE id=$3) target_held,(SELECT state FROM booking_schema.alternative_swap_groups WHERE id=$4) proposal_state FROM booking_schema.appointments a WHERE a.id=$1`,[f.appointment,f.source,f.target,proposal.proposalId])).rows[0];expect(state).toEqual({slot_id:f.source,lifecycle_state:'RESCHEDULE_PROPOSED',source_booked:1,target_booked:0,target_held:1,proposal_state:'PENDING'});}finally{await db.query('DROP TRIGGER IF EXISTS wave2_fail_reschedule_event ON booking_schema.appointment_events; DROP FUNCTION IF EXISTS booking_schema.wave2_fail_reschedule_event()');}});

 it('rejects target drift on accept but still permits Owner rejection',async()=>{const f=await fixture(db);const p=await lifecycle.propose({...command(f),targetSlotId:f.target,expectedTargetSlotVersion:1});await db.query('UPDATE clinic_schema.appointment_slots SET version=version+1 WHERE id=$1',[f.target]);await expect(ownerResolution.resolve(p.proposalId as string,f.owner,'ACCEPT',{expectedVersion:2,idempotencyKey:randomUUID(),correlationId:randomUUID()},f.hold)).rejects.toMatchObject({status:409,response:{code:'BOOKING_STATE_CONFLICT'}});await expect(ownerResolution.resolve(p.proposalId as string,f.owner,'DECLINE',{expectedVersion:2,idempotencyKey:randomUUID(),correlationId:randomUUID()},f.hold)).resolves.toMatchObject({decision:'DECLINE',state:'CONFIRMED'});});

 it('expires a confirmed proposal without losing the original booking or version fence',async()=>{const f=await fixture(db);const p=await lifecycle.propose({...command(f),targetSlotId:f.target,expectedTargetSlotVersion:1});await db.query("UPDATE booking_schema.alternative_swap_groups SET expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[p.proposalId]);await expect(lifecycle.expireRescheduleProposals(1)).resolves.toBe(1);const s=(await db.query<any>(`SELECT a.lifecycle_state,a.version,h.version hold_version,(SELECT state FROM booking_schema.alternative_swap_groups WHERE id=$2) proposal_state,(SELECT booked_count FROM clinic_schema.appointment_slots WHERE id=$3) source_booked,(SELECT held_count FROM clinic_schema.appointment_slots WHERE id=$4) target_held FROM booking_schema.appointments a JOIN booking_schema.booking_holds h ON h.id=a.hold_id WHERE a.id=$1`,[f.appointment,p.proposalId,f.source,f.target])).rows[0];expect(s).toEqual({lifecycle_state:'CONFIRMED',version:3,hold_version:3,proposal_state:'EXPIRED',source_booked:1,target_held:0});await expect(security.releaseHold({holdId:f.hold,actor:{sub:f.owner,roles:[Role.OWNER]},expectedVersion:3,idempotencyKey:randomUUID(),correlationId:randomUUID(),normalizeOwnerNotFound:true})).resolves.toBeDefined();});

 it('Owner cancellation closes a pending proposal and releases both capacities',async()=>{const f=await fixture(db);const p=await lifecycle.propose({...command(f),targetSlotId:f.target,expectedTargetSlotVersion:1});await security.releaseHold({holdId:f.hold,actor:{sub:f.owner,roles:[Role.OWNER]},expectedVersion:2,idempotencyKey:randomUUID(),correlationId:randomUUID(),normalizeOwnerNotFound:true});const s=(await db.query<any>(`SELECT a.lifecycle_state,(SELECT state FROM booking_schema.alternative_swap_groups WHERE id=$2) proposal_state,(SELECT booked_count FROM clinic_schema.appointment_slots WHERE id=$3) source_booked,(SELECT held_count FROM clinic_schema.appointment_slots WHERE id=$4) target_held FROM booking_schema.appointments a WHERE a.id=$1`,[f.appointment,p.proposalId,f.source,f.target])).rows[0];expect(s).toEqual({lifecycle_state:'CANCELLED_BY_USER',proposal_state:'DECLINED',source_booked:0,target_held:0});});

 it('terminal completed and no-show appointments cannot be owner-cancelled or rewritten',async()=>{let f=await fixture(db,-1);await lifecycle.markNoShow(command(f));await expect(security.releaseHold({holdId:f.hold,actor:{sub:f.owner,roles:[Role.OWNER]},expectedVersion:1,idempotencyKey:randomUUID(),correlationId:randomUUID(),normalizeOwnerNotFound:true})).rejects.toMatchObject({status:409});f=await fixture(db,-1);await db.query("UPDATE booking_schema.appointments SET status='COMPLETED',lifecycle_state=NULL WHERE id=$1",[f.appointment]);await db.query("UPDATE booking_schema.booking_holds SET state='COMPLETED' WHERE id=$1",[f.hold]);await expect(lifecycle.markNoShow(command(f))).rejects.toMatchObject({status:409});});

 it('serializes Owner accept versus expiry and restores the original booking',async()=>{const f=await fixture(db);const p=await lifecycle.propose({...command(f),targetSlotId:f.target,expectedTargetSlotVersion:1});await db.query("UPDATE booking_schema.alternative_swap_groups SET expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[p.proposalId]);await Promise.allSettled([ownerResolution.resolve(p.proposalId as string,f.owner,'ACCEPT',{expectedVersion:2,idempotencyKey:randomUUID(),correlationId:randomUUID()},f.hold),lifecycle.expireRescheduleProposals(1)]);const s=(await db.query<any>(`SELECT a.lifecycle_state,(SELECT state FROM booking_schema.alternative_swap_groups WHERE id=$2) proposal_state,(SELECT booked_count FROM clinic_schema.appointment_slots WHERE id=$3) source_booked,(SELECT held_count FROM clinic_schema.appointment_slots WHERE id=$4) target_held FROM booking_schema.appointments a WHERE a.id=$1`,[f.appointment,p.proposalId,f.source,f.target])).rows[0];expect(s).toEqual({lifecycle_state:'CONFIRMED',proposal_state:'EXPIRED',source_booked:1,target_held:0});});

 it('marks no-show only after authoritative start time, exact scope and replays idempotently',async()=>{let f=await fixture(db);await expect(lifecycle.markNoShow(command(f))).rejects.toMatchObject({status:422});f=await fixture(db,-1);await expect(lifecycle.markNoShow({...command(f),employee:{...f.employee,locationIds:[randomUUID()]}})).rejects.toMatchObject({status:403});const cmd=command(f);const result=await lifecycle.markNoShow(cmd);await expect(lifecycle.markNoShow(cmd)).resolves.toEqual(result);const row=(await db.query<any>('SELECT status,lifecycle_state,no_show_at,no_show_by_actor_id::text FROM booking_schema.appointments WHERE id=$1',[f.appointment])).rows[0];expect(row).toMatchObject({status:'NO_SHOW',lifecycle_state:'NO_SHOW',no_show_by_actor_id:f.employee.sub});});
});

const command=(f:Awaited<ReturnType<typeof fixture>>)=>({appointmentId:f.appointment,clinicId:f.clinic,locationId:f.location,employee:f.employee,expectedVersion:1,idempotencyKey:randomUUID(),correlationId:randomUUID()});
async function fixture(db:DatabaseService,hours=3){await db.query('TRUNCATE clinic_schema.clinics,pet_schema.pets,identity_schema.users CASCADE');const owner=randomUUID(),staff=randomUUID(),pet=randomUUID();await db.query('INSERT INTO identity_schema.users(id) VALUES($1),($2)',[owner,staff]);await db.query("INSERT INTO pet_schema.pets(id,owner_id,name,species) VALUES($1,$2,'Wave2','DOG')",[pet,owner]);const clinic=(await db.query<any>("INSERT INTO clinic_schema.clinics(legal_name,public_name) VALUES('W2','W2') RETURNING id")).rows[0].id;const location=(await db.query<any>("INSERT INTO clinic_schema.clinic_locations(clinic_id,address) VALUES($1,'W2') RETURNING id",[clinic])).rows[0].id;await db.query("INSERT INTO clinic_schema.employee_location_memberships(employee_id,clinic_location_id,role) VALUES($1,$2,'CLINIC_RECEPTIONIST')",[staff,location]);const service=(await db.query<any>("INSERT INTO clinic_schema.clinic_services(clinic_location_id,code,display_name,duration_minutes) VALUES($1,'W2','W2',30) RETURNING id",[location])).rows[0].id;const source=(await db.query<any>("INSERT INTO clinic_schema.appointment_slots(clinic_location_id,service_id,starts_at,ends_at,capacity,booked_count,status,integration_mode) VALUES($1,$2,clock_timestamp()+$3*interval '1 hour',clock_timestamp()+($3+1)*interval '1 hour',1,1,'BOOKED','LEVEL_C') RETURNING id",[location,service,hours])).rows[0].id;const target=(await db.query<any>("INSERT INTO clinic_schema.appointment_slots(clinic_location_id,service_id,starts_at,ends_at,capacity,status,integration_mode) VALUES($1,$2,clock_timestamp()+interval '5 hour',clock_timestamp()+interval '6 hour',1,'AVAILABLE','LEVEL_C') RETURNING id",[location,service])).rows[0].id;const hold=(await db.query<any>("INSERT INTO booking_schema.booking_holds(slot_id,owner_id,pet_id,state,expires_at) VALUES($1,$2,$3,'CONFIRMED',clock_timestamp()+interval '1 day') RETURNING id",[source,owner,pet])).rows[0].id;const appointment=(await db.query<any>("INSERT INTO booking_schema.appointments(hold_id,owner_id,pet_id,clinic_location_id,slot_id) VALUES($1,$2,$3,$4,$5) RETURNING id",[hold,owner,pet,location,source])).rows[0].id;return{owner,clinic,location,source,target,hold,appointment,employee:{sub:staff,roles:[Role.CLINIC_RECEPTIONIST],clinicIds:[clinic],locationIds:[location]}};}
