import { Pressable, Text, View } from 'react-native';
import { BodyText, StateMessage } from '@/ui/primitives';
import { uiTokens as t } from '@/ui/tokens';
import type { SpecialistDiscoveryDoctor } from './specialist-discovery-api';

type Pin=Readonly<{clinicId:string;locationId:string;clinicName:string;address:string;latitude:number;longitude:number}>;
export function discoveryPins(doctors:readonly SpecialistDiscoveryDoctor[]):Pin[]{const pins=new Map<string,Pin>();for(const doctor of doctors){if(doctor.latitude===null||doctor.longitude===null)continue;const key=`${doctor.clinicId}:${doctor.locationId}`;if(!pins.has(key))pins.set(key,{clinicId:doctor.clinicId,locationId:doctor.locationId,clinicName:doctor.clinicName,address:doctor.address,latitude:doctor.latitude,longitude:doctor.longitude});}return[...pins.values()].sort((a,b)=>a.clinicName.localeCompare(b.clinicName,'ru')||a.address.localeCompare(b.address,'ru')||a.clinicId.localeCompare(b.clinicId)||a.locationId.localeCompare(b.locationId));}

export function DiscoveryMapSurface({doctors,selectedLocationId,onSelectLocation,onShowList}:{doctors:readonly SpecialistDiscoveryDoctor[];selectedLocationId:string|null;onSelectLocation(pin:Pin):void;onShowList():void}){
  const pins=discoveryPins(doctors);
  if(pins.length===0)return <StateMessage kind="empty" title="Для этих результатов нет координат" body="Доступность остаётся в списке — адреса и время не изменены." action={<Pressable accessibilityRole="button" onPress={onShowList} style={{minHeight:t.layout.minTouch,justifyContent:'center'}}><Text style={{...t.typography.button,color:t.color.accent}}>Открыть список</Text></Pressable>}/>;
  const latitudes=pins.map(pin=>pin.latitude),longitudes=pins.map(pin=>pin.longitude);const minLat=Math.min(...latitudes),maxLat=Math.max(...latitudes),minLon=Math.min(...longitudes),maxLon=Math.max(...longitudes);const latSpan=Math.max(maxLat-minLat,0.01),lonSpan=Math.max(maxLon-minLon,0.01);
  return <View style={{gap:t.spacing.sm}}><View accessibilityLabel="Карта доступных клиник" style={{height:280,borderRadius:t.radius.section,borderWidth:1,borderColor:t.color.separator,backgroundColor:t.color.infoSoft,overflow:'hidden'}}><View style={{position:'absolute',left:'8%',right:'8%',top:'8%',bottom:'8%',borderWidth:1,borderColor:t.color.separator,borderRadius:t.radius.card}}/>{pins.map(pin=>{const left=8+84*((pin.longitude-minLon)/lonSpan),top=8+84*(1-(pin.latitude-minLat)/latSpan),active=pin.locationId===selectedLocationId;return <Pressable key={`${pin.clinicId}:${pin.locationId}`} accessibilityRole="button" accessibilityLabel={`Клиника на карте: ${pin.clinicName}, ${pin.address}`} accessibilityState={{selected:active}} onPress={()=>onSelectLocation(pin)} style={({pressed})=>({position:'absolute',left:`${left}%`,top:`${top}%`,width:48,height:48,marginLeft:-24,marginTop:-24,borderRadius:24,alignItems:'center',justifyContent:'center',borderWidth:3,borderColor:active?t.color.accent:t.color.surface,backgroundColor:t.color.accent,opacity:pressed?0.7:1,...t.shadow.card})}><Text style={{...t.typography.label,color:t.color.onAccent}}>●</Text></Pressable>;})}</View><BodyText secondary>Пины показывают только координаты из карточки локации. Карта не ранжирует клиники и не определяет доступность.</BodyText></View>;
}
