import { act, fireEvent, render, waitFor } from '@testing-library/react-native';
import { SpecialistDiscoveryScreen } from './SpecialistDiscoveryScreen';
const SP='11111111-1111-4111-8111-111111111111',D='22222222-2222-4222-8222-222222222222',S='33333333-3333-4333-8333-333333333333',C='44444444-4444-4444-8444-444444444444',L='55555555-5555-4555-8555-555555555555',T='66666666-6666-4666-8666-666666666666';
const options={observedAt:'2026-08-29T08:00:00.000Z',specialties:[{specialtyId:SP,name:'Терапевт'}],services:[{serviceCode:'PRIMARY_EXAM',name:'Первичный приём'}]};
const data={observedAt:'2026-08-29T08:00:00.000Z',limit:50,doctors:[{specialtyId:SP,specialtyName:'Терапевт',doctorId:D,doctorName:'Анна Вет',serviceId:S,serviceCode:'PRIMARY_EXAM',serviceName:'Первичный приём',clinicId:C,clinicName:'ВетКлиника',locationId:L,address:'Москва',timezone:'Europe/Moscow',latitude:55.7558,longitude:37.6173,slots:[{slotId:T,startsAt:'2026-08-30T08:00:00.000Z',endsAt:'2026-08-30T08:30:00.000Z',expectedVersion:3}]}]};
const mockUseQuery=jest.fn();
jest.mock('@tanstack/react-query',()=>({useQuery:(input:unknown)=>mockUseQuery(input)}));
jest.mock('@/session/SessionProvider',()=>({useSession:()=>({session:{cacheScope:'owner',opaqueCredential:'token'}})}));
function queries(resultState:Record<string,unknown>={isPending:false,isError:false,data,refetch:jest.fn().mockResolvedValue({data,isError:false})},optionState:Record<string,unknown>={isPending:false,isError:false,data:options,refetch:jest.fn()}){mockUseQuery.mockImplementation((input:{queryKey:string[]})=>input.queryKey.includes('specialist-discovery-options')?optionState:resultState);}
describe('SpecialistDiscoveryScreen',()=>{
  beforeEach(()=>mockUseQuery.mockReset());
  it.each([['Терапевт',false],['Первичный приём',true]] as const)('supports %s entry and hands off exact eligible identities',async(label,serviceFirst)=>{queries();const onContinue=jest.fn();const screen=await render(<SpecialistDiscoveryScreen onClose={jest.fn()} onContinue={onContinue}/>);if(serviceFirst){await act(async()=>fireEvent.press(screen.getByText('По услуге')));await waitFor(()=>expect(screen.getByText(label)).toBeTruthy());}await act(async()=>fireEvent.press(screen.getByText(label)));const slot=await screen.findByLabelText(/^Анна Вет,/);await act(async()=>fireEvent.press(slot));await waitFor(()=>expect(screen.getByLabelText(/^Анна Вет,/).props.accessibilityState.selected).toBe(true));await act(async()=>fireEvent.press(screen.getByText('Продолжить')));await waitFor(()=>expect(onContinue).toHaveBeenCalledWith({specialtyId:SP,doctorId:D,serviceId:S,clinicId:C,locationId:L,slotId:T,expectedSlotVersion:3}));expect(screen.getByText('ВетКлиника · Москва')).toBeTruthy();});
  it('maps an API-derived pin to the exact location and preserves doctor/service/slot selection',async()=>{queries();const onContinue=jest.fn();const screen=await render(<SpecialistDiscoveryScreen onClose={jest.fn()} onContinue={onContinue}/>);await act(async()=>fireEvent.press(screen.getByText('Терапевт')));await waitFor(()=>expect(screen.getByText('Карта')).toBeTruthy());await act(async()=>fireEvent.press(screen.getByText('Карта')));const pin=await screen.findByLabelText('Клиника на карте: ВетКлиника, Москва');await act(async()=>fireEvent.press(pin));expect(pin.props.accessibilityState.selected).toBe(true);const slot=await screen.findByLabelText(/^Анна Вет,/);await act(async()=>fireEvent.press(slot));await act(async()=>fireEvent.press(screen.getByText('Продолжить')));await waitFor(()=>expect(onContinue).toHaveBeenCalledWith({specialtyId:SP,doctorId:D,serviceId:S,clinicId:C,locationId:L,slotId:T,expectedSlotVersion:3}));});
  it('keeps a usable list fallback for null-coordinate results',async()=>{queries({isPending:false,isError:false,data:{...data,doctors:[{...data.doctors[0],latitude:null,longitude:null}]},refetch:jest.fn()});const screen=await render(<SpecialistDiscoveryScreen onClose={jest.fn()} onContinue={jest.fn()}/>);await act(async()=>fireEvent.press(screen.getByText('Терапевт')));await act(async()=>fireEvent.press(await screen.findByText('Карта')));expect(await screen.findByText('Для этих результатов нет координат')).toBeTruthy();await act(async()=>fireEvent.press(screen.getByText('Открыть список')));expect(screen.getByText('Анна Вет')).toBeTruthy();});
  it.each([[{isPending:true,isError:false},'Загружаем направления'],[{isPending:false,isError:false,data:{...options,specialties:[],services:[]}},'Сейчас нет направлений с доступным временем'],[{isPending:false,isError:true,refetch:jest.fn()},'Не удалось загрузить направления']] as const)('renders options state %#',async(state,label)=>{queries(undefined,state as never);expect((await render(<SpecialistDiscoveryScreen onClose={jest.fn()} onContinue={jest.fn()}/>)).getByText(label)).toBeTruthy();});
  it('retries errors and rejects a selection removed by authoritative refresh',async()=>{const retry=jest.fn(),refetch=jest.fn().mockResolvedValue({data:{...data,doctors:[]},isError:false});queries({isPending:false,isError:false,data,refetch});const screen=await render(<SpecialistDiscoveryScreen onClose={jest.fn()} onContinue={jest.fn()}/>);await act(async()=>fireEvent.press(screen.getByText('Терапевт')));const slot=await screen.findByLabelText(/^Анна Вет,/);await act(async()=>fireEvent.press(slot));await waitFor(()=>expect(screen.getByLabelText(/^Анна Вет,/).props.accessibilityState.selected).toBe(true));await act(async()=>fireEvent.press(screen.getByText('Продолжить')));await waitFor(()=>expect(screen.getByText('Выбранное время больше недоступно')).toBeTruthy());queries({isPending:false,isError:true,refetch:retry});const failed=await render(<SpecialistDiscoveryScreen onClose={jest.fn()} onContinue={jest.fn()}/>);await act(async()=>fireEvent.press(failed.getByText('Терапевт')));await waitFor(()=>expect(failed.getByText('Повторить')).toBeTruthy());fireEvent.press(failed.getByText('Повторить'));expect(retry).toHaveBeenCalled();});
});
