import { createSpecialistDiscoveryApi, parseSpecialistDiscovery } from './specialist-discovery-api';
const SP='11111111-1111-4111-8111-111111111111',D='22222222-2222-4222-8222-222222222222',S='33333333-3333-4333-8333-333333333333',C='44444444-4444-4444-8444-444444444444',L='55555555-5555-4555-8555-555555555555',T='66666666-6666-4666-8666-666666666666';
const options={observedAt:'2026-08-29T08:00:00.000Z',specialties:[{specialtyId:SP,name:'Терапевт'}],services:[{serviceId:S,specialtyId:SP,serviceCode:'PRIMARY_EXAM',name:'Первичный приём'}]};
const result={observedAt:'2026-08-29T08:00:00.000Z',limit:50,doctors:[{specialtyId:SP,specialtyName:'Терапевт',doctorId:D,doctorName:'Анна Вет',serviceId:S,serviceCode:'PRIMARY_EXAM',serviceName:'Первичный приём',clinicId:C,clinicName:'ВетКлиника',locationId:L,address:'Москва',timezone:'Europe/Moscow',latitude:55.7558,longitude:37.6173,slots:[{slotId:T,startsAt:'2026-08-30T08:00:00.000Z',endsAt:'2026-08-30T08:30:00.000Z',expectedVersion:3}]}]};
describe('specialist discovery api',()=>{
  it('uses exact Owner selectors and the authoritative service identity',async()=>{const request=jest.fn().mockResolvedValue(result);const api=createSpecialistDiscoveryApi({request});await api.searchByServiceId('token',S);expect(request).toHaveBeenCalledWith(`v1/owner/clinic-catalog/specialist-discovery?serviceId=${S}&limit=50`,expect.objectContaining({headers:{Authorization:'Bearer token'}}));await expect(api.searchByServiceId('token','bad')).rejects.toThrow('INVALID_SPECIALIST_SERVICE_ID');});
  it('uses the exact service identity from the authoritative taxonomy option',async()=>{const request=jest.fn().mockResolvedValueOnce(options).mockResolvedValueOnce(result);const api=createSpecialistDiscoveryApi({request});const parsed=await api.options('token');await api.search('token',{kind:'SERVICE',...parsed.services[0]});expect(request).toHaveBeenLastCalledWith(`v1/owner/clinic-catalog/specialist-discovery?serviceId=${S}&limit=50`,expect.anything());});
  it('fails closed for service choices without exact taxonomy identities',async()=>{const request=jest.fn().mockResolvedValue({...options,services:[{serviceCode:'PRIMARY_EXAM',name:'Первичный приём'}]});await expect(createSpecialistDiscoveryApi({request}).options('token')).rejects.toThrow('INVALID_SPECIALIST_OPTIONS_RESPONSE');});
  it('accepts null coordinates for list-only locations',()=>expect(parseSpecialistDiscovery({...result,doctors:[{...result.doctors[0],latitude:null,longitude:null}]}).doctors[0]).toMatchObject({latitude:null,longitude:null}));
  it.each([{...result,coordinates:{latitude:1,longitude:2}},{...result,doctors:[{...result.doctors[0],staffId:D}]},{...result,doctors:[{...result.doctors[0],timezone:'not/a real zone'}]},{...result,doctors:[{...result.doctors[0],latitude:91}]},{...result,doctors:[{...result.doctors[0],longitude:181}]},{...result,doctors:[{...result.doctors[0],slots:[{...result.doctors[0].slots[0],expectedVersion:0}]}]},{...result,doctors:Array.from({length:51},()=>result.doctors[0])}])('fails closed for extra, private, malformed, or unbounded data',value=>expect(()=>parseSpecialistDiscovery(value)).toThrow('INVALID_SPECIALIST_DISCOVERY_RESPONSE'));
});
