import { act, fireEvent, render, waitFor } from "@testing-library/react-native";
import { SpecialistSelectionScreen } from "./SpecialistSelectionScreen";
const SP="11111111-1111-4111-8111-111111111111",D="22222222-2222-4222-8222-222222222222",S="33333333-3333-4333-8333-333333333333",C="44444444-4444-4444-8444-444444444444",L="55555555-5555-4555-8555-555555555555",T="66666666-6666-4666-8666-666666666666";
const mockUseQuery=jest.fn();
jest.mock("@tanstack/react-query",()=>({useQuery:(value:unknown)=>mockUseQuery(value)}));
jest.mock("@/session/SessionProvider",()=>({useSession:()=>({session:{cacheScope:"owner-a",opaqueCredential:"token-a"}})}));
const doctor={specialtyId:SP,specialtyName:"Терапевт",doctorId:D,doctorName:"Анна Вет",serviceId:S,serviceCode:"PRIMARY_EXAM",serviceName:"Первичный приём",clinicId:C,clinicName:"ВетКлиника",locationId:L,address:"Москва",timezone:"Europe/Moscow",latitude:null,longitude:null,slots:[{slotId:T,startsAt:"2026-09-10T08:00:00.000Z",endsAt:"2026-09-10T08:30:00.000Z",expectedVersion:3}]};
const data={observedAt:"2026-09-08T08:00:00.000Z",limit:50,doctors:[doctor]};
const context={clinicId:C,locationId:L,serviceId:S};
describe("SpecialistSelectionScreen",()=>{
  it("selects exactly one safe public identity and revalidates before handoff",async()=>{const onContinue=jest.fn(),refetch=jest.fn().mockResolvedValue({data,isError:false});mockUseQuery.mockReturnValue({isPending:false,isError:false,isFetching:false,data,refetch});const screen=await render(<SpecialistSelectionScreen context={context} petName="Рекс" onBack={jest.fn()} onContinue={onContinue}/>);expect(screen.getByText(/Рекс/)).toBeTruthy();fireEvent.press(screen.getByRole("radio"));await waitFor(()=>expect(screen.getByRole("radio").props.accessibilityState.selected).toBe(true));fireEvent.press(screen.getByText("Выбрать время"));await waitFor(()=>expect(onContinue).toHaveBeenCalledWith(expect.objectContaining({doctorId:D,serviceId:S,clinicId:C,locationId:L,slots:doctor.slots})));expect(refetch).toHaveBeenCalledTimes(1);expect(screen.queryByText(/рейтинг|отзыв|стаж/i)).toBeNull();});
  it("clears a specialist removed by authoritative refresh",async()=>{const refetch=jest.fn().mockResolvedValue({data:{...data,doctors:[]},isError:false});mockUseQuery.mockReturnValue({isPending:false,isError:false,isFetching:false,data,refetch});const screen=await render(<SpecialistSelectionScreen context={context} onBack={jest.fn()} onContinue={jest.fn()}/>);fireEvent.press(screen.getByRole("radio"));await waitFor(()=>expect(screen.getByRole("radio").props.accessibilityState.selected).toBe(true));await act(async()=>fireEvent.press(screen.getByText("Выбрать время")));await waitFor(()=>expect(screen.getByText("Специалист больше недоступен")).toBeTruthy());});
  it.each([[{isPending:true,isError:false,isFetching:true,refetch:jest.fn()},"Загружаем специалистов"],[{isPending:false,isError:true,isFetching:false,refetch:jest.fn()},"Не удалось загрузить специалистов"],[{isPending:false,isError:false,isFetching:false,data:{...data,doctors:[]},refetch:jest.fn()},"Сейчас нет доступных специалистов"]] as const)("renders bounded state %#",async(state,label)=>{mockUseQuery.mockReturnValue(state);expect((await render(<SpecialistSelectionScreen context={context} onBack={jest.fn()} onContinue={jest.fn()}/>)).getByText(label)).toBeTruthy();});
  it("fails closed for specialists from another journey context",async()=>{mockUseQuery.mockReturnValue({isPending:false,isError:false,isFetching:false,data:{...data,doctors:[{...doctor,locationId:SP}]},refetch:jest.fn()});const screen=await render(<SpecialistSelectionScreen context={context} onBack={jest.fn()} onContinue={jest.fn()}/>);expect(screen.getByText("Сейчас нет доступных специалистов")).toBeTruthy();expect(screen.queryByText("Анна Вет")).toBeNull();});
  it("locks specialist choice while authority revalidation is pending",async()=>{let resolve!:(value:unknown)=>void;const refetch=jest.fn().mockReturnValue(new Promise(value=>{resolve=value;}));mockUseQuery.mockReturnValue({isPending:false,isError:false,isFetching:false,data,refetch});const screen=await render(<SpecialistSelectionScreen context={context} onBack={jest.fn()} onContinue={jest.fn()}/>);fireEvent.press(screen.getByRole("radio"));await waitFor(()=>expect(screen.getByRole("radio").props.accessibilityState.selected).toBe(true));fireEvent.press(screen.getByRole("button",{name:"Выбрать время"}));await waitFor(()=>expect(screen.getByRole("radio").props.accessibilityState.disabled).toBe(true));await act(async()=>resolve({data,isError:false}));});
});
