export const TELEMED_AUDIT_CODES = ['ASSIGNED', 'SAFETY_ESCALATED', 'RECOMMENDATION_SAVED', 'FOLLOW_UP_ROUTED', 'SESSION_STARTED', 'DOCTOR_CONNECTED', 'OWNER_CANCELLED', 'DOCTOR_TIMEOUT'] as const;
export type TelemedAuditCode = (typeof TELEMED_AUDIT_CODES)[number];
export type TelemedAuditItem = { id: string; eventType: TelemedAuditCode; summaryCode: TelemedAuditCode; createdAt: string };
export type TelemedAuditTrail = { caseId: string; serverNow: string; items: TelemedAuditItem[] };

const KEYS = ['caseId', 'items', 'serverNow']; const ITEM_KEYS = ['createdAt', 'eventType', 'id', 'summaryCode'];
const RFC3339 = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?(?:Z|[+-](\d{2}):(\d{2}))$/;
function sameKeys(value: object, keys: string[]) { return Object.keys(value).sort().join('|') === keys.join('|'); }
function timestamp(value: unknown): value is string { if (typeof value !== 'string') return false; const match = RFC3339.exec(value); if (!match) return false; const year = Number(match[1]); const month = Number(match[2]); const day = Number(match[3]); const hour = Number(match[4]); const minute = Number(match[5]); const second = Number(match[6]); const offsetHour = match[7] === undefined ? undefined : Number(match[7]); const offsetMinute = match[8] === undefined ? undefined : Number(match[8]); return month >= 1 && month <= 12 && day >= 1 && day <= new Date(Date.UTC(year, month, 0)).getUTCDate() && hour <= 23 && minute <= 59 && second <= 59 && (offsetHour === undefined || (offsetHour <= 23 && offsetMinute !== undefined && offsetMinute <= 59)) && Number.isFinite(Date.parse(value)); }
function code(value: unknown): value is TelemedAuditCode { return typeof value === 'string' && TELEMED_AUDIT_CODES.includes(value as TelemedAuditCode); }
function item(value: unknown): TelemedAuditItem | null { if (!value || typeof value !== 'object' || !sameKeys(value, ITEM_KEYS)) return null; const row = value as Record<string, unknown>; if (typeof row.id !== 'string' || row.id.length === 0 || !code(row.eventType) || !code(row.summaryCode) || row.eventType !== row.summaryCode || !timestamp(row.createdAt)) return null; return { id: row.id, eventType: row.eventType, summaryCode: row.summaryCode, createdAt: row.createdAt }; }
export function parseTelemedAuditTrail(value: unknown): TelemedAuditTrail | null { if (!value || typeof value !== 'object' || !sameKeys(value, KEYS)) return null; const row = value as Record<string, unknown>; if (typeof row.caseId !== 'string' || !timestamp(row.serverNow) || !Array.isArray(row.items)) return null; const items = row.items.map(item); return items.every((entry): entry is TelemedAuditItem => entry !== null) ? { caseId: row.caseId, serverNow: row.serverNow, items } : null; }
