import { act, fireEvent, render, waitFor } from '@testing-library/react-native';
import { ApiError } from '@/api/errors';
import { BookingReviewScreen } from './BookingReviewScreen';

const mockCreate=jest.fn();
const mockRead=jest.fn();
jest.mock('./booking-api',()=>({bookingApi:{create:(...args:unknown[])=>mockCreate(...args),read:(...args:unknown[])=>mockRead(...args)}}));
jest.mock('@/session/SessionProvider',()=>({useSession:()=>({session:{cacheScope:'owner-a',opaqueCredential:'credential-a'}})}));
const ids={petId:'11111111-1111-4111-8111-111111111111',clinicId:'22222222-2222-4222-8222-222222222222',locationId:'33333333-3333-4333-8333-333333333333',serviceId:'44444444-4444-4444-8444-444444444444',slotId:'55555555-5555-4555-8555-555555555555'};
const result={holdId:'66666666-6666-4666-8666-666666666666',status:'PENDING_CONFIRMATION',slotId:ids.slotId,expiresAt:'2026-08-13T12:00:00.000Z',lastUpdatedAt:'2026-08-13T11:00:00.000Z',correlationId:'77777777-7777-4777-8777-777777777777',serverNow:'2026-08-13T11:00:00.000Z',aggregateVersion:1,confirmationMode:'MANUAL',nextAction:'READ_STATUS'};
const pending={holdId:result.holdId,slotId:ids.slotId,status:'PENDING_CONFIRMATION',statusCode:'PENDING_CONFIRMATION',statusTitle:'Клиника подтверждает заявку',safeDescription:'Ожидаем подтверждение выбранного времени клиникой.',nextActionCode:'WAIT',confirmationMode:'MANUAL',expiresAt:result.expiresAt,serverNow:result.serverNow,aggregateVersion:1,lastUpdatedAt:result.lastUpdatedAt,pet:{id:ids.petId,name:'Барсик',species:'CAT'},clinic:{id:ids.clinicId,name:'Добрый доктор'},location:{id:ids.locationId,address:'ул. Добра, 1'},service:{id:ids.serviceId,name:'Осмотр'},doctor:null,slot:{startsAt:'2026-08-14T08:00:00.000Z',endsAt:'2026-08-14T08:30:00.000Z',timezone:'Europe/Moscow'},clinicLocationId:ids.locationId,startsAt:'2026-08-14T08:00:00.000Z',endsAt:'2026-08-14T08:30:00.000Z'};
const mockSnapshots=new Map<string,unknown>([
  [JSON.stringify(['owner','owner-a','pets']),[{petId:ids.petId,name:'Барсик',species:'CAT',createdAt:'2026-01-01',updatedAt:'2026-01-01'}]],
  [JSON.stringify(['owner','owner-a','clinic-services',ids.clinicId,ids.locationId]),{name:'Добрый доктор',services:[{serviceId:ids.serviceId,name:'Осмотр',price:{kind:'INFORMATIONAL',amount:'1500.00',currency:'RUB'}}]}],
  [JSON.stringify(['owner','owner-a','session','g1','availability',ids.clinicId,ids.locationId,ids.serviceId]),{slots:[{slotId:ids.slotId,expectedVersion:3,localDate:'2026-08-14',localTime:'11:00'}]}],
]);
jest.mock('@tanstack/react-query',()=>({useQueryClient:()=>({getQueryData:(key:unknown[])=>mockSnapshots.get(JSON.stringify(key))})}));
const props={petId:ids.petId,context:{clinicId:ids.clinicId,locationId:ids.locationId,serviceId:ids.serviceId,slotId:ids.slotId,expectedSlotVersion:3},authorityGeneration:'g1',onBack:jest.fn(),onConflict:jest.fn()};
jest.setTimeout(15_000);
describe('BookingReviewScreen',()=>{
  beforeAll(()=>{Object.defineProperty(globalThis,'crypto',{configurable:true,value:{randomUUID:()=> '88888888-8888-4888-8888-888888888888'}});});
  beforeEach(()=>{mockCreate.mockReset();mockRead.mockReset().mockResolvedValue(pending);props.onBack.mockReset();props.onConflict.mockReset();});
  it('shows review, single-flights submit and distinguishes waiting from confirmation',async()=>{let resolve!:(value:unknown)=>void;mockCreate.mockReturnValue(new Promise(value=>{resolve=value;}));const view=await render(<BookingReviewScreen {...props}/>);expect(view.getByText('Питомец: Барсик')).toBeTruthy();fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(view.getByText('Отправляем…')).toBeTruthy());fireEvent.press(view.getByText('Отправляем…'));expect(mockCreate).toHaveBeenCalledTimes(1);await act(async()=>{resolve(result);});await waitFor(()=>expect(view.getAllByText('Клиника подтверждает заявку').length).toBeGreaterThan(0));expect(view.getByText('Это ещё не подтверждённая запись.')).toBeTruthy();});
  it('keeps the same command context for an uncertain retry',async()=>{mockCreate.mockRejectedValueOnce(new ApiError('TIMEOUT','timeout')).mockResolvedValueOnce(result);const view=await render(<BookingReviewScreen {...props}/>);fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(view.getByText('Проверить заявку')).toBeTruthy());fireEvent.press(view.getByText('Проверить заявку'));await waitFor(()=>expect(view.getAllByText('Клиника подтверждает заявку').length).toBeGreaterThan(0));expect(mockCreate).toHaveBeenCalledTimes(2);expect(mockCreate.mock.calls[1][1]).toEqual(mockCreate.mock.calls[0][1]);expect(mockCreate.mock.calls[1][2]).toBe(mockCreate.mock.calls[0][2]);});
  it('reads the returned hold and refreshes PENDING to server-authored CONFIRMED',async()=>{mockCreate.mockResolvedValue(result);mockRead.mockResolvedValueOnce(pending).mockResolvedValueOnce({...pending,status:'CONFIRMED',statusCode:'CONFIRMED',statusTitle:'Запись подтверждена',safeDescription:'Клиника подтвердила выбранное время.',nextActionCode:'VIEW_APPOINTMENT',aggregateVersion:2});const view=await render(<BookingReviewScreen {...props}/>);fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(view.getAllByText('Клиника подтверждает заявку').length).toBeGreaterThan(0));expect(mockRead).toHaveBeenCalledWith('credential-a',result.holdId);fireEvent.press(view.getByText('Обновить статус'));await waitFor(()=>expect(view.getAllByText('Запись подтверждена').length).toBeGreaterThan(0));expect(view.getAllByText('Клиника подтвердила выбранное время.').length).toBeGreaterThan(0);expect(mockCreate).toHaveBeenCalledTimes(1);});
  it.each([['REJECTED','Клиника отклонила заявку'],['CANCELLED','Заявка отменена'],['EXPIRED','Время ожидания истекло']])('renders %s using server-authored status text',async(status,title)=>{mockCreate.mockResolvedValue(result);mockRead.mockResolvedValue({...pending,status,statusCode:status,statusTitle:title,safeDescription:`Описание ${status}`,nextActionCode:'CHOOSE_ANOTHER_SLOT'});const view=await render(<BookingReviewScreen {...props}/>);fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(view.getAllByText(title).length).toBeGreaterThan(0));expect(view.getAllByText(`Описание ${status}`).length).toBeGreaterThan(0);});
  it('preserves the last authoritative status and exposes retry after read failure',async()=>{mockCreate.mockResolvedValue(result);mockRead.mockResolvedValueOnce(pending).mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce({...pending,aggregateVersion:2});const view=await render(<BookingReviewScreen {...props}/>);fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(view.getAllByText('Клиника подтверждает заявку').length).toBeGreaterThan(0));fireEvent.press(view.getByText('Обновить статус'));await waitFor(()=>expect(view.getByText('Не удалось обновить статус. Последний полученный статус сохранён.')).toBeTruthy());expect(view.getAllByText('Клиника подтверждает заявку').length).toBeGreaterThan(0);fireEvent.press(view.getByText('Обновить статус'));await waitFor(()=>expect(mockRead).toHaveBeenCalledTimes(3));expect(mockCreate).toHaveBeenCalledTimes(1);});
  it('never claims success for a controlled conflict',async()=>{mockCreate.mockRejectedValue(new ApiError('CONFLICT','conflict',409));const view=await render(<BookingReviewScreen {...props}/>);fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(view.getByText('Это время уже недоступно. Выберите другое.')).toBeTruthy());expect(view.queryByText('Ожидает подтверждения клиникой')).toBeNull();fireEvent.press(view.getByText('Выбрать другое время'));expect(props.onConflict).toHaveBeenCalledTimes(1);});
  it('routes canonical stale conflicts back to availability',async()=>{mockCreate.mockRejectedValue(new ApiError('CONFLICT','conflict',409,undefined,'BOOKING_STATE_CONFLICT'));const view=await render(<BookingReviewScreen {...props}/>);fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(view.getByText('Это время уже недоступно. Выберите другое.')).toBeTruthy());fireEvent.press(view.getByText('Выбрать другое время'));expect(props.onConflict).toHaveBeenCalledTimes(1);expect(view.queryByText('Ожидает подтверждения клиникой')).toBeNull();});
  it('fails canonical idempotency conflicts closed without retrying',async()=>{mockCreate.mockRejectedValue(new ApiError('CONFLICT','conflict',409,undefined,'IDEMPOTENCY_CONFLICT'));const view=await render(<BookingReviewScreen {...props}/>);fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(view.getByText('Данные заявки изменились. Вернитесь к выбору и начните отправку заново.')).toBeTruthy());expect(view.getByRole('button',{name:'Отправить заявку'}).props.accessibilityState.disabled).toBe(true);fireEvent.press(view.getByText('Вернуться к выбору'));expect(props.onBack).toHaveBeenCalledTimes(1);expect(mockCreate).toHaveBeenCalledTimes(1);expect(view.queryByText('Ожидает подтверждения клиникой')).toBeNull();});
  it('ignores a late success after the journey unmounts',async()=>{let resolve!:(value:unknown)=>void;mockCreate.mockReturnValue(new Promise(value=>{resolve=value;}));const view=await render(<BookingReviewScreen {...props}/>);fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(mockCreate).toHaveBeenCalledTimes(1));view.unmount();await act(async()=>{resolve(result);});expect(view.queryByText('Ожидает подтверждения клиникой')).toBeNull();});
});
