import { act, fireEvent, render, waitFor } from '@testing-library/react-native';
import { ApiError } from '@/api/errors';
import { BookingReviewScreen } from './BookingReviewScreen';

const mockCreate=jest.fn();
const mockPersist=jest.fn();
jest.mock('./booking-api',()=>({bookingApi:{create:(...args:unknown[])=>mockCreate(...args)}}));
jest.mock('./active-booking-store',()=>({activeBookingStore:{write:(...args:unknown[])=>mockPersist(...args)}}));
jest.mock('@/session/SessionProvider',()=>({useSession:()=>({session:{cacheScope:'owner-a',opaqueCredential:'credential-a'}})}));
const ids={petId:'11111111-1111-4111-8111-111111111111',clinicId:'22222222-2222-4222-8222-222222222222',locationId:'33333333-3333-4333-8333-333333333333',serviceId:'44444444-4444-4444-8444-444444444444',slotId:'55555555-5555-4555-8555-555555555555'};
const result={holdId:'66666666-6666-4666-8666-666666666666',status:'PENDING_CONFIRMATION',slotId:ids.slotId,expiresAt:'2026-08-13T12:00:00.000Z',lastUpdatedAt:'2026-08-13T11:00:00.000Z',correlationId:'77777777-7777-4777-8777-777777777777',serverNow:'2026-08-13T11:00:00.000Z',aggregateVersion:1,confirmationMode:'MANUAL',nextAction:'READ_STATUS'};
const mockSnapshots=new Map<string,unknown>([
  [JSON.stringify(['owner','owner-a','pets']),[{petId:ids.petId,name:'Барсик',species:'CAT',createdAt:'2026-01-01',updatedAt:'2026-01-01'}]],
  [JSON.stringify(['owner','owner-a','clinic-services',ids.clinicId,ids.locationId]),{name:'Добрый доктор',services:[{serviceId:ids.serviceId,name:'Осмотр',price:{kind:'INFORMATIONAL',amount:'1500.00',currency:'RUB'}}]}],
  [JSON.stringify(['owner','owner-a','session','g1','availability',ids.clinicId,ids.locationId,ids.serviceId]),{slots:[{slotId:ids.slotId,expectedVersion:3,localDate:'2026-08-14',localTime:'11:00'}]}],
]);
jest.mock('@tanstack/react-query',()=>({useQueryClient:()=>({getQueryData:(key:unknown[])=>mockSnapshots.get(JSON.stringify(key))})}));
const props={petId:ids.petId,context:{clinicId:ids.clinicId,locationId:ids.locationId,serviceId:ids.serviceId,slotId:ids.slotId,expectedSlotVersion:3},authorityGeneration:'g1',onBack:jest.fn(),onConflict:jest.fn(),onCreated:jest.fn()};
jest.setTimeout(15_000);
describe('BookingReviewScreen',()=>{
  beforeAll(()=>{Object.defineProperty(globalThis,'crypto',{configurable:true,value:{randomUUID:()=> '88888888-8888-4888-8888-888888888888'}});});
  beforeEach(()=>{mockCreate.mockReset();mockPersist.mockReset().mockResolvedValue(undefined);props.onBack.mockReset();props.onConflict.mockReset();props.onCreated.mockReset();});
  it('fails durable re-entry persistence closed and retries storage without resubmitting create',async()=>{mockCreate.mockResolvedValue(result);mockPersist.mockRejectedValueOnce(new Error('secure store unavailable')).mockResolvedValueOnce(undefined);const view=await render(<BookingReviewScreen {...props}/>);fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(view.getByText('Заявка создана, но не удалось сохранить её для повторного открытия.')).toBeTruthy());expect(props.onCreated).not.toHaveBeenCalled();fireEvent.press(view.getByText('Повторить сохранение'));await waitFor(()=>expect(props.onCreated).toHaveBeenCalledWith(result.holdId));expect(mockCreate).toHaveBeenCalledTimes(1);expect(mockPersist).toHaveBeenCalledTimes(2);});
  it('shows review, single-flights submit and distinguishes waiting from confirmation',async()=>{let resolve!:(value:unknown)=>void;mockCreate.mockReturnValue(new Promise(value=>{resolve=value;}));const view=await render(<BookingReviewScreen {...props}/>);expect(view.getByText('Питомец')).toBeTruthy();expect(view.getByText('Барсик')).toBeTruthy();fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(view.getByText('Отправляем…')).toBeTruthy());fireEvent.press(view.getByText('Отправляем…'));expect(mockCreate).toHaveBeenCalledTimes(1);await act(async()=>{resolve(result);});await waitFor(()=>expect(view.getByText('Ожидает подтверждения клиникой')).toBeTruthy());expect(view.queryByText(/Это ещё не подтверждённая запись/)).toBeNull();});
  it('keeps the same command context for an uncertain retry',async()=>{mockCreate.mockRejectedValueOnce(new ApiError('TIMEOUT','timeout')).mockResolvedValueOnce(result);const view=await render(<BookingReviewScreen {...props}/>);fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(view.getByText('Проверить заявку')).toBeTruthy());fireEvent.press(view.getByText('Проверить заявку'));await waitFor(()=>expect(view.getByText('Ожидает подтверждения клиникой')).toBeTruthy());expect(mockCreate).toHaveBeenCalledTimes(2);expect(mockCreate.mock.calls[1][1]).toEqual(mockCreate.mock.calls[0][1]);expect(mockCreate.mock.calls[1][2]).toBe(mockCreate.mock.calls[0][2]);});
  it('never claims success for a controlled conflict',async()=>{mockCreate.mockRejectedValue(new ApiError('CONFLICT','conflict',409));const view=await render(<BookingReviewScreen {...props}/>);fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(view.getByText('Это время уже недоступно. Выберите другое.')).toBeTruthy());expect(view.queryByText('Ожидает подтверждения клиникой')).toBeNull();fireEvent.press(view.getByText('Выбрать другое время'));expect(props.onConflict).toHaveBeenCalledTimes(1);});
  it('routes canonical stale conflicts back to availability',async()=>{mockCreate.mockRejectedValue(new ApiError('CONFLICT','conflict',409,undefined,'BOOKING_STATE_CONFLICT'));const view=await render(<BookingReviewScreen {...props}/>);fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(view.getByText('Это время уже недоступно. Выберите другое.')).toBeTruthy());fireEvent.press(view.getByText('Выбрать другое время'));expect(props.onConflict).toHaveBeenCalledTimes(1);expect(view.queryByText('Ожидает подтверждения клиникой')).toBeNull();});
  it('fails canonical idempotency conflicts closed without retrying',async()=>{mockCreate.mockRejectedValue(new ApiError('CONFLICT','conflict',409,undefined,'IDEMPOTENCY_CONFLICT'));const view=await render(<BookingReviewScreen {...props}/>);fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(view.getByText('Данные заявки изменились. Вернитесь к выбору и начните отправку заново.')).toBeTruthy());expect(view.getByRole('button',{name:'Отправить заявку'}).props.accessibilityState.disabled).toBe(true);fireEvent.press(view.getByText('Вернуться к выбору'));expect(props.onBack).toHaveBeenCalledTimes(1);expect(mockCreate).toHaveBeenCalledTimes(1);expect(view.queryByText('Ожидает подтверждения клиникой')).toBeNull();});
  it('ignores a late success after the journey unmounts',async()=>{let resolve!:(value:unknown)=>void;mockCreate.mockReturnValue(new Promise(value=>{resolve=value;}));const view=await render(<BookingReviewScreen {...props}/>);fireEvent.press(view.getByText('Отправить заявку'));await waitFor(()=>expect(mockCreate).toHaveBeenCalledTimes(1));await view.unmount();await act(async()=>{resolve(result);});expect(view.queryByText('Ожидает подтверждения клиникой')).toBeNull();});
});
