import {fireEvent,render,waitFor} from '@testing-library/react-native';
import {ApiError} from '@/api/errors';
import {BookingChangeRequestPanel} from './BookingChangeRequestPanel';

const mockRead=jest.fn(),mockCreate=jest.fn();
jest.mock('./booking-api',()=>({...jest.requireActual('./booking-api'),bookingApi:{readCurrentChangeRequest:(...args:unknown[])=>mockRead(...args),createChangeRequest:(...args:unknown[])=>mockCreate(...args)}}));
jest.mock('@/session/SessionProvider',()=>({useSession:()=>({session:{opaqueCredential:'credential'}})}));
const ids={hold:'66666666-6666-4666-8666-666666666666',slot:'55555555-5555-4555-8555-555555555555',clinic:'22222222-2222-4222-8222-222222222222',location:'33333333-3333-4333-8333-333333333333'};
const booking={holdId:ids.hold,slotId:ids.slot,status:'CONFIRMED',statusCode:'CONFIRMED',canCancel:true,statusTitle:'Запись подтверждена',safeDescription:'Подтверждено',nextActionCode:'VIEW_APPOINTMENT',confirmationMode:'MANUAL',expiresAt:'2026-08-13T12:00:00.000Z',serverNow:'2026-08-13T11:00:00.000Z',aggregateVersion:2,lastUpdatedAt:'2026-08-13T11:00:00.000Z',pet:{id:'11111111-1111-4111-8111-111111111111',name:'Барсик',species:'CAT'},clinic:{id:ids.clinic,name:'Клиника'},location:{id:ids.location,address:'Москва'},service:{id:'44444444-4444-4444-8444-444444444444',name:'Осмотр'},doctor:null,slot:{startsAt:'2026-08-14T08:00:00.000Z',endsAt:'2026-08-14T08:30:00.000Z',timezone:'Europe/Moscow'},clinicLocationId:ids.location,startsAt:'2026-08-14T08:00:00.000Z',endsAt:'2026-08-14T08:30:00.000Z'} as const;
const change=(requestType:'CANCEL'|'RESCHEDULE'='CANCEL',status:'OPEN'|'PROCESSING'|'COMPLETED'|'REJECTED'|'CANCELLED'='OPEN')=>({requestId:'77777777-7777-4777-8777-777777777771',requestType,status,bookingHoldId:ids.hold,appointmentId:'77777777-7777-4777-8777-777777777772',clinicId:ids.clinic,locationId:ids.location,slotId:ids.slot,version:1,createdAt:'2026-08-13T11:00:00.000Z',stateChangedAt:'2026-08-13T11:00:00.000Z',updatedAt:'2026-08-13T11:00:00.000Z',terminalAt:['COMPLETED','REJECTED','CANCELLED'].includes(status)?'2026-08-13T11:01:00.000Z':null});

describe('BookingChangeRequestPanel',()=>{
  beforeEach(()=>{mockRead.mockReset().mockRejectedValue(new ApiError('UNEXPECTED_RESPONSE','missing',404));mockCreate.mockReset();Object.defineProperty(globalThis,'crypto',{configurable:true,value:{randomUUID:jest.fn().mockReturnValue('88888888-8888-4888-8888-888888888888')}});});
  it.each([['CANCEL','Запросить отмену','Запрос на отмену: запрос отправлен.'],['RESCHEDULE','Запросить изменение времени','Запрос на изменение времени: запрос отправлен.']] as const)('confirms and submits %s without claiming that booking changed',async(type,label,success)=>{mockCreate.mockResolvedValue(change(type));const view=await render(<BookingChangeRequestPanel booking={booking}/>);await waitFor(()=>expect(view.getByText(label)).toBeTruthy());fireEvent.press(view.getByText(label));await waitFor(()=>expect(view.getByText(/Запись и время пока останутся без изменений/)).toBeTruthy());fireEvent.press(view.getByText('Отправить запрос'));await waitFor(()=>expect(view.getByText(success)).toBeTruthy());expect(view.queryByText('Запись отменена')).toBeNull();expect(mockCreate.mock.calls[0].slice(0,3)).toEqual(['credential',ids.hold,type]);await view.unmount();});
  it.each([['OPEN','Запрос отправлен'],['PROCESSING','Запрос обрабатывается'],['COMPLETED','Изменение выполнено'],['REJECTED','Изменение не удалось выполнить'],['CANCELLED','Запрос отменён']] as const)('shows authoritative %s copy after reload',async(status,copy)=>{mockRead.mockResolvedValue(change('RESCHEDULE',status));const view=await render(<BookingChangeRequestPanel booking={booking}/>);await waitFor(()=>expect(view.getAllByText(new RegExp(copy,'i')).length).toBeGreaterThan(0));await view.unmount();});
  it('keeps the idempotency key and controlled copy across 425 retry',async()=>{mockCreate.mockRejectedValueOnce(new ApiError('UNEXPECTED_RESPONSE','raw',425,undefined,'IDEMPOTENCY_IN_PROGRESS')).mockResolvedValueOnce(change());const view=await render(<BookingChangeRequestPanel booking={booking}/>);await waitFor(()=>expect(view.getByText('Запросить отмену')).toBeTruthy());fireEvent.press(view.getByText('Запросить отмену'));await waitFor(()=>expect(view.getByText('Отправить запрос')).toBeTruthy());fireEvent.press(view.getByText('Отправить запрос'));await waitFor(()=>expect(view.getByText(/Запрос ещё отправляется/)).toBeTruthy());fireEvent.press(view.getByText('Проверить снова'));await waitFor(()=>expect(view.getByText('Запрос на отмену: запрос отправлен.')).toBeTruthy());expect(mockCreate).toHaveBeenCalledTimes(2);expect(mockCreate.mock.calls[1][3]).toBe(mockCreate.mock.calls[0][3]);expect(view.queryByText('IDEMPOTENCY_IN_PROGRESS')).toBeNull();await view.unmount();});
  it('reads back an existing active request after a create conflict',async()=>{mockRead.mockRejectedValueOnce(new ApiError('UNEXPECTED_RESPONSE','missing',404)).mockResolvedValueOnce(change('RESCHEDULE','PROCESSING'));mockCreate.mockRejectedValueOnce(new ApiError('CONFLICT','active',409,undefined,'BOOKING_CHANGE_REQUEST_ACTIVE_CONFLICT'));const view=await render(<BookingChangeRequestPanel booking={booking}/>);await waitFor(()=>expect(view.getByText('Запросить изменение времени')).toBeTruthy());fireEvent.press(view.getByText('Запросить изменение времени'));await waitFor(()=>expect(view.getByText('Отправить запрос')).toBeTruthy());fireEvent.press(view.getByText('Отправить запрос'));await waitFor(()=>expect(view.getByText('Запрос на изменение времени: запрос обрабатывается.')).toBeTruthy());expect(view.queryByText('BOOKING_CHANGE_REQUEST_ACTIVE_CONFLICT')).toBeNull();await view.unmount();});
  it('retries a failed initial read and then shows server authority',async()=>{mockRead.mockRejectedValueOnce(new ApiError('NETWORK','offline')).mockResolvedValueOnce(change());const view=await render(<BookingChangeRequestPanel booking={booking}/>);await waitFor(()=>expect(view.getByText(/Нет связи с сервером/)).toBeTruthy());fireEvent.press(view.getByText('Повторить'));await waitFor(()=>expect(view.getByText('Запрос на отмену: запрос отправлен.')).toBeTruthy());expect(mockRead).toHaveBeenCalledTimes(2);await view.unmount();});
  it('fails closed on mismatched booking identity and exposes no internal data',async()=>{mockRead.mockResolvedValue({...change(),clinicId:'99999999-9999-4999-8999-999999999999',ownerId:'internal'});const view=await render(<BookingChangeRequestPanel booking={booking}/>);await waitFor(()=>expect(view.getByText(/Данные записи или запроса изменились/)).toBeTruthy());expect(view.queryByText('internal')).toBeNull();expect(view.queryByText('99999999-9999-4999-8999-999999999999')).toBeNull();await view.unmount();});
  it('single-flights a double confirmation tap',async()=>{mockCreate.mockReturnValue(new Promise(()=>undefined));const view=await render(<BookingChangeRequestPanel booking={booking}/>);await waitFor(()=>expect(view.getByText('Запросить отмену')).toBeTruthy());fireEvent.press(view.getByText('Запросить отмену'));await waitFor(()=>expect(view.getByText('Отправить запрос')).toBeTruthy());const confirm=view.getByText('Отправить запрос');fireEvent.press(confirm);fireEvent.press(confirm);expect(mockCreate).toHaveBeenCalledTimes(1);await view.unmount();});
});
