import { act, fireEvent, render, waitFor } from '@testing-library/react-native';
import { ApiError } from '@/api/errors';
import { BookingStatusScreen } from './BookingStatusScreen';

const mockRead=jest.fn();
let mockSession: { cacheScope: string; opaqueCredential: string } | null = { cacheScope:'11111111-1111-4111-8111-111111111111', opaqueCredential:'credential-a' };
jest.mock('./booking-api',()=>({bookingApi:{read:(...args:unknown[])=>mockRead(...args)}}));
jest.mock('./BookingChangeRequestPanel',()=>{const React=jest.requireActual('react');const{Text}=jest.requireActual('react-native');return{BookingChangeRequestPanel:()=>React.createElement(Text,null,'change-request-panel')};});
jest.mock('@/session/SessionProvider',()=>({useSession:()=>({session:mockSession})}));
const ids={petId:'11111111-1111-4111-8111-111111111111',clinicId:'22222222-2222-4222-8222-222222222222',locationId:'33333333-3333-4333-8333-333333333333',serviceId:'44444444-4444-4444-8444-444444444444',slotId:'55555555-5555-4555-8555-555555555555',holdId:'66666666-6666-4666-8666-666666666666'};
const base={holdId:ids.holdId,slotId:ids.slotId,status:'PENDING_CONFIRMATION',statusCode:'PENDING_CONFIRMATION',canCancel:true,statusTitle:'Клиника подтверждает заявку',safeDescription:'Ожидаем подтверждение.',nextActionCode:'WAIT',confirmationMode:'MANUAL',expiresAt:'2026-08-13T11:15:00.000Z',serverNow:'2026-08-13T11:00:00.000Z',aggregateVersion:1,lastUpdatedAt:'2026-08-13T11:00:00.000Z',pet:{id:ids.petId,name:'Барсик',species:'CAT'},clinic:{id:ids.clinicId,name:'Добрый доктор'},location:{id:ids.locationId,address:'Москва, ул. Ветеринарная, 1'},service:{id:ids.serviceId,name:'Осмотр'},doctor:null,slot:{startsAt:'2026-08-14T08:00:00.000Z',endsAt:'2026-08-14T08:30:00.000Z',timezone:'Europe/Moscow'},clinicLocationId:ids.locationId,startsAt:'2026-08-14T08:00:00.000Z',endsAt:'2026-08-14T08:30:00.000Z'} as const;
const confirmed={...base,status:'CONFIRMED',statusCode:'CONFIRMED',statusTitle:'Запись подтверждена',safeDescription:'Клиника подтвердила выбранное время.',nextActionCode:'VIEW_APPOINTMENT',aggregateVersion:2,lastUpdatedAt:'2026-08-13T11:01:00.000Z'} as const;
const rejected={...base,status:'REJECTED',statusCode:'REJECTED',canCancel:false,statusTitle:'Клиника не смогла подтвердить это время',safeDescription:'Выберите другое доступное время.',nextActionCode:'CHOOSE_ANOTHER_SLOT',aggregateVersion:2,lastUpdatedAt:'2026-08-13T11:01:00.000Z'} as const;
const expired={...base,status:'EXPIRED',statusCode:'EXPIRED',canCancel:false,statusTitle:'Клиника не успела подтвердить запись',safeDescription:'Это время больше не удерживается. Выберите другое доступное время.',nextActionCode:'CHOOSE_ANOTHER_SLOT',aggregateVersion:2,lastUpdatedAt:'2026-08-13T11:15:00.000Z',serverNow:'2026-08-13T11:15:00.000Z'} as const;
const props={holdId:ids.holdId,authorityGeneration:'g1',onClose:jest.fn()};

describe('BookingStatusScreen',()=>{
  beforeEach(()=>{mockRead.mockReset();mockSession={cacheScope:'11111111-1111-4111-8111-111111111111',opaqueCredential:'credential-a'};props.onClose.mockReset();});
  afterEach(()=>{jest.useRealTimers();});
  it('repeats bounded authoritative polling from pending into confirmed without a local final state',async()=>{jest.useFakeTimers();mockRead.mockResolvedValueOnce(base).mockResolvedValueOnce(base).mockResolvedValueOnce(confirmed);const view=await render(<BookingStatusScreen {...props}/>);await act(async()=>{});expect(view.getByText('Клиника подтверждает запись')).toBeTruthy();await act(async()=>{await jest.advanceTimersByTimeAsync(15_000);});expect(view.getByText('Клиника подтверждает запись')).toBeTruthy();await act(async()=>{await jest.advanceTimersByTimeAsync(15_000);});expect(view.getByText('Запись подтверждена')).toBeTruthy();expect(view.getByText('Клиника')).toBeTruthy();expect(view.getByText('Добрый доктор')).toBeTruthy();expect(mockRead).toHaveBeenCalledTimes(3);view.unmount();},15_000);
  it('refreshes pending into rejected and never displays the internal enum',async()=>{mockRead.mockResolvedValueOnce(base).mockResolvedValueOnce(rejected);const view=await render(<BookingStatusScreen {...props}/>);await waitFor(()=>expect(view.getByText('Клиника подтверждает запись')).toBeTruthy());fireEvent.press(view.getByText('Обновить статус'));await waitFor(()=>expect(view.getByText('Клиника не сможет принять в выбранное время')).toBeTruthy());expect(view.queryByText('MANUAL_CONFIRM_PENDING')).toBeNull();});
  it('shows the authoritative 15-minute deadline and server-calibrated countdown',async()=>{mockRead.mockResolvedValue(base);const view=await render(<BookingStatusScreen {...props}/>);await waitFor(()=>expect(view.getByText(/Клиника сможет подтвердить запись до/)).toBeTruthy());expect(view.getByText('Осталось 15:00')).toBeTruthy();expect(view.queryByText(/оплат/i)).toBeNull();});
  it('does not fabricate EXPIRED or retain pending actions when the presentation countdown reaches zero',async()=>{jest.useFakeTimers();const near={...base,serverNow:'2026-08-13T11:14:59.000Z'};mockRead.mockResolvedValueOnce(near).mockImplementation(()=>new Promise(()=>{}));const view=await render(<BookingStatusScreen {...props}/>);await act(async()=>{});expect(view.getByText('Осталось 00:01')).toBeTruthy();await act(async()=>{await jest.advanceTimersByTimeAsync(1_000);});expect(view.getByText('Проверяем актуальный статус…')).toBeTruthy();expect(view.queryByText('Клиника не успела подтвердить запись')).toBeNull();expect(view.queryByText('Отменить запись')).toBeNull();expect(mockRead).toHaveBeenCalledTimes(2);view.unmount();});
  it('renders EXPIRED only after authoritative readback',async()=>{mockRead.mockResolvedValueOnce(base).mockResolvedValueOnce(expired);const view=await render(<BookingStatusScreen {...props}/>);await waitFor(()=>expect(view.getByText('Клиника подтверждает запись')).toBeTruthy());fireEvent.press(view.getByText('Обновить статус'));await waitFor(()=>expect(view.getByText('Клиника не успела подтвердить запись')).toBeTruthy());expect(view.getByText('Это время больше не удерживается. Выберите другое доступное время.')).toBeTruthy();});
  it('shows a network retry and replaces it only with authoritative readback',async()=>{mockRead.mockRejectedValueOnce(new ApiError('NETWORK','offline')).mockResolvedValueOnce(confirmed);const view=await render(<BookingStatusScreen {...props}/>);await waitFor(()=>expect(view.getByText('Нет связи с сервером. Проверьте подключение и повторите.')).toBeTruthy());expect(view.queryByText('Запись подтверждена')).toBeNull();fireEvent.press(view.getByText('Повторить'));await waitFor(()=>expect(view.getByText('Запись подтверждена')).toBeTruthy());});
  it('fails closed with an explicit session-ended state without issuing a status read',async()=>{mockSession=null;const view=await render(<BookingStatusScreen {...props}/>);expect(view.getByText('Сессия завершена')).toBeTruthy();expect(view.getByText('Войдите снова, чтобы получить актуальный статус заявки.')).toBeTruthy();expect(mockRead).not.toHaveBeenCalled();});
  it('fails malformed initial payload closed and retains a last valid snapshot on malformed refresh',async()=>{mockRead.mockRejectedValueOnce(new Error('INVALID_BOOKING_SNAPSHOT')).mockResolvedValueOnce(base).mockRejectedValueOnce(new Error('INVALID_BOOKING_SNAPSHOT'));const view=await render(<BookingStatusScreen {...props}/>);await waitFor(()=>expect(view.getByText('Не удалось безопасно прочитать статус заявки.')).toBeTruthy());fireEvent.press(view.getByText('Повторить'));await waitFor(()=>expect(view.getByText('Клиника подтверждает запись')).toBeTruthy());fireEvent.press(view.getByText('Обновить статус'));await waitFor(()=>expect(view.getByText('Сервер вернул неизвестный формат. Показаны последние проверенные данные.')).toBeTruthy());expect(view.getByText('Клиника подтверждает запись')).toBeTruthy();});
  it('re-entry fetches and renders the same authoritative terminal result',async()=>{mockRead.mockResolvedValue(confirmed);const first=await render(<BookingStatusScreen {...props}/>);await waitFor(()=>expect(first.getByText('Запись подтверждена')).toBeTruthy());await first.unmount();const second=await render(<BookingStatusScreen {...props}/>);await waitFor(()=>expect(second.getByText('Запись подтверждена')).toBeTruthy());expect(mockRead).toHaveBeenCalledTimes(2);});
  it('routes a confirmed booking to the additive change-request panel',async()=>{mockRead.mockResolvedValue(confirmed);const view=await render(<BookingStatusScreen {...props}/>);await waitFor(()=>expect(view.getByText('change-request-panel')).toBeTruthy());});
});
