import {fireEvent,render,waitFor} from '@testing-library/react-native';
import {ApiError} from '@/api/errors';
import {ReallocationOfferPanel} from './ReallocationOfferPanel';
const mockOpen=jest.fn(),mockRead=jest.fn(),mockAccept=jest.fn();
jest.mock('./booking-api',()=>({...jest.requireActual('./booking-api'),bookingApi:{openReallocationCase:(...args:unknown[])=>mockOpen(...args),readReallocationCase:(...args:unknown[])=>mockRead(...args),acceptReallocationOffer:(...args:unknown[])=>mockAccept(...args)}}));
jest.mock('@/session/SessionProvider',()=>({useSession:()=>({session:{opaqueCredential:'credential'}})}));
const ids={hold:'66666666-6666-4666-8666-666666666666',request:'77777777-7777-4777-8777-777777777771',case:'88888888-8888-4888-8888-888888888881',offer:'99999999-9999-4999-8999-999999999991',clinic:'22222222-2222-4222-8222-222222222222',location:'33333333-3333-4333-8333-333333333333',doctor:'44444444-4444-4444-8444-444444444441',service:'44444444-4444-4444-8444-444444444442',slot:'55555555-5555-4555-8555-555555555555'};
const booking={holdId:ids.hold,slotId:'55555555-5555-4555-8555-555555555551',status:'CONFIRMED',statusCode:'CONFIRMED',canCancel:true,statusTitle:'Запись подтверждена',safeDescription:'Подтверждено',nextActionCode:'VIEW_APPOINTMENT',confirmationMode:'MANUAL',expiresAt:'2026-09-01T10:00:00.000Z',serverNow:'2026-09-01T09:00:00.000Z',aggregateVersion:2,lastUpdatedAt:'2026-09-01T09:00:00.000Z',pet:{id:'11111111-1111-4111-8111-111111111111',name:'Барсик',species:'CAT'},clinic:{id:'22222222-2222-4222-8222-222222222221',name:'Текущая клиника'},location:{id:'33333333-3333-4333-8333-333333333331',address:'Москва'},service:{id:ids.service,name:'Осмотр'},doctor:null,slot:{startsAt:'2026-09-02T08:00:00.000Z',endsAt:'2026-09-02T08:30:00.000Z',timezone:'Europe/Moscow'},clinicLocationId:'33333333-3333-4333-8333-333333333331',startsAt:'2026-09-02T08:00:00.000Z',endsAt:'2026-09-02T08:30:00.000Z'} as const;
const request={requestId:ids.request,requestType:'RESCHEDULE',status:'PROCESSING',bookingHoldId:ids.hold,appointmentId:'77777777-7777-4777-8777-777777777772',clinicId:booking.clinic.id,locationId:booking.location.id,slotId:booking.slotId,version:1,createdAt:booking.serverNow,stateChangedAt:booking.serverNow,updatedAt:booking.serverNow,terminalAt:null} as const;
const offer=(override:Record<string,unknown>={})=>({offerId:ids.offer,version:3,rank:1,clinicId:ids.clinic,clinicName:'Новая клиника',locationId:ids.location,locationAddress:'Тверская, 1',timezone:'Europe/Moscow',doctorId:ids.doctor,doctorName:'Анна Вет',serviceId:ids.service,serviceName:'Осмотр',slotId:ids.slot,slotVersion:7,startsAt:'2026-09-03T08:00:00.000Z',endsAt:'2026-09-03T08:30:00.000Z',distanceMeters:1250,priceAmount:900,priceCurrency:'RUB',status:'OFFERED',expiresAt:'2026-09-01T09:15:00.000Z',...override});
const reallocation=(offers:ReturnType<typeof offer>[]= [offer()],override:Record<string,unknown>={})=>({caseId:ids.case,bookingChangeRequestId:ids.request,bookingHoldId:ids.hold,status:'OPEN',eligibility:'ACTIVE',version:2,serverNow:'2026-09-01T09:00:00.000Z',createdAt:'2026-09-01T09:00:00.000Z',acceptedOfferId:null,replacementBooking:null,offers,...override});
describe('Owner Smart Reallocation offers',()=>{
  beforeEach(()=>{mockOpen.mockReset();mockRead.mockReset();mockAccept.mockReset();Object.defineProperty(globalThis,'crypto',{configurable:true,value:{randomUUID:jest.fn().mockReturnValue('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa')}});});
  it('shows authoritative replacement time and clinic after confirmed cutover',async()=>{const closed=reallocation([offer({status:'ACCEPTED'})],{status:'CLOSED',eligibility:'BOOKING_INELIGIBLE',acceptedOfferId:ids.offer,replacementBooking:{holdId:'66666666-6666-4666-8666-666666666667',status:'CONFIRMED',confirmationMode:'MANUAL',slotId:ids.slot,aggregateVersion:2,expiresAt:'2026-09-01T09:20:00.000Z'}});mockOpen.mockResolvedValue(closed);const view=await render(<ReallocationOfferPanel booking={booking} request={request}/>);fireEvent.press(view.getByText('Показать варианты'));await waitFor(()=>expect(view.getByText('Новое время подтверждено')).toBeTruthy());expect(view.getByText(/Новая клиника/)).toBeTruthy();});
  it('keeps backend order and hands off every authoritative identity without reserving anything',async()=>{
    const second=offer({offerId:'99999999-9999-4999-8999-999999999992',rank:2,clinicName:'Вторая клиника',slotId:'55555555-5555-4555-8555-555555555556',slotVersion:8});mockOpen.mockResolvedValue(reallocation([offer(),second]));const selected=jest.fn();const view=await render(<ReallocationOfferPanel booking={booking} request={request} onSelectionChange={selected}/>);
    fireEvent.press(view.getByText('Показать варианты'));await waitFor(()=>expect(view.getByText('Новая клиника')).toBeTruthy());expect(view.getAllByText(/клиника$/i).map(node=>node.props.children)).toEqual(['Новая клиника','Вторая клиника']);const first=view.getByLabelText(/Новая клиника/);fireEvent.press(first);await waitFor(()=>expect(first.props.accessibilityState.selected).toBe(true));fireEvent.press(view.getByText('Продолжить с этим вариантом'));
    expect(selected).toHaveBeenCalledWith({reallocationCaseId:ids.case,caseVersion:2,offerId:ids.offer,offerVersion:3,bookingHoldId:ids.hold,clinicId:ids.clinic,locationId:ids.location,doctorId:ids.doctor,serviceId:ids.service,slotId:ids.slot,slotVersion:7,expiresAt:'2026-09-01T09:15:00.000Z'});await waitFor(()=>expect(view.getByText('Создать запрос на новое время?')).toBeTruthy());expect(mockOpen).toHaveBeenCalledTimes(1);
  });
  it('renders missing optional facts safely and blocks expired or stale offers',async()=>{
    mockOpen.mockResolvedValue(reallocation([offer({priceAmount:null,priceCurrency:null,distanceMeters:null,doctorName:null,status:'EXPIRED'}),offer({offerId:'99999999-9999-4999-8999-999999999992',rank:2,status:'INVALIDATED',clinicName:'Старая клиника',priceAmount:null,priceCurrency:null,distanceMeters:null})]));const view=await render(<ReallocationOfferPanel booking={booking} request={request}/>);
    fireEvent.press(view.getByText('Показать варианты'));await waitFor(()=>expect(view.getByText('Срок варианта истёк')).toBeTruthy());expect(view.getByText('Вариант больше недоступен')).toBeTruthy();expect(view.queryByText(/Ориентировочная стоимость/)).toBeNull();expect(view.getByText('Продолжить с этим вариантом').parent?.props.accessibilityState.disabled).toBe(true);
  });
  it('covers empty, Booking-ineligible and retry states without changing Booking A copy',async()=>{
    mockOpen.mockRejectedValueOnce(new ApiError('NETWORK','offline')).mockResolvedValueOnce(reallocation([]));const view=await render(<ReallocationOfferPanel booking={booking} request={request}/>);fireEvent.press(view.getByText('Показать варианты'));await waitFor(()=>expect(view.getByText('Не удалось обновить варианты')).toBeTruthy());fireEvent.press(view.getByText('Повторить'));await waitFor(()=>expect(view.getByText('Подходящих вариантов пока нет')).toBeTruthy());expect(view.getByText('Ваша текущая запись сохранена')).toBeTruthy();mockRead.mockResolvedValue(reallocation([], {eligibility:'BOOKING_INELIGIBLE'}));fireEvent.press(view.getByText('Обновить варианты'));await waitFor(()=>expect(view.getByText('Для этой записи варианты больше недоступны')).toBeTruthy());
  });
  it('clears a local choice when authoritative refresh marks the active offer expired',async()=>{
    mockOpen.mockResolvedValue(reallocation());mockRead.mockResolvedValue(reallocation([offer({status:'EXPIRED'})]));const selected=jest.fn();const view=await render(<ReallocationOfferPanel booking={booking} request={request} onSelectionChange={selected}/>);fireEvent.press(view.getByText('Показать варианты'));await waitFor(()=>expect(view.getByText('Новая клиника')).toBeTruthy());fireEvent.press(view.getByLabelText(/Новая клиника/));await waitFor(()=>expect(view.getByText('Продолжить с этим вариантом').parent?.props.accessibilityState.disabled).toBe(false));fireEvent.press(view.getByText('Обновить варианты'));await waitFor(()=>expect(view.getByText('Срок варианта истёк')).toBeTruthy());expect(view.getByText('Продолжить с этим вариантом').parent?.props.accessibilityState.disabled).toBe(true);expect(selected).not.toHaveBeenCalled();
  });
  it('creates one pending-confirmation replacement request while explicitly preserving Booking A',async()=>{
    const pending=reallocation([offer({status:'ACCEPTED',version:4})],{status:'REPLACEMENT_PENDING_CONFIRMATION',eligibility:'BOOKING_INELIGIBLE',version:3,acceptedOfferId:ids.offer,replacementBooking:{holdId:'66666666-6666-4666-8666-666666666667',status:'PENDING_CONFIRMATION',confirmationMode:'MANUAL',slotId:ids.slot,aggregateVersion:1,expiresAt:'2026-09-01T09:20:00.000Z'}});mockOpen.mockResolvedValue(reallocation());mockAccept.mockResolvedValue(pending);const view=await render(<ReallocationOfferPanel booking={booking} request={request}/>);fireEvent.press(view.getByText('Показать варианты'));await waitFor(()=>expect(view.getByText('Новая клиника')).toBeTruthy());fireEvent.press(view.getByLabelText(/Новая клиника/));await waitFor(()=>expect(view.getByText('Продолжить с этим вариантом').parent?.props.accessibilityState.disabled).toBe(false));fireEvent.press(view.getByText('Продолжить с этим вариантом'));await waitFor(()=>expect(view.getByText('Создать запрос')).toBeTruthy());fireEvent.press(view.getByText('Создать запрос'));await waitFor(()=>expect(view.getByText('Запрос на новое время создан')).toBeTruthy());expect(view.getAllByText('Ваша текущая запись сохранена').length).toBeGreaterThan(0);expect(view.getByText(/Клиника ещё должна подтвердить/)).toBeTruthy();expect(mockAccept).toHaveBeenCalledTimes(1);
  });
  it('recovers a response-loss acceptance from authoritative readback without a second command',async()=>{
    const pending=reallocation([offer({status:'ACCEPTED',version:4})],{status:'REPLACEMENT_PENDING_CONFIRMATION',eligibility:'BOOKING_INELIGIBLE',version:3,acceptedOfferId:ids.offer,replacementBooking:{holdId:'66666666-6666-4666-8666-666666666667',status:'PENDING_CONFIRMATION',confirmationMode:'MANUAL',slotId:ids.slot,aggregateVersion:1,expiresAt:'2026-09-01T09:20:00.000Z'}});mockOpen.mockResolvedValue(reallocation());mockAccept.mockRejectedValue(new ApiError('NETWORK','lost'));mockRead.mockResolvedValue(pending);const view=await render(<ReallocationOfferPanel booking={booking} request={request}/>);fireEvent.press(view.getByText('Показать варианты'));await waitFor(()=>expect(view.getByText('Новая клиника')).toBeTruthy());fireEvent.press(view.getByLabelText(/Новая клиника/));await waitFor(()=>expect(view.getByText('Продолжить с этим вариантом').parent?.props.accessibilityState.disabled).toBe(false));fireEvent.press(view.getByText('Продолжить с этим вариантом'));await waitFor(()=>expect(view.getByText('Создать запрос')).toBeTruthy());fireEvent.press(view.getByText('Создать запрос'));await waitFor(()=>expect(view.getByText('Запрос на новое время создан')).toBeTruthy());expect(mockAccept).toHaveBeenCalledTimes(1);expect(mockRead).toHaveBeenCalledWith('credential',ids.case);
  });
});
