import { fireEvent, render } from '@testing-library/react-native';
import { OwnerHome } from '@/app/(app)';
import type { OwnerHomeSnapshot } from '@/home/owner-home-api';

const PET={id:'22222222-2222-4222-8222-222222222222',name:'Барни',species:'DOG' as const,breed:null,photoUrl:null};
const SNAPSHOT:OwnerHomeSnapshot={schemaVersion:1,serverNow:'2026-09-10T08:00:00.000Z',pets:[PET],selectedPet:PET,selectionSource:'DEFAULT',nextAction:{type:'START_PLANNED_CARE',priority:'LOW',sourceType:'PET',sourceId:PET.id,title:'Спланируйте заботу о питомце',description:'Выберите клинику или услугу в каталоге VetHelp.',deadlineAt:null,actionCode:'OPEN_CATALOG'},activeCare:null};

it('renders the V50 Home composition and keeps authoritative workflow actions', async () => {
  const onBook=jest.fn(),onClinics=jest.fn(),onPets=jest.fn(),onFindTime=jest.fn(),onDiary=jest.fn(),onLogout=jest.fn();
  const view=await render(<OwnerHome onBook={onBook} onClinics={onClinics} onPets={onPets} onFindTime={onFindTime} onDiary={onDiary} onLogout={onLogout} snapshot={SNAPSHOT} onHomeAction={()=>undefined}/>);
  expect(view.getByLabelText('Основная навигация')).toBeTruthy();
  expect(view.getByRole('header',{name:'Здравствуйте!'})).toBeTruthy();
  expect(view.queryByText(/Доброе утро/)).toBeNull();
  expect(view.getByText('Что нужно Барни сейчас?')).toBeTruthy();
  expect(view.getByText('Польза сразу')).toBeTruthy();
  expect(view.getByText('Сравните варианты для Барни без звонка')).toBeTruthy();
  expect(view.getByText('Выбрать клинику')).toBeTruthy();
  expect(view.getByText('Найти время')).toBeTruthy();
  expect(view.getByText('Следующий шаг')).toBeTruthy();
  expect(view.getAllByText('Барни').length).toBeGreaterThan(0);
  expect(view.queryByText('Ближайших записей пока нет')).toBeNull();
  expect(view.getByText('Спланируйте заботу о питомце')).toBeTruthy();
  expect(view.getByText('Плановый шаг')).toBeTruthy();
  expect(view.queryByText(/Home пока/)).toBeNull();
  expect(view.queryByText(/подтверждённый профиль/)).toBeNull();
  expect(view.queryByText(/API|backend|authoritative|V50 референс/)).toBeNull();
  fireEvent.press(view.getAllByText('Записаться')[0]);
  fireEvent.press(view.getAllByText('Выбрать клинику')[0]);
  fireEvent.press(view.getAllByText('Найти время')[0]);
  fireEvent.press(view.getByRole('button', { name: /Питомцы/ }));
  fireEvent.press(view.getAllByText('Дневник')[0]);
  fireEvent.press(view.getByText('Выйти'));
  expect(onBook).toHaveBeenCalledTimes(1);
  expect(onPets).toHaveBeenCalledTimes(1);
  expect(onClinics).toHaveBeenCalledTimes(1);
  expect(onFindTime).toHaveBeenCalledTimes(1);
  expect(onDiary).toHaveBeenCalledTimes(1);
  expect(onLogout).toHaveBeenCalledTimes(1);
  const confirmed={...SNAPSHOT,nextAction:{...SNAPSHOT.nextAction,type:'UPCOMING_CONFIRMED_VISIT' as const,sourceType:'BOOKING_HOLD' as const,sourceId:'33333333-3333-4333-8333-333333333333',title:'Ближайший визит подтверждён',description:'12 сентября, 11:00',deadlineAt:'2026-09-12T08:00:00.000Z',actionCode:'OPEN_APPOINTMENT' as const},activeCare:{sourceType:'BOOKING_HOLD' as const,sourceId:'33333333-3333-4333-8333-333333333333',statusCode:'CONFIRMED' as const,title:'Добрый ветеринар',description:'Запись подтверждена',startsAt:'2026-09-12T08:00:00.000Z',deadlineAt:'2026-09-12T08:00:00.000Z',clinicName:'Добрый ветеринар',petId:PET.id,actionCode:'OPEN_APPOINTMENT' as const}};
  await view.rerender(<OwnerHome onBook={onBook} onClinics={onClinics} onPets={onPets} onFindTime={onFindTime} onDiary={onDiary} onLogout={onLogout} snapshot={confirmed}/>);
  expect(view.getByText('Ближайший визит подтверждён')).toBeTruthy();
  expect(view.getByText('Добрый ветеринар')).toBeTruthy();
  expect(view.queryByText('Нужна новая запись?')).toBeNull();
  await view.unmount();
});
