const { expect, test } = require('@playwright/test');
const AxeBuilder = require('@axe-core/playwright').default;
const { createHash } = require('node:crypto');
const { execFileSync } = require('node:child_process');
const { mkdirSync, readFileSync, writeFileSync } = require('node:fs');
const { resolve } = require('node:path');
const { PNG } = require('pngjs');
const backend=(process.env.VETHELP_API_BASE_URL??'http://127.0.0.1:3000').replace(/\/$/,'');
const reference=`http://127.0.0.1:${Number(process.env.OWNER_V50_REFERENCE_PORT??8093)}/index.html`;
const evidence=resolve(process.cwd(),'../../docs/testing/evidence/owner-v50-r4');
const shots=[{width:390,height:844},{width:1440,height:900}], layouts=[...shots,{width:768,height:1024},{width:1024,height:900}];

test('R4 real-stack Owner journeys and canonical/current evidence',async({page,request,context})=>{
 test.setTimeout(300000);await expect(request.get(`${backend}/v1/health`).then(r=>r.json())).resolves.toMatchObject({status:'ok'});mkdirSync(evidence,{recursive:true});
 const root=resolve(process.cwd(),'../..'), meta={generatedAt:new Date().toISOString(),head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8',cwd:root}).trim(),dirty:execFileSync('git',['status','--short'],{encoding:'utf8',cwd:root}).trim().split('\n').filter(Boolean),fixture:{ownerPhone:'+79991234567',pet:'Demo Pet',clinic:'VetHelp Pilot',source:'real local BFF/backend seeds'},records:[],structural:[],perceptual:[],navigation:[],accessibility:[]};
 const ref=await context.newPage();
 const record=async(state,anchor,route,refAnchor)=>{for(const viewport of layouts){await page.setViewportSize(viewport);await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const box=await anchor.boundingBox();expect(box).not.toBeNull();meta.structural.push({state,source:'current',...viewport,anchor:box,horizontalOverflow:false});}const axe=await new AxeBuilder({page}).analyze();const severe=axe.violations.filter(v=>v.impact==='serious'||v.impact==='critical');expect(severe).toEqual([]);meta.accessibility.push({state,severeViolations:0});for(const viewport of shots){await page.setViewportSize(viewport);const currentFile=`current-${state}-${viewport.width}x${viewport.height}.png`;await page.screenshot({path:resolve(evidence,currentFile),animations:'disabled'});await ref.setViewportSize(viewport);await ref.goto(`${reference}#${route}`);await ref.waitForTimeout(150);if(refAnchor)await ref.locator(refAnchor).first().scrollIntoViewIfNeeded();await expect.poll(()=>ref.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const canonicalFile=`canonical-${state}-${viewport.width}x${viewport.height}.png`;await ref.screenshot({path:resolve(evidence,canonicalFile),animations:'disabled'});meta.records.push({state,viewport,route:page.url(),canonicalRoute:`#${route}`,currentFile,currentSha:sha(currentFile),canonicalFile,canonicalSha:sha(canonicalFile),horizontalOverflow:false});meta.perceptual.push(diff(state,viewport,currentFile,canonicalFile));}};
 await authenticate(page);await record('home',page.getByRole('heading',{name:/Доброе/}),'home');expect(await page.getByText('Ближайших записей пока нет').count()).toBe(0);
 await page.getByRole('button',{name:/Записаться/}).first().click();await expect(page.getByRole('heading',{name:'Кого записываем?'})).toBeVisible();await record('pet-booking',page.getByRole('heading',{name:'Кого записываем?'}),'pets');await selectPet(page);
 await record('catalog',page.getByRole('heading',{name:'Выберите клинику'}),'catalog');await page.getByRole('button',{name:'Открыть клинику'}).first().click();await record('clinic-detail',page.getByRole('heading',{name:'VetHelp Pilot'}).first(),'clinic');await page.getByRole('button',{name:'Выбрать услугу'}).click();await record('service',page.getByRole('heading',{name:'Что нужно питомцу?'}),'clinic','.service-grid');await chooseService(page);
 await record('availability',page.getByRole('heading',{name:'Выберите время'}),'booking');await chooseSlot(page);await record('review',page.getByRole('heading',{name:'Проверьте заявку'}),'booking-review');await keyboardReach(page,page.getByRole('button',{name:'Отправить заявку'}));const created=page.waitForResponse(r=>r.url().endsWith('/api/owner/v1/booking-holds')&&r.request().method()==='POST');await page.getByRole('button',{name:'Отправить заявку'}).click();expect((await created).ok()).toBe(true);await expect(page).toHaveURL(/\/booking\/[0-9a-f-]{36}$/i);await expect(page.getByText('Клиника подтверждает запись')).toBeVisible();await record('pending',page.getByRole('heading',{name:'Клиника подтверждает запись'}),'appointment-detail');meta.navigation.push({journey:'Booking',result:'PASS',semantics:'pet → catalog → clinic detail → service → availability → review → pending'});const pending=page.url();await page.goBack();await expect(page).not.toHaveURL(pending);await page.goto('/');await closeStatus(page);
 await page.getByRole('button',{name:'Выбрать клинику'}).click();await expect(page.getByRole('heading',{name:'Клиники VetHelp'})).toBeVisible();await page.getByRole('button',{name:'Открыть клинику'}).first().click();await expect(page.getByRole('heading',{name:'VetHelp Pilot'}).first()).toBeVisible();await page.getByRole('button',{name:'Назад'}).first().click();await expect(page.getByRole('heading',{name:'Клиники VetHelp'})).toBeVisible();meta.navigation.push({journey:'Clinics',result:'PASS',semantics:'catalog → clinic detail → back'});await page.getByRole('button',{name:'Назад'}).first().click();
 await page.getByRole('button',{name:'Найти время'}).click();await selectPet(page);await page.getByRole('button',{name:'Открыть клинику'}).first().click();await page.getByRole('button',{name:'Выбрать услугу'}).click();await chooseService(page);await expect(page.getByRole('heading',{name:'Выберите время'})).toBeVisible();meta.navigation.push({journey:'Time',result:'PASS',semantics:'pet → catalog → clinic detail → service → availability'});for(let i=0;i<4;i++)await page.getByRole('button',{name:'Назад'}).first().click();await expect(page.getByRole('heading',{name:/Доброе/})).toBeVisible();
 await page.getByRole('button',{name:/Дневник/}).first().click();await record('pet-diary',page.getByRole('heading',{name:'Чей дневник открыть?'}),'pets');await selectPet(page);await record('diary',page.getByRole('heading',{name:/Дневник:/}),'diary');meta.navigation.push({journey:'Diary',result:'PASS',semantics:'pet → authoritative diary'});writeFileSync(resolve(evidence,'manifest.json'),`${JSON.stringify(meta,null,2)}\n`);
});
async function authenticate(page){await page.setViewportSize({width:390,height:844});await page.goto('/?intent=book');await page.getByRole('button',{name:'Начать запись'}).click();await page.getByLabel('Номер телефона').fill('+79991234567');await page.getByRole('button',{name:'Получить код'}).click();await page.getByLabel('Код из сообщения').fill(process.env.AUTH_DEV_OTP_CODE??'246810');await page.getByRole('button',{name:'Подтвердить'}).click();await expect(page.getByRole('heading',{name:/Доброе/})).toBeVisible();const c=await page.evaluate(async()=>{const r=await fetch('/api/owner/v1/owner/pets');return{status:r.status,body:await r.json()}});expect(c.status).toBe(200);expect(c.body).toEqual(expect.arrayContaining([expect.objectContaining({name:'Demo Pet',species:'DOG'})]));}
async function selectPet(page){const pet=page.getByRole('radio',{name:/Demo Pet/});await expect(pet).toBeVisible();await keyboardReach(page,pet);await pet.click();await page.getByRole('button',{name:'Продолжить',exact:true}).click();}
async function chooseService(page){const service=page.getByRole('radio').first();await keyboardReach(page,service);await service.click();await page.getByRole('button',{name:'Продолжить',exact:true}).click();}
async function chooseSlot(page){const date=page.getByRole('tab').first();await keyboardReach(page,date);await date.click();const slot=page.getByRole('radio').first();await keyboardReach(page,slot);await slot.click();await page.getByRole('button',{name:'Продолжить',exact:true}).click();}
async function closeStatus(page){if(await page.getByRole('heading',{name:'Статус заявки'}).isVisible().catch(()=>false))await page.getByRole('button',{name:'Назад'}).last().click();await expect(page.getByRole('heading',{name:/Доброе/})).toBeVisible();}
async function keyboardReach(page,target){await target.scrollIntoViewIfNeeded();await page.locator('body').click({position:{x:1,y:1}});for(let i=0;i<100;i++){await page.keyboard.press('Tab');if(await target.evaluate(el=>el===document.activeElement).catch(()=>false))return;}throw new Error('Keyboard traversal did not reach required control');}
function sha(file){return createHash('sha256').update(readFileSync(resolve(evidence,file))).digest('hex');}
function diff(state,viewport,currentFile,canonicalFile){const a=PNG.sync.read(readFileSync(resolve(evidence,currentFile))),b=PNG.sync.read(readFileSync(resolve(evidence,canonicalFile))),width=Math.min(a.width,b.width),height=Math.min(a.height,b.height),out=new PNG({width,height});let changed=0;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const ai=(y*a.width+x)*4,bi=(y*b.width+x)*4,oi=(y*width+x)*4,d=Math.abs(a.data[ai]-b.data[bi])+Math.abs(a.data[ai+1]-b.data[bi+1])+Math.abs(a.data[ai+2]-b.data[bi+2]);if(d>60){changed++;out.data[oi]=230;out.data[oi+1]=45;out.data[oi+2]=70;out.data[oi+3]=210}else{out.data[oi]=b.data[bi];out.data[oi+1]=b.data[bi+1];out.data[oi+2]=b.data[bi+2];out.data[oi+3]=70}}const file=`diff-${state}-${viewport.width}x${viewport.height}.png`;writeFileSync(resolve(evidence,file),PNG.sync.write(out));return{state,viewport,file,changedPixels:changed,comparedPixels:width*height,changedRatio:changed/(width*height),classification:'raw perceptual diagnostic; factual regions reviewed separately'};}
