import { HoldState } from './booking.types';

const transitions: Record<HoldState, readonly HoldState[]> = {
  MANUAL_CONFIRM_PENDING: ['ALTERNATIVE_PENDING', 'CONFIRMED', 'EXPIRED', 'RELEASED', 'SLA_BREACHED', 'CANCELLATION_REQUESTED', 'RESCHEDULE_REQUESTED'],
  ALTERNATIVE_PENDING: ['MIS_HELD', 'EXPIRED', 'RELEASED', 'CANCELLATION_REQUESTED'],
  CONFIRMED: ['CANCELLATION_REQUESTED', 'RESCHEDULE_REQUESTED', 'COMPLETED'],
  EXPIRED: [],
  RELEASED: [],
  SLA_BREACHED: [],
  MIS_RESERVATION_PENDING: ['MIS_HELD', 'MIS_RECONCILIATION_PENDING', 'MIS_BOOKING_FAILED', 'RELEASED', 'CANCELLATION_REQUESTED'],
  MIS_RECONCILIATION_PENDING: ['MIS_HELD', 'MIS_BOOKING_FAILED', 'RELEASED', 'CANCELLATION_REQUESTED'],
  MIS_HELD: ['PAYMENT_PENDING', 'CONFIRMED', 'RELEASED', 'CANCELLATION_REQUESTED'],
  PAYMENT_PENDING: ['PAYMENT_IN_PROGRESS', 'RELEASED', 'CANCELLATION_REQUESTED'],
  PAYMENT_IN_PROGRESS: ['PAYMENT_RECONCILIATION_PENDING', 'CONFIRMED', 'RELEASED', 'CANCELLATION_REQUESTED'],
  PAYMENT_RECONCILIATION_PENDING: ['CONFIRMED', 'RELEASED', 'CANCELLATION_REQUESTED'],
  MIS_BOOKING_FAILED: ['RELEASED'],
  CANCELLATION_REQUESTED: ['RELEASED'],
  RESCHEDULE_REQUESTED: ['CONFIRMED', 'RELEASED'],
  COMPLETED: [],
};

export function canTransition(from: HoldState, to: HoldState): boolean {
  return transitions[from].includes(to);
}

export function isMvpTerminalState(state: HoldState): boolean {
  return state === 'CONFIRMED' || state === 'EXPIRED' || state === 'RELEASED' || state === 'SLA_BREACHED';
}
