'use client';

import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { useEffectiveSession } from '@/components/auth/EffectiveSessionProvider';
import { loadVeterinarianVisitClinicalReadback, parseVeterinarianVisitDetail, parseVeterinarianVisits, type ClinicalResult, type VeterinarianVisit, type VeterinarianVisitClinicalReadback, type VeterinarianVisitDetail } from '@/lib/api/veterinarian-visits';

type Props = { clinicId: string; locationId: string; holdId?: string };
type State = 'idle' | 'loading' | 'unavailable' | 'error' | 'ready';

export function VeterinarianVisitWorkspace({ clinicId, locationId, holdId }: Props) {
  const { loading: sessionLoading, error: sessionError, hasCapability, hasClinicScope, refresh } = useEffectiveSession();
  const [state, setState] = useState<State>('idle'); const [visits, setVisits] = useState<VeterinarianVisit[]>([]); const [visit, setVisit] = useState<VeterinarianVisitDetail | null>(null); const [clinical, setClinical] = useState<VeterinarianVisitClinicalReadback | null>(null); const [reloadKey, setReloadKey] = useState(0);
  const scoped = hasClinicScope(clinicId, locationId); const allowed = !sessionLoading && !sessionError && hasCapability('clinical.visit.workspace.read') && scoped; const canWrite = hasCapability('clinical.visit.complete') && scoped;
  const endpoint = `/api/clinic/${clinicId}/locations/${locationId}/vet/visits${holdId ? `/${holdId}` : ''}`; const reload = () => setReloadKey((value) => value + 1);
  useEffect(() => { if (!allowed) { setState('idle'); return; } let active = true; setState('loading'); void fetch(endpoint, { cache: 'no-store' }).then(async (response) => { const payload = await response.json().catch(() => null); if (!active) return; if ([401, 403, 404].includes(response.status)) { setState('unavailable'); return; } if (!response.ok) { setState('error'); return; } if (holdId) { const parsed = parseVeterinarianVisitDetail(payload); if (!parsed) { setState('error'); return; } const readback = await loadVeterinarianVisitClinicalReadback(parsed); if (!active) return; setVisit(parsed); setClinical(readback); } else { const parsed = parseVeterinarianVisits(payload); if (!parsed) { setState('error'); return; } setVisits(parsed); } setState('ready'); }).catch(() => { if (active) setState('error'); }); return () => { active = false; }; }, [allowed, endpoint, holdId, reloadKey]);
  if (sessionLoading) return <SurfaceState title="Загрузка доступа…" busy />;
  if (sessionError) return <SurfaceState title="Раздел временно недоступен" retry={() => void refresh()} />;
  if (!allowed) return <SurfaceState title="Раздел недоступен" />;
  if (state === 'loading' || state === 'idle') return <SurfaceState title="Загрузка приёма…" busy />;
  if (state === 'unavailable') return <SurfaceState title={holdId ? 'Приём сейчас недоступен' : 'Приёмы сейчас недоступны'} />;
  if (state === 'error') return <SurfaceState title={holdId ? 'Не удалось получить приём' : 'Не удалось получить приёмы'} retry={reload} />;
  return holdId ? <VisitDetail visit={visit!} clinical={clinical} clinicId={clinicId} locationId={locationId} canWrite={canWrite} reload={reload} /> : <VisitList visits={visits} clinicId={clinicId} locationId={locationId} />;
}

function SurfaceState({ title, busy, retry }: { title: string; busy?: boolean; retry?: () => void }) { return <main className="min-h-screen px-4 py-6 sm:px-8" aria-live="polite" aria-busy={busy}><section className="mx-auto max-w-4xl rounded-lg border border-slate-200 bg-white p-6"><h1 className="text-2xl font-semibold text-slate-950">{title}</h1>{retry ? <button type="button" className="mt-4 min-h-11 rounded bg-slate-900 px-4 py-2 text-white" onClick={retry}>Повторить</button> : null}</section></main>; }
function VisitList({ visits, clinicId, locationId }: { visits: VeterinarianVisit[]; clinicId: string; locationId: string }) { return <main className="min-h-screen px-4 py-6 sm:px-8"><section className="mx-auto max-w-4xl" aria-labelledby="vet-visits-title"><h1 id="vet-visits-title" className="text-2xl font-semibold text-slate-950">Приёмы врача</h1>{visits.length === 0 ? <p className="mt-4 rounded-lg border border-slate-200 bg-white p-5 text-slate-600">Нет доступных приёмов.</p> : <ul className="mt-4 space-y-3">{visits.map((item) => <li key={item.holdId} className="rounded-lg border border-slate-200 bg-white p-5"><p className="font-semibold text-slate-950">{item.petDisplayName} · {item.species}</p><p className="mt-1 text-sm text-slate-600">{format(item.scheduledStart)} — {format(item.scheduledEnd)} · {item.status}</p><Link className="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-blue-700 underline" href={`/clinics/${clinicId}/locations/${locationId}/vet/visits/${item.holdId}`} aria-label={`Открыть приём ${item.petDisplayName}`}>Открыть приём</Link></li>)}</ul>}</section></main>; }
function VisitDetail({ visit, clinical, clinicId, locationId, canWrite, reload }: { visit: VeterinarianVisitDetail; clinical: VeterinarianVisitClinicalReadback | null; clinicId: string; locationId: string; canWrite: boolean; reload: () => void }) { return <main className="min-h-screen px-4 py-5 sm:px-8"><section className="mx-auto max-w-4xl" aria-labelledby="vet-visit-detail-title"><Link className="inline-flex min-h-11 items-center text-sm font-semibold text-blue-700 underline" href={`/clinics/${clinicId}/locations/${locationId}/vet/visits`}>К списку приёмов</Link><div className="rounded-lg border border-slate-200 bg-white p-5 sm:p-6"><header className="flex flex-col gap-3 border-b border-slate-200 pb-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 id="vet-visit-detail-title" className="text-2xl font-semibold text-slate-950">{visit.petDisplayName}</h1><p className="mt-1 text-sm text-slate-600">{visit.species} · {format(visit.scheduledStart)} — {format(visit.scheduledEnd)}</p></div><p className="text-sm font-medium text-slate-700">{visit.visitId ? 'Приём завершён' : 'Приём не завершён'}</p></header><div className="mt-5"><ClinicalWorkspace visit={visit} clinical={clinical} canWrite={canWrite} reload={reload} /></div></div></section></main>; }
function ClinicalWorkspace({ visit, clinical, canWrite, reload }: { visit: VeterinarianVisitDetail; clinical: VeterinarianVisitClinicalReadback | null; canWrite: boolean; reload: () => void }) { if (visit.visitId === null) return canWrite ? <CompleteVisit visit={visit} reload={reload} /> : <ReadOnlyNote text="Завершение приёма недоступно для вашей роли." />; if (!clinical?.result) return <CreateResult visitId={visit.visitId} canWrite={canWrite} reload={reload} />; return clinical.result.status === 'DRAFT' ? <DraftResult visitId={visit.visitId} result={clinical.result} canWrite={canWrite} reload={reload} /> : <PublishedResult visitId={visit.visitId} clinical={clinical} canWrite={canWrite} reload={reload} />; }

function CompleteVisit({ visit, reload }: { visit: VeterinarianVisitDetail; reload: () => void }) {
  const [summary, setSummary] = useState(''); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const field = useRef<HTMLTextAreaElement>(null);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (pending || !valid(summary, setError, field)) return; setPending(true); setError(''); try { const response = await fetch(`/api/clinic/booking-holds/${visit.holdId}/complete`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ summary }) }); if (response.ok || response.status === 409) { reload(); return; } setError(response.status === 400 ? 'Проверьте клиническое заключение.' : response.status === 401 || response.status === 403 ? 'Завершение приёма недоступно.' : 'Не удалось завершить приём. Повторите попытку.'); } catch { setError('Не удалось завершить приём. Повторите попытку.'); } finally { setPending(false); } }
  return <form onSubmit={submit} aria-label="Завершение приёма"><h2 className="text-lg font-semibold text-slate-950">Завершение приёма</h2><ClinicalField id="completion-summary" label="Клиническое заключение" value={summary} setValue={setSummary} fieldRef={field} pending={pending} error={error} /><Action pending={pending} idle="Завершить приём" busy="Завершение…" /></form>;
}

function CreateResult({ visitId, canWrite, reload }: { visitId: string; canWrite: boolean; reload: () => void }) {
  const [open, setOpen] = useState(false); const [content, setContent] = useState(''); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const field = useRef<HTMLTextAreaElement>(null); const key = useRef(crypto.randomUUID());
  async function submit(event: React.FormEvent) { event.preventDefault(); if (pending || !valid(content, setError, field)) return; setPending(true); setError(''); try { const response = await fetch(`/api/clinic/visits/${visitId}/results`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': key.current }, body: JSON.stringify({ clinicalSummary: content }) }); if (response.ok || response.status === 409) { reload(); return; } setError(message(response.status, 'Не удалось оформить результат.')); } catch { setError('Не удалось оформить результат. Повторите попытку.'); } finally { setPending(false); } }
  if (!canWrite) return <><h2 className="text-lg font-semibold text-slate-950">Приём завершён</h2><ReadOnlyNote text="Результат ещё не оформлен." /></>;
  return <section aria-labelledby="no-result-title"><h2 id="no-result-title" className="text-lg font-semibold text-slate-950">Приём завершён</h2><p className="mt-1 text-slate-600">Результат ещё не оформлен</p>{open ? <form className="mt-5" onSubmit={submit} aria-label="Оформление результата"><ClinicalField id="new-result" label="Текст результата" value={content} setValue={setContent} fieldRef={field} pending={pending} error={error} /><Action pending={pending} idle="Сохранить черновик" busy="Сохранение…" /></form> : <button type="button" className="mt-4 min-h-11 rounded bg-slate-900 px-4 py-2 text-white" onClick={() => setOpen(true)}>Оформить результат</button>}</section>;
}

function DraftResult({ visitId, result, canWrite, reload }: { visitId: string; result: ClinicalResult; canWrite: boolean; reload: () => void }) {
  const [content, setContent] = useState(result.clinicalSummary); const [notice, setNotice] = useState(''); const [pending, setPending] = useState(false); const [confirming, setConfirming] = useState(false); const field = useRef<HTMLTextAreaElement>(null); const publishButton = useRef<HTMLButtonElement>(null); const confirmButton = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (confirming) confirmButton.current?.focus(); }, [confirming]);
  async function save(event: React.FormEvent) { event.preventDefault(); if (pending || !valid(content, setNotice, field)) return; setPending(true); setNotice(''); try { const response = await fetch(`/api/clinic/visits/${visitId}/results/${result.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', 'If-Match': String(result.version) }, body: JSON.stringify({ clinicalSummary: content }) }); if (response.ok) { setNotice('Сохранено'); reload(); return; } if (response.status === 409) { reload(); return; } setNotice(message(response.status, 'Не удалось сохранить черновик.')); } catch { setNotice('Не удалось сохранить черновик. Повторите попытку.'); } finally { setPending(false); } }
  async function publish() { if (pending) return; setPending(true); setNotice(''); try { const response = await fetch(`/api/clinic/visits/${visitId}/results/${result.id}/publish`, { method: 'POST' }); if (response.ok || response.status === 409) { publishButton.current?.focus(); setConfirming(false); reload(); return; } setNotice(message(response.status, 'Не удалось опубликовать результат.')); } catch { setNotice('Не удалось опубликовать результат. Повторите попытку.'); } finally { setPending(false); } }
  return <section aria-labelledby="draft-title"><div className="flex flex-wrap items-center gap-3"><h2 id="draft-title" className="text-lg font-semibold text-slate-950">Результат приёма</h2><span className="rounded-full bg-amber-100 px-3 py-1 text-sm font-medium text-amber-950">Черновик</span></div><p className="mt-2 text-sm text-slate-600">Не виден владельцу питомца</p>{canWrite ? <form className="mt-5" onSubmit={save} aria-label="Редактирование черновика"><ClinicalField id="draft-result" label="Текст результата" value={content} setValue={(value) => { setContent(value); setNotice(''); }} fieldRef={field} pending={pending} error={notice} /><div className="flex flex-wrap gap-3"><Action pending={pending} idle="Сохранить" busy="Сохранение…" /><button ref={publishButton} type="button" className="min-h-11 rounded border border-slate-400 px-4 py-2 font-semibold text-slate-900" disabled={pending} onClick={() => setConfirming(true)}>Опубликовать результат</button></div></form> : <p className="mt-4 whitespace-pre-wrap text-slate-800">{result.clinicalSummary}</p>}{confirming ? <ConfirmPublish confirmRef={confirmButton} pending={pending} close={() => { setConfirming(false); publishButton.current?.focus(); }} publish={() => void publish()} /> : null}</section>;
}

function ConfirmPublish({ confirmRef, pending, close, publish }: { confirmRef: React.RefObject<HTMLButtonElement | null>; pending: boolean; close: () => void; publish: () => void }) {
  function handleKeyDown(event: React.KeyboardEvent<HTMLElement>) {
    if (event.key === 'Escape' && !pending) { event.preventDefault(); close(); return; }
    if (event.key !== 'Tab') return;
    const controls = Array.from(event.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)'));
    const first = controls[0]; const last = controls.at(-1); const active = document.activeElement;
    if (!first || !last) return;
    if (event.shiftKey && (active === first || !event.currentTarget.contains(active))) { event.preventDefault(); last.focus(); }
    else if (!event.shiftKey && (active === last || !event.currentTarget.contains(active))) { event.preventDefault(); first.focus(); }
  }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" role="presentation"><section role="dialog" aria-modal="true" aria-labelledby="publish-title" className="max-w-md rounded-lg bg-white p-6 shadow-xl" onKeyDown={handleKeyDown}><h3 id="publish-title" className="text-lg font-semibold text-slate-950">Опубликовать результат?</h3><p className="mt-3 text-sm text-slate-700">Результат станет доступен владельцу. Основной текст больше нельзя будет изменить; последующие исправления оформляются как уточнения.</p><div className="mt-5 flex flex-wrap gap-3"><button ref={confirmRef} type="button" className="min-h-11 rounded bg-slate-900 px-4 py-2 text-white" disabled={pending} onClick={publish}>{pending ? 'Публикация…' : 'Опубликовать'}</button><button type="button" className="min-h-11 rounded border border-slate-400 px-4 py-2" disabled={pending} onClick={close}>Отмена</button></div></section></div>;
}

function PublishedResult({ visitId, clinical, canWrite, reload }: { visitId: string; clinical: VeterinarianVisitClinicalReadback; canWrite: boolean; reload: () => void }) {
  const result = clinical.result!; const [open, setOpen] = useState(false); const [content, setContent] = useState(''); const [error, setError] = useState(''); const [pending, setPending] = useState(false); const field = useRef<HTMLTextAreaElement>(null); const key = useRef(crypto.randomUUID());
  async function amend(event: React.FormEvent) { event.preventDefault(); if (pending || !valid(content, setError, field)) return; setPending(true); setError(''); try { const response = await fetch(`/api/clinic/visits/${visitId}/results/${result.id}/amendments`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': key.current }, body: JSON.stringify({ content }) }); if (response.ok || response.status === 409) { reload(); return; } setError(message(response.status, 'Не удалось добавить уточнение.')); } catch { setError('Не удалось добавить уточнение. Повторите попытку.'); } finally { setPending(false); } }
  return <section aria-labelledby="published-title"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="published-title" className="text-lg font-semibold text-slate-950">Исходный результат</h2><span className="rounded-full bg-emerald-100 px-3 py-1 text-sm font-medium text-emerald-950">Опубликован</span></div><p className="mt-2 text-xs text-slate-500">Опубликован {result.publishedAt ? format(result.publishedAt) : ''}</p><p className="mt-4 whitespace-pre-wrap text-slate-900">{result.clinicalSummary}</p><section className="mt-6 border-t border-slate-200 pt-5" aria-labelledby="amendments-title"><h3 id="amendments-title" className="font-semibold text-slate-950">Уточнения</h3>{clinical.amendments.length ? <ol className="mt-3 space-y-3">{clinical.amendments.map((item) => <li key={item.amendmentId} className="border-l-2 border-slate-300 pl-4"><p className="whitespace-pre-wrap text-slate-800">{item.content}</p><p className="mt-1 text-xs text-slate-500">{format(item.publishedAt)}</p></li>)}</ol> : <p className="mt-2 text-sm text-slate-600">Уточнений нет.</p>}{canWrite ? open ? <form className="mt-5" onSubmit={amend} aria-label="Добавление уточнения"><ClinicalField id="amendment" label="Текст уточнения" value={content} setValue={setContent} fieldRef={field} pending={pending} error={error} /><div className="flex flex-wrap gap-3"><Action pending={pending} idle="Добавить уточнение" busy="Добавление…" /><button type="button" className="min-h-11 rounded border border-slate-400 px-4 py-2" disabled={pending} onClick={() => setOpen(false)}>Отмена</button></div></form> : <button type="button" className="mt-4 min-h-11 rounded bg-slate-900 px-4 py-2 text-white" onClick={() => setOpen(true)}>Добавить уточнение</button> : null}</section></section>;
}

function ClinicalField({ id, label, value, setValue, fieldRef, pending, error }: { id: string; label: string; value: string; setValue: (value: string) => void; fieldRef: React.RefObject<HTMLTextAreaElement | null>; pending: boolean; error: string }) { return <div className="mb-4"><label className="block text-sm font-semibold text-slate-800" htmlFor={id}>{label}</label><textarea ref={fieldRef} id={id} value={value} onChange={(event) => setValue(event.target.value)} className="mt-2 min-h-40 w-full rounded border border-slate-300 p-3 focus:border-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-200" minLength={3} maxLength={8000} required disabled={pending} aria-describedby={error ? `${id}-message` : undefined} />{error ? <p id={`${id}-message`} role="status" className={`mt-2 text-sm ${error === 'Сохранено' ? 'text-emerald-700' : 'text-red-700'}`}>{error}</p> : null}</div>; }
function Action({ pending, idle, busy }: { pending: boolean; idle: string; busy: string }) { return <button type="submit" className="min-h-11 rounded bg-slate-900 px-4 py-2 font-semibold text-white disabled:opacity-60" disabled={pending}>{pending ? busy : idle}</button>; }
function ReadOnlyNote({ text }: { text: string }) { return <p className="mt-2 text-slate-600" role="status">{text}</p>; }
function valid(value: string, setError: (value: string) => void, field: React.RefObject<HTMLTextAreaElement | null>) { const length = value.trim().length; if (length >= 3 && length <= 8000) return true; setError(length < 3 ? 'Введите не менее 3 символов.' : 'Введите не более 8000 символов.'); field.current?.focus(); return false; }
function message(status: number, fallback: string) { return status === 400 ? 'Проверьте введённый текст.' : status === 401 || status === 403 ? 'Изменение недоступно для вашей роли.' : `${fallback} Повторите попытку.`; }
function format(value: string) { return new Date(value).toLocaleString('ru-RU'); }
