import { apiClient, type ApiClient } from '@/api/client';

export type ClinicServiceHandoff=Readonly<{clinicId:string;locationId:string;serviceId:string}>;
export type SpecialistNextAvailability=Readonly<{startsAt:string;localDate:string;localTime:string;timezone:string}>;
export type ClinicServiceSpecialist=Readonly<{doctorId:string;displayName:string;specialtyName:string;nextAvailability:SpecialistNextAvailability}>;
export type ClinicService=Readonly<{serviceId:string;name:string;price:Readonly<{kind:'INFORMATIONAL';amount:string;currency:string}>;specialty:Readonly<{id:string;name:string}>|null;specialists:ClinicServiceSpecialist[]}>;
export type ClinicServiceSnapshot=Readonly<{observedAt:string;clinicId:string;locationId:string;name:string;address:string;phone:string|null;services:ClinicService[]}>;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const exact=(value:Record<string,unknown>,keys:string[])=>Object.keys(value).sort().join()===keys.sort().join();
const calendarDate=(value:unknown)=>{if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const [year,month,day]=value.split('-').map(Number),date=new Date(Date.UTC(year,month-1,day));return date.getUTCFullYear()===year&&date.getUTCMonth()+1===month&&date.getUTCDate()===day;};
const instant=(value:unknown)=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(value)&&Number.isFinite(Date.parse(value))&&calendarDate(value.slice(0,10));
const timezone=(value:unknown)=>{if(typeof value!=='string'||value.length>64)return false;try{new Intl.DateTimeFormat('en-US',{timeZone:value}).format(0);return true;}catch{return false;}};
export function parseClinicServiceSnapshot(raw:unknown):ClinicServiceSnapshot{
  if(!raw||typeof raw!=='object')throw new Error('INVALID_CLINIC_SERVICE_RESPONSE');
  const value=raw as Record<string,unknown>;
  if(!exact(value,['observedAt','clinicId','locationId','name','address','phone','services'])||typeof value.observedAt!=='string'||!Number.isFinite(Date.parse(value.observedAt))||typeof value.clinicId!=='string'||!UUID.test(value.clinicId)||typeof value.locationId!=='string'||!UUID.test(value.locationId)||typeof value.name!=='string'||typeof value.address!=='string'||!(value.phone===null||typeof value.phone==='string')||!Array.isArray(value.services)||value.services.length>50)throw new Error('INVALID_CLINIC_SERVICE_RESPONSE');
  const services=value.services.map(rawService=>{if(!rawService||typeof rawService!=='object')throw new Error('INVALID_CLINIC_SERVICE_RESPONSE');const service=rawService as Record<string,unknown>,price=service.price as Record<string,unknown>|null;if(!exact(service,['serviceId','name','price','specialty','specialists'])||typeof service.serviceId!=='string'||!UUID.test(service.serviceId)||typeof service.name!=='string'||!price||typeof price!=='object'||!exact(price,['kind','amount','currency'])||price.kind!=='INFORMATIONAL'||typeof price.amount!=='string'||!/^\d{1,10}\.\d{2}$/.test(price.amount)||typeof price.currency!=='string'||!/^[A-Z]{3}$/.test(price.currency)||!Array.isArray(service.specialists)||service.specialists.length>10)throw new Error('INVALID_CLINIC_SERVICE_RESPONSE');
    let specialty:ClinicService['specialty']=null;if(service.specialty!==null){if(!service.specialty||typeof service.specialty!=='object')throw new Error('INVALID_CLINIC_SERVICE_RESPONSE');const value=service.specialty as Record<string,unknown>;if(!exact(value,['id','name'])||typeof value.id!=='string'||!UUID.test(value.id)||typeof value.name!=='string')throw new Error('INVALID_CLINIC_SERVICE_RESPONSE');specialty={id:value.id,name:value.name};}
    const specialists=service.specialists.map(raw=>{if(!raw||typeof raw!=='object')throw new Error('INVALID_CLINIC_SERVICE_RESPONSE');const specialist=raw as Record<string,unknown>,next=specialist.nextAvailability as Record<string,unknown>|null,displayName=typeof specialist.displayName==='string'?specialist.displayName.trim():'';if(!exact(specialist,['doctorId','displayName','specialtyName','nextAvailability'])||typeof specialist.doctorId!=='string'||!UUID.test(specialist.doctorId)||typeof specialist.displayName!=='string'||displayName===''||displayName!==specialist.displayName||UUID.test(displayName)||typeof specialist.specialtyName!=='string'||specialist.specialtyName.trim()===''||!next||typeof next!=='object'||!exact(next,['startsAt','localDate','localTime','timezone'])||!instant(next.startsAt)||!calendarDate(next.localDate)||typeof next.localTime!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(next.localTime)||!timezone(next.timezone))throw new Error('INVALID_CLINIC_SERVICE_RESPONSE');return {doctorId:specialist.doctorId,displayName:specialist.displayName,specialtyName:specialist.specialtyName,nextAvailability:next as SpecialistNextAvailability};});
    return {serviceId:service.serviceId,name:service.name,price:{kind:'INFORMATIONAL' as const,amount:price.amount,currency:price.currency},specialty,specialists};});
  return {observedAt:value.observedAt,clinicId:value.clinicId,locationId:value.locationId,name:value.name,address:value.address,phone:value.phone,services};
}
export function createClinicServiceApi(client:ApiClient=apiClient){return{async read(credential:string,clinicId:string,locationId:string,signal?:AbortSignal){return parseClinicServiceSnapshot(await client.request<unknown>(`v1/owner/clinic-catalog/${clinicId}/locations/${locationId}`,{headers:{Authorization:`Bearer ${credential}`},signal}));}};}
export const clinicServiceApi=createClinicServiceApi();
