import { fireEvent, render, waitFor } from '@testing-library/react-native';
import { ClinicServiceScreen } from './ClinicServiceScreen';
const C='11111111-1111-4111-8111-111111111111',L='22222222-2222-4222-8222-222222222222',S='33333333-3333-4333-8333-333333333333';
const mockUseQuery=jest.fn();
jest.mock('@tanstack/react-query',()=>({useQuery:(input:unknown)=>mockUseQuery(input)}));
jest.mock('@/session/SessionProvider',()=>({useSession:()=>({session:{cacheScope:'owner-a',opaqueCredential:'token-a'}})}));
const data={clinicId:C,locationId:L,name:'Clinic',address:'Address',phone:null,services:[{serviceId:S,name:'Осмотр',price:{kind:'INFORMATIONAL',amount:'1250.00',currency:'RUB'}}]};
describe('ClinicServiceScreen',()=>{
  it('selects one service and refreshes authority before exact handoff',async()=>{const onContinue=jest.fn(),refetch=jest.fn().mockResolvedValue({data});mockUseQuery.mockReturnValue({isPending:false,isError:false,data,refetch});const screen=await render(<ClinicServiceScreen clinic={{clinicId:C,locationId:L}} onBack={jest.fn()} onContinue={onContinue}/>);fireEvent.press(screen.getByText('Осмотр'));await waitFor(()=>expect(screen.getByRole('radio').props.accessibilityState.selected).toBe(true));fireEvent.press(screen.getByText('Продолжить'));await waitFor(()=>expect(onContinue).toHaveBeenCalledWith({clinicId:C,locationId:L,serviceId:S}));expect(refetch).toHaveBeenCalledTimes(1);expect(screen.getByText('Ориентировочная стоимость: 1 250 ₽')).toBeTruthy();});
  it('restores a retained service selection after Back',async()=>{mockUseQuery.mockReturnValue({isPending:false,isError:false,data,refetch:jest.fn()});const screen=await render(<ClinicServiceScreen clinic={{clinicId:C,locationId:L}} initialServiceId={S} onBack={jest.fn()} onContinue={jest.fn()}/>);expect(screen.getByRole('radio').props.accessibilityState.selected).toBe(true);expect(screen.getByText('Ориентировочная стоимость: 1 250 ₽')).toBeTruthy();});
  it('clears stale selection and does not continue',async()=>{const onContinue=jest.fn(),refetch=jest.fn().mockResolvedValue({data:{...data,services:[]}});mockUseQuery.mockReturnValue({isPending:false,isError:false,data,refetch});const screen=await render(<ClinicServiceScreen clinic={{clinicId:C,locationId:L}} onBack={jest.fn()} onContinue={onContinue}/>);fireEvent.press(screen.getByText('Осмотр'));await waitFor(()=>expect(screen.getByRole('radio').props.accessibilityState.selected).toBe(true));fireEvent.press(screen.getByText('Продолжить'));await waitFor(()=>expect(screen.getByText('Выбранная услуга больше недоступна. Выберите другую.')).toBeTruthy());expect(onContinue).not.toHaveBeenCalled();});
  it('never continues from stale cached data after a failed refresh',async()=>{const onContinue=jest.fn(),refetch=jest.fn().mockResolvedValue({isError:true,data});mockUseQuery.mockReturnValue({isPending:false,isError:false,data,refetch});const screen=await render(<ClinicServiceScreen clinic={{clinicId:C,locationId:L}} onBack={jest.fn()} onContinue={onContinue}/>);fireEvent.press(screen.getByText('Осмотр'));await waitFor(()=>expect(screen.getByRole('radio').props.accessibilityState.selected).toBe(true));fireEvent.press(screen.getByText('Продолжить'));await waitFor(()=>expect(screen.getByText('Не удалось проверить услугу. Повторите попытку.')).toBeTruthy());expect(onContinue).not.toHaveBeenCalled();});
  it.each([[{isPending:true,isError:false},'Загружаем услуги'],[{isPending:false,isError:false,data:{...data,services:[]}},'В этой клинике пока нет доступных услуг'],[{isPending:false,isError:true,data,refetch:jest.fn()},'Не удалось обновить карточку клиники']])('renders deterministic state %#',async(state,label)=>{mockUseQuery.mockReturnValue(state);const screen=await render(<ClinicServiceScreen clinic={{clinicId:C,locationId:L}} onBack={jest.fn()} onContinue={jest.fn()}/>);expect(screen.getByText(label)).toBeTruthy();if(state.isError)expect(screen.queryByText('Осмотр')).toBeNull();});
});
