apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vethelp-backend-runtime
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: alpha-vault-store
  target:
    name: alpha-vethelp-backend-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data: []
