apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vethelp-backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vethelp-backend
      app.kubernetes.io/component: backend
