'use client';
import {useEffect,useRef,useState,type KeyboardEvent} from 'react';
import {EffectiveSessionProvider,useEffectiveSession} from '@/components/auth/EffectiveSessionProvider';
import type {ChangeRequestDetail,ChangeRequestPage} from '@/lib/api/booking-change-requests';
import {allowedChangeRequestCommands,canApplyChangeRequest,commandFingerprint,isDefinitiveCommandResponse,stableCommandKey} from '@/lib/api/booking-change-request-actions';
const labels={CANCEL:'Отмена',RESCHEDULE:'Перенос',OPEN:'Открыта',PROCESSING:'В работе',COMPLETED:'Завершена',REJECTED:'Отклонена',CANCELLED:'Отменена'} as const;
const actionClass='min-h-11 rounded-md border px-3 text-sm font-semibold disabled:opacity-50';
const neutralActionClass=`${actionClass} border-slate-300 bg-white text-slate-950 hover:bg-slate-50`;
function Workspace({initial,initialError}:{initial:ChangeRequestPage|null;initialError:string|null}){
 const access=useEffectiveSession();const commandKeys=useRef(new Map<string,string>());const detailPanel=useRef<HTMLElement|null>(null);const detailTrigger=useRef<HTMLElement|null>(null);const [overlay,setOverlay]=useState(false);const [page,setPage]=useState(initial);const [detail,setDetail]=useState<ChangeRequestDetail|null>(null);const [replacementSlotId,setReplacementSlotId]=useState('');const [error,setError]=useState(initialError);const [busy,setBusy]=useState(false);const read=access.hasCapability('booking.change-request.read');const process=access.hasCapability('booking.change-request.process');
 useEffect(()=>{const media=window.matchMedia('(max-width: 1279px)');const sync=()=>setOverlay(media.matches);sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync);},[]);
 useEffect(()=>{if(detail&&overlay)requestAnimationFrame(()=>detailPanel.current?.querySelector<HTMLElement>('button:not([disabled]),select:not([disabled])')?.focus());},[detail?.requestId,overlay]);
 const closeDetail=()=>{setDetail(null);requestAnimationFrame(()=>detailTrigger.current?.focus());};
 const trapDetail=(event:KeyboardEvent<HTMLElement>)=>{if(!overlay)return;if(event.key==='Escape'){event.preventDefault();closeDetail();return;}if(event.key!=='Tab')return;const focusable=[...(detailPanel.current?.querySelectorAll<HTMLElement>('button:not([disabled]),select:not([disabled])')??[])];if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};
 const refresh=async()=>{setBusy(true);setError(null);try{const response=await fetch('/api/ops/change-requests',{cache:'no-store'});if(!response.ok)throw new Error(response.status===403?'FORBIDDEN':'LOAD_FAILED');setPage(await response.json());}catch(e){setError(e instanceof Error?e.message:'LOAD_FAILED');}finally{setBusy(false);}};
 const open=async(id:string)=>{detailTrigger.current=document.activeElement as HTMLElement|null;setBusy(true);setError(null);setReplacementSlotId('');try{const response=await fetch(`/api/ops/change-requests/${id}`,{cache:'no-store'});if(!response.ok)throw new Error(response.status===403?'FORBIDDEN':'LOAD_FAILED');setDetail(await response.json());}catch(e){setError(e instanceof Error?e.message:'LOAD_FAILED');}finally{setBusy(false);}};
 const command=async(action:string)=>{if(!detail)return;const replacement=detail.replacementSlots.find(slot=>slot.slotId===replacementSlotId);const body=action==='complete'&&detail.requestType==='RESCHEDULE'&&replacement?{replacementSlotId:replacement.slotId,replacementSlotVersion:replacement.version}:{};const fingerprint=commandFingerprint(detail.requestId,action,detail.version,replacementSlotId);const key=stableCommandKey(commandKeys.current,fingerprint,()=>crypto.randomUUID());setBusy(true);setError(null);try{const response=await fetch(`/api/ops/change-requests/${detail.requestId}/${action}`,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key,'If-Match':String(detail.version)},body:JSON.stringify(body)});if(!response.ok){if(isDefinitiveCommandResponse(response.status))commandKeys.current.delete(fingerprint);const payload=await response.json().catch(()=>({})) as {code?:string};throw new Error(response.status===409?`STALE:${payload.code??'CONFLICT'}`:response.status===403?'FORBIDDEN':payload.code??'COMMAND_FAILED');}commandKeys.current.delete(fingerprint);setDetail(await response.json());setReplacementSlotId('');await refresh();}catch(e){const message=e instanceof Error?e.message:'COMMAND_FAILED';await open(detail.requestId);await refresh();setError(message);}finally{setBusy(false);}};
 if(access.loading)return <main className="min-h-screen p-6" aria-busy="true">Проверяем доступ…</main>;if(access.error)return <State text="Не удалось проверить доступ" retry={()=>void access.refresh()}/>;if(!read)return <State text="403 · Нет доступа к очереди"/>;const commands=detail?allowedChangeRequestCommands(detail.status,process):[];
 return <main className="min-h-screen bg-slate-50 px-4 py-4 text-slate-950 sm:px-6"><header className="flex min-h-14 items-center justify-between gap-4 border-b border-slate-200 pb-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-blue-700">Operations</p><h1 className="text-2xl font-semibold">Запросы на изменение записи</h1></div><button className={neutralActionClass} onClick={()=>void refresh()} disabled={busy}>Обновить очередь</button></header>
 {error&&!(detail&&overlay)&&<ErrorBanner error={error} retry={refresh}/>}
 <div className="mt-3 grid min-h-[calc(100vh-7rem)] gap-2 xl:grid-cols-[minmax(0,1fr)_minmax(340px,32%)]"><section className="min-w-0 overflow-x-auto border border-slate-200 bg-white" aria-busy={busy} aria-label="Очередь запросов">{!page?.items.length?<p className="p-4 text-sm text-slate-600">Нет открытых запросов.</p>:<table className="w-full min-w-0 border-collapse text-left text-sm xl:min-w-[760px]"><thead className="bg-slate-100 text-xs uppercase text-slate-600"><tr><th className="h-10 px-3">Запрос</th><th className="px-3">Статус</th><th className="hidden px-3 xl:table-cell">Создан</th><th className="hidden px-3 xl:table-cell">Booking</th><th className="hidden px-3 xl:table-cell">Локация</th><th className="px-3"><span className="sr-only">Открыть</span></th></tr></thead><tbody className="divide-y divide-slate-200">{page.items.map(item=><tr key={item.requestId} className={detail?.requestId===item.requestId?'bg-blue-50':'hover:bg-slate-50'}><td className="px-3 py-2 font-semibold">{labels[item.requestType]}</td><td className="px-3 py-2"><span className="inline-flex rounded-full border border-slate-300 px-2 py-1 text-xs font-semibold">{labels[item.status]}</span></td><td className="hidden whitespace-nowrap px-3 py-2 xl:table-cell">{new Date(item.createdAt).toLocaleString('ru-RU')}</td><td className="hidden max-w-44 truncate px-3 py-2 font-mono text-xs xl:table-cell" title={item.bookingHoldId}>{item.bookingHoldId}</td><td className="hidden max-w-44 truncate px-3 py-2 font-mono text-xs xl:table-cell" title={item.locationId}>{item.locationId}</td><td className="px-2 py-1"><button className={`${neutralActionClass} w-full`} onClick={()=>void open(item.requestId)}>Открыть</button></td></tr>)}</tbody></table>}</section>
 <aside ref={detailPanel} onKeyDown={trapDetail} role={detail&&overlay?'dialog':undefined} aria-modal={detail&&overlay?true:undefined} className={`${detail?'fixed inset-0 z-20 overflow-y-auto':'hidden'} border border-slate-200 bg-white p-4 xl:static xl:z-auto xl:block`} aria-label="Детали запроса">{!detail?<p className="text-sm text-slate-600">Выберите запрос в очереди.</p>:<>{error&&overlay&&<ErrorBanner error={error} retry={refresh}/>}<div className="flex items-start justify-between gap-3 border-b border-slate-200 pb-3"><div><p className="text-xs font-semibold uppercase text-blue-700">{labels[detail.status]}</p><h2 className="text-xl font-semibold">{labels[detail.requestType]} записи</h2></div><button className={`${neutralActionClass} xl:hidden`} onClick={closeDetail}>Закрыть</button></div><dl className="divide-y divide-slate-100 text-sm"><Row k="Создан" v={new Date(detail.createdAt).toLocaleString('ru-RU')}/><Row k="Время сервера" v={new Date(detail.serverNow).toLocaleString('ru-RU')}/><Row k="Booking / статус" v={`${detail.bookingHoldId} · ${detail.currentBookingStatus}`}/><Row k="Appointment / статус" v={`${detail.appointmentId??'—'} · ${detail.currentAppointmentStatus??'—'}`}/><Row k="Клиника" v={detail.clinicId}/><Row k="Локация" v={detail.locationId}/></dl>{detail.requestType==='RESCHEDULE'&&detail.status==='PROCESSING'&&<label className="mt-3 block text-sm font-semibold">Новый опубликованный слот<select className="mt-1 min-h-11 w-full rounded-md border border-slate-300 px-2 font-normal" value={replacementSlotId} onChange={event=>setReplacementSlotId(event.target.value)}><option value="">Выберите слот</option>{detail.replacementSlots.map(slot=><option key={slot.slotId} value={slot.slotId}>{new Date(slot.startsAt).toLocaleString('ru-RU')}</option>)}</select>{detail.replacementSlots.length===0&&<span className="mt-1 block font-normal text-amber-700">Подходящих опубликованных слотов сейчас нет.</span>}</label>}<div className="sticky bottom-0 mt-3 flex flex-wrap gap-2 border-t border-slate-200 bg-white py-3">{!process&&<span className="flex min-h-11 items-center text-sm text-slate-600">Режим только для чтения</span>}{commands.includes('start')&&<button className={`${actionClass} border-blue-700 bg-blue-700 text-white hover:bg-blue-800`} onClick={()=>void command('start')} disabled={busy}>Взять в работу</button>}{commands.includes('complete')&&<button className={`${actionClass} border-emerald-700 bg-emerald-700 text-white hover:bg-emerald-800`} onClick={()=>void command('complete')} disabled={busy||!canApplyChangeRequest(detail.requestType,detail.status,replacementSlotId,process)}>Применить изменение</button>}{commands.includes('reject')&&<button className={neutralActionClass} onClick={()=>void command('reject')} disabled={busy}>Отклонить</button>}{commands.includes('cancel')&&<button className={neutralActionClass} onClick={()=>void command('cancel')} disabled={busy}>Отменить запрос</button>}</div></>}</aside></div></main>;
}
const ErrorBanner=({error,retry}:{error:string;retry:()=>Promise<void>})=><div role="alert" className="mb-3 flex min-h-11 items-center justify-between gap-3 border border-amber-300 bg-amber-50 px-3 text-sm"><span>{error.startsWith('STALE:')?'Запрос уже изменён другим оператором. Показана актуальная версия.':'Действие не выполнено.'}</span><button className={neutralActionClass} onClick={()=>void retry()}>Повторить</button></div>;
const Row=({k,v}:{k:string;v:string})=><div className="grid gap-1 py-3 sm:grid-cols-[130px_1fr]"><dt className="font-medium text-slate-500">{k}</dt><dd className="break-all">{v}</dd></div>;
const State=({text,retry}:{text:string;retry?:()=>void})=><main className="min-h-screen p-6"><p>{text}</p>{retry&&<button className={neutralActionClass} onClick={retry}>Повторить</button>}</main>;
export function ChangeRequestWorkspace(props:{initial:ChangeRequestPage|null;initialError:string|null}){return <EffectiveSessionProvider><Workspace {...props}/></EffectiveSessionProvider>;}
