#!/usr/bin/env bash
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
OUT="$ROOT/docs/assets-manifest.md"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

mkdir -p "$(dirname "$OUT")"

find "$ROOT" \
  -type d \( \
    -name .git -o -name node_modules -o -name .next -o -name dist -o \
    -name build -o -name coverage -o -name playwright-report -o -name test-results \
  \) -prune -o \
  -type f \( \
    -iname '*.svg' -o -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o \
    -iname '*.webp' -o -iname '*.gif' -o -iname '*.avif' -o -iname '*.ico' -o \
    -iname '*.woff' -o -iname '*.woff2' -o -iname '*.ttf' -o -iname '*.otf' \
  \) -print0 \
  | while IFS= read -r -d '' file; do
      rel="${file#$ROOT/}"
      ext="${file##*.}"
      size="$(du -h "$file" | awk '{print $1}')"
      printf '%s\t%s\t%s\n' "$rel" "$ext" "$size"
    done \
  | LC_ALL=C sort > "$TMP"

{
  echo '# Assets manifest'
  echo
  echo 'Generated by `scripts/update-assets-manifest.sh`.'
  echo
  echo 'Use this manifest before searching or opening binary assets.'
  echo
  echo '| Path | Extension | Size |'
  echo '|---|---:|---:|'
  while IFS=$'\t' read -r rel ext size; do
    printf '| `%s` | `%s` | %s |\n' "$rel" "$ext" "$size"
  done < "$TMP"
} > "$OUT"

echo "Updated: $OUT"
