import { expect, test } from '@playwright/test';
import { AxeBuilder } from '@axe-core/playwright';
import type { BrowserContext } from '@playwright/test';
import { createServer, type Server } from 'node:http';
import { SignJWT } from 'jose';

const clinicId='11111111-1111-4111-8111-111111111111', locationId='22222222-2222-4222-8222-222222222222', holdId='44444444-4444-4444-8444-444444444444', slotId='66666666-6666-4666-8666-666666666666', secret='clinic-e2e-secret-at-least-32-bytes';
let server: Server, caps=['booking.queue.read','booking.hold.read','booking.replay.read'], mode='success', eventsReads=0, release: (()=>void)|null=null;
const event=(type='booking.confirmed.v1')=>({eventId:'77777777-7777-4777-8777-777777777777',eventType:type,occurredAt:'2026-07-20T10:00:00.000Z',payload:{secret:'raw-payload'},correlationId:'correlation-secret',traceparent:'trace-secret'});
test.beforeAll(async()=>{server=createServer((req,res)=>{const path=new URL(req.url??'/',`http://${req.headers.host}`).pathname;const send=(s:number,b:unknown)=>{res.writeHead(s,{'Content-Type':'application/json'});res.end(JSON.stringify(b));};if(path==='/v1/auth/session')return send(200,{subjectId:'u',roles:['CLINIC_RECEPTIONIST'],effectiveCapabilities:caps,clinicScopes:[{clinicId,locationId}]});if(path===`/v1/clinic/${clinicId}/locations/${locationId}/booking-queue`)return send(200,{clinicId,locationId,serverNow:'2026-07-20T08:00:00.000Z',items:[{holdId,version:1,holdExpiresAt:'2026-07-20T09:00:00.000Z',manualConfirmPendingAt:'2026-07-20T08:00:00.000Z',confirmationSlaExpiresAt:'2026-07-20T09:00:00.000Z',slot:{id:slotId,startsAt:'2026-07-20T10:00:00.000Z',endsAt:'2026-07-20T10:30:00.000Z'},pet:{id:slotId,name:'Барс',species:'cat'},service:null}]});if(path===`/v1/booking-holds/${holdId}`)return send(200,{holdId,slotId,state:'CONFIRMED',expiresAt:'2026-07-20T09:00:00.000Z',clinicLocationId:locationId,startsAt:'2026-07-20T10:00:00.000Z',endsAt:'2026-07-20T10:30:00.000Z'});if(path===`/v1/booking-holds/${holdId}/events`){eventsReads++;if(mode==='deny')return send(403,{x:'secret'});if(mode==='bad')return send(200,{holdId,events:[event(),{eventId:'bad'}]});if(mode==='empty')return send(200,{holdId,events:[]});if(mode==='pending'){let released=false;return void (release=()=>{if(released)return;released=true;if(!res.headersSent&&!res.writableEnded&&!res.destroyed)send(200,{holdId,events:[event()]});});}if(mode==='error')return send(503,{x:'secret'});return send(200,{holdId,events:[event(),event('unknown.internal.v1')]});}send(404,{});});await new Promise<void>(r=>server.listen(3212,'127.0.0.1',r));});
test.afterAll(async()=>{release?.();await new Promise<void>((r,j)=>server.close(e=>e?j(e):r()));});test.beforeEach(()=>{caps=['booking.queue.read','booking.hold.read','booking.replay.read'];mode='success';eventsReads=0;release=null;});
async function session(context:BrowserContext,baseURL:string|undefined){if(!baseURL)throw new Error('baseURL');const token=await new SignJWT({roles:['CLINIC_RECEPTIONIST'],clinicIds:[clinicId],locationIds:[locationId]}).setProtectedHeader({alg:'HS256'}).setSubject('u').setExpirationTime('1h').sign(new TextEncoder().encode(secret));await context.addCookies([{name:'vethelp_clinic_session',value:token,url:baseURL}]);}
async function inspector(page:any){await page.getByRole('button',{name:'Состояние удержания'}).first().click();await expect(page.getByRole('heading',{name:'Состояние удержания слота'})).toBeVisible();}
async function open(page:any){await page.getByRole('button',{name:'История обработки'}).click();return page.getByRole('dialog',{name:'История обработки'});}
test('suppresses replay without capability and renders only safe ordered history',async({page,context,baseURL})=>{caps=['booking.queue.read','booking.hold.read'];await session(context,baseURL);await page.goto(`/clinics/${clinicId}/locations/${locationId}/queue`);await inspector(page);await expect(page.getByRole('button',{name:'История обработки'})).toHaveCount(0);expect(eventsReads).toBe(0);caps.push('booking.replay.read');await page.reload();await inspector(page);const panel=await open(page);await expect(panel.getByText('Запись подтверждена')).toBeVisible();await expect(panel.getByText('Событие обработки')).toBeVisible();await expect(panel.getByText(/raw-payload|correlation-secret|trace-secret|unknown\.internal/i)).toHaveCount(0);expect((await new AxeBuilder({page}).include('[role="dialog"]').analyze()).violations).toEqual([]);});
test('shows empty replay history',async({page,context,baseURL})=>{await session(context,baseURL);await page.route('**/api/booking-holds/**/events',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({holdId,events:[]})}));await page.goto(`/clinics/${clinicId}/locations/${locationId}/queue`);await inspector(page);const panel=await open(page);await expect(panel.getByText('История обработки пока пуста.')).toBeVisible();});
test('fails closed for malformed replay response',async({page,context,baseURL})=>{await session(context,baseURL);await page.route('**/api/booking-holds/**/events',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({holdId,events:[{id:'raw',payload:{secret:'raw-payload'}}]})}));await page.goto(`/clinics/${clinicId}/locations/${locationId}/queue`);await inspector(page);const panel=await open(page);await expect(panel.getByText('История обработки сейчас недоступна.')).toBeVisible();await expect(panel.getByRole('button',{name:'Повторить'})).toHaveCount(0);await expect(panel.getByText(/raw-payload|raw/i)).toHaveCount(0);});
for(const status of [401,403,404])test(`fails closed for replay denial ${status}`,async({page,context,baseURL})=>{await session(context,baseURL);await page.route('**/api/booking-holds/**/events',route=>route.fulfill({status,contentType:'application/json',body:JSON.stringify({code:'PRIVATE'})}));await page.goto(`/clinics/${clinicId}/locations/${locationId}/queue`);await inspector(page);const panel=await open(page);await expect(panel.getByText('История обработки сейчас недоступна.')).toBeVisible();await expect(panel.getByRole('button',{name:'Повторить'})).toHaveCount(0);await expect(panel.getByText(/PRIVATE|raw-payload|correlation-secret/i)).toHaveCount(0);});
test('retries once and aborts a pending replay',async({page,context,baseURL})=>{mode='error';await session(context,baseURL);await page.goto(`/clinics/${clinicId}/locations/${locationId}/queue`);await inspector(page);const panel=await open(page);await expect(panel.getByRole('button',{name:'Повторить'})).toBeVisible();mode='pending';await panel.getByRole('button',{name:'Повторить'}).click();await expect(panel.getByRole('button',{name:'Повторная попытка…'})).toBeDisabled();expect(eventsReads).toBe(2);await panel.getByRole('button',{name:'Закрыть историю обработки'}).click();release?.();await expect(page.getByRole('heading',{name:'История обработки'})).toHaveCount(0);await expect(page.getByRole('button',{name:'История обработки'})).toBeFocused();});
