import { test,expect,type BrowserContext } from '@playwright/test';
import { AxeBuilder } from '@axe-core/playwright';
import { createServer,type Server } from 'node:http';
import { SignJWT } from 'jose';
const id=(digit:string)=>`${digit.repeat(8)}-${digit.repeat(4)}-4${digit.repeat(3)}-8${digit.repeat(3)}-${digit.repeat(12)}`;
const clinic=id('1'),location=id('2'),hold=id('3'),appointment=id('4'),result=id('5'),amendmentA=id('6'),amendmentB=id('7'),document=id('8');
const root=`/v1/clinic/appointments/${appointment}/medical-shares`,bff=`/api/clinic/appointments/${appointment}/medical-shares`;
let server:Server,mode:'shared'|'none'|'revoked'|'error'|'malformed'='none',role='CLINIC_VETERINARIAN',reads=0;
const refs=[{type:'AMENDMENT',id:amendmentB},{type:'DOCUMENT',id:document},{type:'RESULT',id:result},{type:'AMENDMENT',id:amendmentA}];
test.describe.configure({mode:'serial'});
test.beforeAll(async()=>{server=createServer((request,response)=>{const path=new URL(request.url??'/',`http://${request.headers.host}`).pathname;const json=(status:number,body:unknown)=>{response.writeHead(status,{'Content-Type':'application/json'});response.end(JSON.stringify(body));};
  if(path==='/v1/auth/session')return json(200,{subjectId:'vet-user',roles:[role],effectiveCapabilities:role==='CLINIC_VETERINARIAN'?['clinical.visit.workspace.read','medical.shared-data.read']:[],clinicScopes:[{clinicId:clinic,locationId:location}]});
  if(path===`/v1/clinic/${clinic}/locations/${location}/vet/visits/${hold}`)return json(200,{holdId:hold,appointmentId:appointment,clinicId:clinic,locationId:location,scheduledStart:'2026-10-07T10:00:00.000Z',scheduledEnd:'2026-10-07T10:30:00.000Z',status:'CONFIRMED',petDisplayName:'Milo',species:'CAT',visitId:null});
  if(path.startsWith(root)){reads++;if(mode==='error')return json(500,{private:'never forwarded'});if(mode==='revoked')return json(404,{code:'MEDICAL_SHARE_NOT_FOUND'});
    if(path===root)return json(200,{appointmentId:appointment,status:mode==='none'?'NOT_SHARED':'SHARED',resources:mode==='none'?[]:refs});
    if(path.endsWith(result))return json(200,mode==='malformed'?{type:'RESULT',id:result,content:'Private malformed payload',publishedAt:'2026-10-01T10:00:00.000Z',storageUrl:'private-source'}:{type:'RESULT',id:result,content:'Selected original result',publishedAt:'2026-10-01T10:00:00.000Z'});
    if(path.endsWith(document))return json(200,{type:'DOCUMENT',id:document,fileName:'selected-history.pdf',mimeType:'application/pdf',createdAt:'2026-10-02T10:00:00.000Z'});
    if(path.endsWith(amendmentA)||path.endsWith(amendmentB)){const first=path.endsWith(amendmentA);return json(200,{type:'AMENDMENT',id:first?amendmentA:amendmentB,content:first?'First selected amendment':'Second selected amendment',version:first?1:2,publishedAt:first?'2026-10-03T10:00:00.000Z':'2026-10-04T10:00:00.000Z'});}
  }return json(404,{code:'NOT_FOUND'});
});await new Promise<void>(resolve=>server.listen(3212,'127.0.0.1',resolve));});
test.afterAll(async()=>{await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));});
test.beforeEach(()=>{mode='none';role='CLINIC_VETERINARIAN';reads=0;});
async function session(context:BrowserContext,baseURL:string|undefined){if(!baseURL)throw new Error('baseURL required');const token=await new SignJWT({roles:[role],clinicIds:[clinic],locationIds:[location]}).setProtectedHeader({alg:'HS256'}).setSubject('vet-user').setIssuedAt().setExpirationTime('1h').sign(new TextEncoder().encode('clinic-e2e-secret-at-least-32-bytes'));await context.addCookies([{name:'vethelp_clinic_session',value:token,url:baseURL,httpOnly:true,sameSite:'Lax'}]);}
const route=`/clinics/${clinic}/locations/${location}/vet/visits/${hold}`;
test('no grant preserves operational context and neutral section wording',async({page,context,baseURL})=>{await session(context,baseURL);await page.goto(route);await expect(page.getByRole('heading',{name:'Данные записи'})).toBeVisible();await expect(page.getByText('Владелец не предоставил медицинские данные для этой записи')).toBeVisible();await expect(page.getByText('У питомца нет медицинской истории')).toHaveCount(0);});
test('selected content, ordered explicit Amendments, document metadata and keyboard/axe',async({page,context,baseURL})=>{mode='shared';await session(context,baseURL);await page.goto(route);await expect(page.getByText('Selected original result')).toBeVisible();await expect(page.getByRole('heading',{name:'selected-history.pdf'})).toBeVisible();const items=page.locator('[aria-labelledby="shared-medical-title"] ol li');await expect(items).toHaveCount(2);await expect(items.nth(0)).toContainText('First selected amendment');await expect(items.nth(1)).toContainText('Second selected amendment');await expect(page.getByText('Unselected result')).toHaveCount(0);const refresh=page.getByRole('button',{name:'Обновить предоставленные данные'});await refresh.focus();await page.keyboard.press('Enter');await expect(page.getByText('Selected original result')).toBeVisible();expect((await new AxeBuilder({page}).include('[aria-labelledby="vet-visit-detail-title"]').analyze()).violations).toEqual([]);});
test('revoked access clears content without breaking the operational page',async({page,context,baseURL})=>{mode='shared';await session(context,baseURL);await page.goto(route);await expect(page.getByText('Selected original result')).toBeVisible();mode='revoked';await page.getByRole('button',{name:'Обновить предоставленные данные'}).click();await expect(page.getByText('Медицинские данные для этой записи недоступны.')).toBeVisible();await expect(page.getByText('Selected original result')).toHaveCount(0);await expect(page.getByRole('heading',{name:'Milo'})).toBeVisible();});
for(const deniedRole of ['CLINIC_ADMIN','CLINIC_RECEPTIONIST'])test(`${deniedRole} BFF medical denial before upstream`,async({page,context,baseURL})=>{role=deniedRole;await session(context,baseURL);const response=await page.request.get(bff);expect(response.status()).toBe(404);expect(await response.json()).toEqual({code:'MEDICAL_SHARE_NOT_FOUND'});expect(reads).toBe(0);});
test('malformed payload and errors never display private content; retry is labeled',async({page,context,baseURL})=>{mode='malformed';await session(context,baseURL);await page.goto(route);await expect(page.getByText('Не удалось загрузить предоставленные данные.')).toBeVisible();await expect(page.getByText('Private malformed payload')).toHaveCount(0);mode='error';await page.getByRole('button',{name:'Обновить предоставленные данные'}).click();await expect(page.getByText('Не удалось загрузить предоставленные данные.')).toBeVisible();await expect(page.getByRole('heading',{name:'Milo'})).toBeVisible();});
