import { expect, test } from '@playwright/test';
import { AxeBuilder } from '@axe-core/playwright';
import { createServer, type Server } from 'node:http';
import { SignJWT } from 'jose';

const caseA = '44444444-4444-4444-8444-444444444444'; const caseB = '55555555-5555-4555-8555-555555555555'; const secret = 'clinic-e2e-secret-at-least-32-bytes';
type Mode = 'success' | 'empty' | 'malformed' | 'denied' | 'error'; let server: Server; let mode: Mode = 'success'; let auditReads = 0; let capabilities = ['telemed.vet.queue.read', 'telemed.vet.audit-trail.read'];
const item = (id: string, code: string, at: string) => ({ id, eventType: code, summaryCode: code, createdAt: at });
test.describe.configure({ mode: 'serial' });
test.beforeAll(async () => { server = createServer(handle); await new Promise<void>((resolve) => server.listen(3212, '127.0.0.1', resolve)); });
test.afterAll(async () => { await new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); });
test.beforeEach(() => { mode = 'success'; auditReads = 0; capabilities = ['telemed.vet.queue.read', 'telemed.vet.audit-trail.read']; });

test('renders newest-first safe audit timeline', async ({ page, context, baseURL }) => {
  await session(context, baseURL); await page.goto('/telemed/vet'); const section = page.getByRole('heading', { name: 'История консультации' }).locator('..');
  await expect(page.getByText('Врач подключился')).toBeVisible(); await expect(page.getByText('Консультация назначена врачу')).toBeVisible(); expect(auditReads).toBe(1);
  await expect(section.locator('ol')).toBeVisible(); await expect(section.locator('time')).toHaveCount(2); await expect(section.locator('time').first()).toHaveAttribute('datetime', '2026-07-12T11:00:00.000Z'); await expect(page.getByText(/payload|token|ownerPhone/i)).toHaveCount(0);
  expect((await new AxeBuilder({ page }).include('[aria-labelledby="telemed-audit-title"]').analyze()).violations).toEqual([]);
});

test('suppresses audit requests without audit capability', async ({ page, context, baseURL }) => { capabilities = ['telemed.vet.queue.read']; await session(context, baseURL); await page.goto('/telemed/vet'); await expect(page.getByRole('heading', { name: 'История консультации' })).toHaveCount(0); expect(auditReads).toBe(0); });
test('shows an empty audit history', async ({ page, context, baseURL }) => { mode = 'empty'; await session(context, baseURL); await page.goto('/telemed/vet'); await expect(page.getByText('История событий пока пуста')).toBeVisible(); expect(auditReads).toBe(1); });
test('fails closed for malformed successful audit responses', async ({ page, context, baseURL }) => { mode = 'malformed'; await session(context, baseURL); await page.goto('/telemed/vet'); await expect(page.getByText('История консультации сейчас недоступна')).toBeVisible(); await expect(page.getByText('UNKNOWN_EVENT')).toHaveCount(0); expect(auditReads).toBe(1); });
test('normalizes backend denials', async ({ page, context, baseURL }) => { mode = 'denied'; await session(context, baseURL); await page.goto('/telemed/vet'); await expect(page.getByText('История консультации сейчас недоступна')).toBeVisible(); await expect(page.getByText(/INTERNAL_REASON/)).toHaveCount(0); expect(auditReads).toBe(1); });
test('retries recoverable audit errors once', async ({ page, context, baseURL }) => { mode = 'error'; await session(context, baseURL); await page.goto('/telemed/vet'); const retry = page.getByRole('button', { name: 'Повторить' }).last(); await expect(retry).toBeVisible(); expect(auditReads).toBe(1); mode = 'success'; await retry.click(); await expect(page.getByText('Врач подключился')).toBeVisible(); expect(auditReads).toBe(2); });

async function session(context: import('@playwright/test').BrowserContext, baseURL: string | undefined) { if (!baseURL) throw new Error('baseURL required'); const token = await new SignJWT({ roles: ['TELEMED_VETERINARIAN'] }).setProtectedHeader({ alg: 'HS256' }).setSubject('vet').setIssuedAt().setExpirationTime('1h').sign(new TextEncoder().encode(secret)); await context.addCookies([{ name: 'vethelp_clinic_session', value: token, url: baseURL, httpOnly: true, sameSite: 'Lax' }]); }
function queueCase(id: string, name: string) { return { caseId: id, state: 'ASSIGNED', queuePriority: 1, urgencyBand: 'LOW', serviceLevel: 'STANDARD', safetyEscalation: false, recommendationText: null, followUpNotes: null, assignedEmployeeId: 'vet', assignedAt: '2026-07-12T09:00:00.000Z', createdAt: '2026-07-12T09:00:00.000Z', updatedAt: '2026-07-12T09:00:00.000Z', intake: { id: '11111111-1111-4111-8111-111111111111', category: 'GENERAL_QUESTION', symptomDuration: 'NO_SYMPTOMS', priorClinicVisit: false, emergencyRedFlags: [] }, pet: { id: '22222222-2222-4222-8222-222222222222', name, species: 'CAT', breed: null, birthDate: null, weightKg: null, allergies: [], chronicConditions: [] }, latestEvent: null, session: null }; }
function json(response: import('node:http').ServerResponse, status: number, body: unknown) { response.writeHead(status, { 'Content-Type': 'application/json' }); response.end(JSON.stringify(body)); }
function handle(request: import('node:http').IncomingMessage, response: import('node:http').ServerResponse) { const path = new URL(request.url ?? '/', `http://${request.headers.host}`).pathname; if (path === '/v1/auth/session') return json(response, 200, { subjectId: 'vet', roles: ['TELEMED_VETERINARIAN'], effectiveCapabilities: capabilities, clinicScopes: [] }); if (path === '/v1/telemed/vet/queue') return json(response, 200, { serverNow: '2026-07-12T10:00:00.000Z', availableCases: [], assignedCases: [queueCase(caseA, 'Мила'), queueCase(caseB, 'Боня')], restrictedOutputPolicy: { allowed: [], forbidden: [] } }); if (path === `/v1/telemed/vet/cases/${caseA}/audit-trail` || path === `/v1/telemed/vet/cases/${caseB}/audit-trail`) { auditReads += 1; if (mode === 'denied') return json(response, 403, { code: 'INTERNAL_REASON' }); if (mode === 'error') return json(response, 503, { code: 'INTERNAL_REASON' }); if (mode === 'malformed') return json(response, 200, { caseId: caseA, serverNow: '2026-07-12T10:00:00.000Z', items: [item('x', 'UNKNOWN_EVENT', 'bad')] }); return json(response, 200, { caseId: path.includes(caseB) ? caseB : caseA, serverNow: '2026-07-12T10:00:00.000Z', items: mode === 'empty' ? [] : [item('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb', 'DOCTOR_CONNECTED', '2026-07-12T11:00:00.000Z'), item('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa', 'ASSIGNED', '2026-07-12T10:00:00.000Z')] }); } return json(response, 404, {}); }
