apiVersion: v1
kind: Service
metadata:
  name: vethelp-backend-service
  namespace: internal
  labels:
    app.kubernetes.io/name: vethelp-backend
    app.kubernetes.io/part-of: vethelp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vethelp-backend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
