import {fireEvent,render,waitFor} from '@testing-library/react-native';
const mockC='11111111-1111-4111-8111-111111111111',mockL='22222222-2222-4222-8222-222222222222',mockS='33333333-3333-4333-8333-333333333333',mockD='44444444-4444-4444-8444-444444444444',mockT='55555555-5555-4555-8555-555555555555';
process.env.EXPO_PUBLIC_OWNER_R2F_SPECIALIST_SELECTION='true';
jest.mock('@/session/SessionProvider',()=>({useSession:()=>({session:{cacheScope:'owner-a',opaqueCredential:'token-a'},error:null,logout:jest.fn()})}));
jest.mock('@/auth/AuthJourneyProvider',()=>({useAuthJourney:()=>({resumedIntent:null,consumeResumedIntent:jest.fn()})}));
jest.mock('@/pets/PetJourneyProvider',()=>({usePetJourney:()=>({active:false,continuedPetId:'66666666-6666-4666-8666-666666666666',pets:[{petId:'66666666-6666-4666-8666-666666666666',name:'Рекс',species:'DOG'}],loading:false,error:false,retry:jest.fn(),start:jest.fn(),cancel:jest.fn()})}));
jest.mock('@/booking/active-booking-store',()=>({activeBookingStore:{read:jest.fn().mockResolvedValue(null)}}));
jest.mock('@/booking/BookingStatusScreen',()=>({BookingStatusScreen:()=>null}));jest.mock('@/booking/BookingReviewScreen',()=>({BookingReviewScreen:()=>null}));jest.mock('@/pets/PetJourneyScreen',()=>({PetJourneyScreen:()=>null}));jest.mock('@/pets/PetDiaryScreen',()=>({PetDiaryScreen:()=>null}));
jest.mock('@/clinics/ClinicCatalogScreen',()=>{const React=jest.requireActual('react'),{Pressable,Text}=jest.requireActual('react-native');return{ClinicCatalogScreen:({onOpenClinic}:{onOpenClinic(value:unknown):void})=>React.createElement(Pressable,{accessibilityRole:'button',onPress:()=>onOpenClinic({clinicId:mockC,locationId:mockL})},React.createElement(Text,null,'open-clinic'))};});
jest.mock('@/clinics/ClinicDetailScreen',()=>{const React=jest.requireActual('react'),{Pressable,Text}=jest.requireActual('react-native');return{ClinicDetailScreen:({onChooseService}:{onChooseService():void})=>React.createElement(Pressable,{accessibilityRole:'button',onPress:onChooseService},React.createElement(Text,null,'choose-service'))};});
jest.mock('@/clinics/ClinicServiceScreen',()=>{const React=jest.requireActual('react'),{Pressable,Text}=jest.requireActual('react-native');return{ClinicServiceScreen:({onContinue}:{onContinue(value:unknown):void})=>React.createElement(Pressable,{accessibilityRole:'button',onPress:()=>onContinue({clinicId:mockC,locationId:mockL,serviceId:mockS})},React.createElement(Text,null,'continue-service'))};});
jest.mock('@/discovery/SpecialistSelectionScreen',()=>{const React=jest.requireActual('react'),{Pressable,Text}=jest.requireActual('react-native');return{SpecialistSelectionScreen:({context,onContinue}:{context:{serviceId:string};onContinue(value:unknown):void})=>React.createElement(Pressable,{accessibilityRole:'button',onPress:()=>onContinue({specialtyId:mockC,specialtyName:'Терапевт',doctorId:mockD,doctorName:'Анна',serviceId:mockS,clinicId:mockC,locationId:mockL,slots:[{slotId:mockT,startsAt:'2026-09-10T08:00:00Z',endsAt:'2026-09-10T08:30:00Z',expectedVersion:2}]})},React.createElement(Text,null,`specialist:${context.serviceId}`))};});
jest.mock('@/clinics/AvailabilityScreen',()=>{const React=jest.requireActual('react'),{Pressable,Text}=jest.requireActual('react-native');return{AvailabilityScreen:({allowedSlots,onBack}:{allowedSlots:readonly {slotId:string}[];onBack():void})=>React.createElement(Pressable,{accessibilityRole:'button',onPress:onBack},React.createElement(Text,null,`availability:${allowedSlots[0].slotId}`))};});
// Runtime flag must be set before loading the route module in this rollback-path test.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const AuthenticatedHomeScreen=require('../app/(app)/index').default;
afterAll(()=>{delete process.env.EXPO_PUBLIC_OWNER_R2F_SPECIALIST_SELECTION;});
it('routes service → one specialist → specialist-bounded availability and back',async()=>{const screen=await render(<AuthenticatedHomeScreen/>);fireEvent.press(screen.getByText('Начать запись'));fireEvent.press(await screen.findByText('open-clinic'));fireEvent.press(await screen.findByText('choose-service'));fireEvent.press(await screen.findByText('continue-service'));expect(await screen.findByText(`specialist:${mockS}`)).toBeTruthy();fireEvent.press(screen.getByText(`specialist:${mockS}`));expect(await screen.findByText(`availability:${mockT}`)).toBeTruthy();fireEvent.press(screen.getByText(`availability:${mockT}`));await waitFor(()=>expect(screen.getByText(`specialist:${mockS}`)).toBeTruthy());});
