const STATES = [
  'reception-ready','admin-ready','veterinarian-limited','multi-role-ready','pending-request',
  'request-due-soon','request-overdue','confirmed-appointment','alternative-selection',
  'owner-decision-pending','reject-confirmation','manual-booking','client-lookup','quick-client-create',
  'operational-empty','no-staff','technical-error','stale-retained','forbidden','slot-conflict',
  'search-results','search-empty','filters-active','week-view','mobile-agenda'
];
const ROLES = ['reception','admin','veterinarian','multi-role'];
const staff = [
  {id:'anna',name:'Анна Иванова',initials:'АИ',specialty:'Терапевт'},
  {id:'ilya',name:'Илья Петров',initials:'ИП',specialty:'Хирург'},
  {id:'maria',name:'Мария Смирнова',initials:'МС',specialty:'Терапевт'}
];
const baseEntries = [
  {id:'demo-request-barsik',col:0,start:5,duration:1,kind:'overdue',time:'10:30',end:'11:00',pet:'Барсик',owner:'Анна Ковалева',service:'Первичный приём терапевта',staff:'Анна Иванова',price:'2 500 ₽',status:'Требует ответа',sla:'Просрочено на 02:14',source:'Заявка с сайта'},
  {id:'demo-confirmed-luna',col:1,start:2,duration:2,kind:'confirmed',time:'09:00',end:'10:00',pet:'Луна',owner:'Олег Миронов',service:'Диагностика',staff:'Илья Петров',price:'3 800 ₽',status:'Подтверждена',source:'Онлайн-запись'},
  {id:'demo-confirmed-rex',col:2,start:3,duration:1.5,kind:'confirmed',time:'09:30',end:'10:15',pet:'Рекс',owner:'Марина Орлова',service:'Вакцинация',staff:'Мария Смирнова',price:'1 900 ₽',status:'Подтверждена',source:'Запись клиники'},
  {id:'demo-request-bonya',col:2,start:6,duration:1,kind:'pending',time:'11:00',end:'11:30',pet:'Боня',owner:'Ирина Соколова',service:'Повторный приём',staff:'Мария Смирнова',price:'1 700 ₽',status:'Требует ответа',sla:'Осталось 00:38',source:'Мобильное приложение'},
  {id:'demo-alternative-tosha',col:1,start:8,duration:1,kind:'alternative',time:'12:00',end:'12:30',pet:'Тоша',owner:'Дмитрий Волков',service:'Первичный приём терапевта',staff:'Илья Петров',price:'2 500 ₽',status:'Ожидает решения владельца',source:'Заявка с сайта'},
  {id:'demo-break-anna',col:0,start:9,duration:1,kind:'break',time:'12:30',end:'13:00',pet:'Перерыв',owner:'',service:'Перерыв сотрудника',staff:'Анна Иванова',price:'',status:'Недоступно',source:'Расписание'},
  {id:'demo-long-procedure',col:1,start:11,duration:3,kind:'confirmed',time:'13:30',end:'15:00',pet:'Марс',owner:'Анна Ковалева',service:'Процедура, 90 минут',staff:'Илья Петров',price:'5 200 ₽',status:'Подтверждена',source:'Запись клиники'},
  {id:'demo-confirmed-sima',col:0,start:12,duration:1,kind:'confirmed',time:'14:00',end:'14:30',pet:'Сима',owner:'Елена Белова',service:'Вакцинация',staff:'Анна Иванова',price:'1 900 ₽',status:'Подтверждена',source:'Онлайн-запись'},
  {id:'demo-request-mars',col:2,start:14,duration:2,kind:'pending',time:'15:00',end:'16:00',pet:'Марс',owner:'Анна Ковалева',service:'Диагностика',staff:'Мария Смирнова',price:'3 800 ₽',status:'Требует ответа',sla:'Осталось 08:12',source:'Мобильное приложение'},
  {id:'demo-unavailable-maria',col:2,start:17,duration:2,kind:'unavailable',time:'16:30',end:'17:30',pet:'Недоступно',owner:'',service:'Нет приёма',staff:'Мария Смирнова',price:'',status:'Недоступно',source:'Расписание'},
  {id:'demo-confirmed-bonya',col:0,start:18,duration:1,kind:'confirmed',time:'17:00',end:'17:30',pet:'Боня',owner:'Ирина Соколова',service:'Повторный приём',staff:'Анна Иванова',price:'1 700 ₽',status:'Подтверждена',source:'Запись клиники'},
  {id:'demo-confirmed-tosha',col:1,start:20,duration:2,kind:'confirmed',time:'18:00',end:'19:00',pet:'Тоша',owner:'Дмитрий Волков',service:'Диагностика',staff:'Илья Петров',price:'3 800 ₽',status:'Подтверждена',source:'Онлайн-запись'}
];
const stateDefaults = {
  'admin-ready':{role:'admin'},'veterinarian-limited':{role:'veterinarian'},'multi-role-ready':{role:'multi-role'},
  'pending-request':{selected:'demo-request-barsik'},'request-due-soon':{selected:'demo-request-bonya'},
  'request-overdue':{selected:'demo-request-barsik'},'confirmed-appointment':{selected:'demo-confirmed-luna'},
  'alternative-selection':{selected:'demo-request-barsik',modal:'alternative'},'owner-decision-pending':{selected:'demo-alternative-tosha'},
  'reject-confirmation':{selected:'demo-request-barsik',modal:'reject'},'manual-booking':{modal:'manual'},
  'client-lookup':{modal:'manual',clientLookup:true},'quick-client-create':{modal:'quick-client'},
  'operational-empty':{empty:true},'no-staff':{noStaff:true},'technical-error':{banner:'error'},
  'stale-retained':{banner:'stale'},'forbidden':{forbidden:true},'slot-conflict':{selected:'demo-request-barsik',conflict:true},
  'search-results':{search:'Барсик'},'search-empty':{search:'Черепаха'},'filters-active':{filters:true},
  'week-view':{week:true},'mobile-agenda':{}
};

const params = new URLSearchParams(location.search);
const requestedState = params.get('state') || 'reception-ready';
const requestedRole = params.get('role') || stateDefaults[requestedState]?.role || 'reception';
const requestedDate = params.get('date') || '2026-08-01';
const dateParts = /^(\d{4})-(\d{2})-(\d{2})$/.exec(requestedDate);
const parsedDate = dateParts ? new Date(Date.UTC(Number(dateParts[1]), Number(dateParts[2]) - 1, Number(dateParts[3]))) : null;
const validDate = Boolean(parsedDate && parsedDate.getUTCFullYear() === Number(dateParts[1]) && parsedDate.getUTCMonth() === Number(dateParts[2]) - 1 && parsedDate.getUTCDate() === Number(dateParts[3]));
const appState = {state:requestedState,role:requestedRole,date:validDate?requestedDate:'2026-08-01',entries:baseEntries.map(entry=>({...entry})),selected:null,lastFocus:null,filterActive:false};
const app = document.getElementById('app');
const drawer = document.getElementById('drawer');
const modal = document.getElementById('modal');
const backdrop = document.getElementById('modal-backdrop');
const liveRegion = document.getElementById('live-region');

function setUrl(state, extra={}){
  appState.state=state;
  const next=new URLSearchParams({state,role:appState.role,date:appState.date,...extra});
  history.pushState(null,'',`?${next}`);
}
function announce(message){liveRegion.textContent='';requestAnimationFrame(()=>{liveRegion.textContent=message;});}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function timeLabel(index){const minutes=8*60+index*30;return `${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`;}
function controlledError(message){app.innerHTML=`<main id="journal-main" class="controlled-error"><h1>Прототип не может открыть это состояние</h1><p role="alert">${escapeHtml(message)}</p><a class="primary-button" href="?state=reception-ready&role=reception&date=2026-08-01">Открыть журнал</a></main>`;}

function renderGrid(entries){
  const grid=document.getElementById('day-grid');
  const heads=['<div class="grid-corner" aria-hidden="true"></div>',...staff.map(person=>`<div class="staff-head"><span class="avatar">${person.initials}</span><span><strong>${person.name}</strong><small>${person.specialty} · принимает</small></span></div>`)].join('');
  let cells='';
  for(let row=0;row<24;row++){cells+=`<div class="time-cell">${timeLabel(row)}</div>`;for(let col=0;col<3;col++)cells+=`<div class="slot-cell"><button class="free-slot" data-action="free-slot" data-time="${timeLabel(row)}" data-staff="${staff[col].id}" aria-label="Свободно: ${timeLabel(row)}, ${staff[col].name}">+ Записать</button></div>`;}
  const cards=entries.map(entry=>{const actionable=['pending','overdue','alternative','confirmed','rejected'].includes(entry.kind);const content=`<strong>${entry.time} · ${entry.pet}</strong><small>${entry.service}</small><small class="status-line">${entry.status}${entry.sla?` · ${entry.sla}`:''}</small>`;const attrs=`class="entry" style="--col:${entry.col};--start:${entry.start};--duration:${entry.duration}" data-kind="${entry.kind}" aria-label="${entry.time}–${entry.end}, ${entry.pet}, ${entry.service}, ${entry.staff}, ${entry.status}${entry.sla?`, ${entry.sla}`:''}"`;return actionable?`<button ${attrs} data-entry-id="${entry.id}" aria-pressed="${appState.selected===entry.id}">${content}</button>`:`<div ${attrs} role="img">${content}</div>`;}).join('');
  grid.innerHTML=heads+cells+cards;
}
function renderAgenda(entries){
  const list=document.getElementById('agenda-list');
  const groups=new Map();entries.filter(e=>!['break','unavailable'].includes(e.kind)).forEach(e=>{const hour=e.time.slice(0,2)+':00';if(!groups.has(hour))groups.set(hour,[]);groups.get(hour).push(e);});
  list.innerHTML=[...groups].map(([hour,items])=>`<section class="agenda-group"><h3>${hour}</h3>${items.map(entry=>`<button class="agenda-card" data-entry-id="${entry.id}" data-kind="${entry.kind}" aria-label="${entry.time}–${entry.end}, ${entry.pet}, ${entry.service}, ${entry.staff}, ${entry.status}"><span class="agenda-time">${entry.time}</span><span class="agenda-content"><strong>${entry.pet}</strong><span>${entry.service}</span><small>${entry.staff} · ${entry.status}${entry.sla?` · ${entry.sla}`:''}</small></span><span class="agenda-price">${entry.price}</span></button>`).join('')}</section>`).join('');
}
function renderWeek(){
  document.getElementById('week-grid').innerHTML=`<div class="week-heading"><span class="avatar">АИ</span><div><h2>Неделя Анны Ивановой</h2><p>Ограниченный вид для выбора доступного времени</p></div></div><div class="week-days"><strong>Время</strong>${['Пн 28','Вт 29','Ср 30','Чт 31','Пт 1'].map(d=>`<strong>${d}</strong>`).join('')}${['09:00','10:00','11:00','12:00','13:00'].map((time,row)=>`<span>${time}</span>${[0,1,2,3,4].map(day=>`<button class="${(row+day)%3===0?'week-event':'week-free'}" data-action="week-slot" data-time="${time}" aria-label="${time}, ${day+28} июля, ${(row+day)%3===0?'занято':'свободно'}">${(row+day)%3===0?'Запись':'Свободно'}</button>`).join('')}`).join('')}</div>`;
}
function drawerMarkup(entry){
  const pending=['pending','overdue'].includes(entry.kind), alternative=entry.kind==='alternative';
  const actions=pending?`<button class="primary-button" data-action="confirm">Подтвердить запись</button><button class="secondary-button" data-action="alternative">Предложить другое время</button><button class="secondary-button danger" data-action="reject">Отклонить</button>`:alternative?`<button class="secondary-button" data-action="view-alternative">Просмотреть предложение</button>`:entry.kind==='confirmed'?`<button class="secondary-button" data-action="open-client">Открыть клиента</button><p class="muted">Перенос и отмена появятся после отдельного runtime-контракта.</p>`:`<p class="muted">Состояние доступно только для просмотра. Действия недоступны.</p>`;
  return `<section class="detail-block"><h3>Клиент и питомец</h3><div class="entity"><span class="avatar">${entry.owner?entry.owner.split(' ').map(x=>x[0]).join('').slice(0,2):'VH'}</span><span><strong>${entry.owner||'Системный интервал'}</strong><small>${entry.owner?'+7 *** ***-12-34':''}</small></span></div>${entry.owner?`<div class="entity"><span class="avatar">🐾</span><span><strong>${entry.pet}</strong><small>Кошка · 4 года</small></span></div>`:''}</section><section class="detail-block"><h3>Запись</h3><div class="detail-line"><span>Услуга</span><strong>${entry.service}</strong></div><div class="detail-line"><span>Время</span><strong>${entry.time}–${entry.end}</strong></div><div class="detail-line"><span>Врач</span><strong>${entry.staff}</strong></div><div class="detail-line"><span>Локация</span><strong>Садовая, 18</strong></div><div class="detail-line"><span>Цена</span><strong>${entry.price||'—'}</strong></div>${entry.sla?`<div class="detail-line"><span>SLA</span><strong>${entry.sla}</strong></div>`:''}</section><section class="detail-block"><h3>История</h3><ol class="timeline"><li>Заявка создана <small>10:12</small></li><li>Слот удержан <small>10:12</small></li><li>Клиника открыла заявку <small>10:14</small></li>${entry.kind==='confirmed'?'<li>Запись подтверждена <small>10:15</small></li>':''}${alternative?'<li>Предложено другое время <small>10:18</small></li><li>Ожидается решение владельца</li>':''}</ol></section><div class="drawer-actions">${actions}</div>`;
}
function openDrawer(id,focus=true){
  const entry=appState.entries.find(e=>e.id===id);if(!entry)return;
  if(!['pending','overdue','alternative','confirmed','rejected'].includes(entry.kind))return;
  appState.lastFocus=focus?document.activeElement:appState.lastFocus;appState.selected=id;
  document.querySelector('.workspace').classList.add('drawer-open');drawer.hidden=false;
  document.getElementById('drawer-status').textContent=`● ${entry.status}`;document.getElementById('drawer-title').textContent=`${entry.time} · ${entry.pet}`;document.getElementById('drawer-source').textContent=`${entry.source} · создана в 10:12`;document.getElementById('drawer-content').innerHTML=drawerMarkup(entry);
  document.querySelectorAll('[data-entry-id]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.entryId===id)));
  if(focus)drawer.querySelector('[data-action=close-drawer]').focus();
}
function closeDrawer(){drawer.hidden=true;document.querySelector('.workspace').classList.remove('drawer-open');appState.selected=null;if(appState.lastFocus?.isConnected)appState.lastFocus.focus();}
function showModal(title,content){appState.lastFocus=document.activeElement;document.getElementById('modal-title').textContent=title;document.getElementById('modal-content').innerHTML=content;backdrop.hidden=false;modal.hidden=false;modal.querySelector('button,[href],input,select,textarea')?.focus();}
function closeModal(){modal.hidden=true;backdrop.hidden=true;if(appState.lastFocus?.isConnected)appState.lastFocus.focus();}
function alternativeModal(){showModal('Предложить другое время',`<p>Исходное время <strong>1 августа, 10:30 · Анна Иванова</strong> остаётся видимым.</p><div class="choice-list" aria-label="Доступные интервалы"><button data-action="select-alternative" data-slot="14:30" aria-pressed="false"><strong>14:30–15:00 · Мария Смирнова</strong><br><small>Первичный приём · 2 500 ₽</small></button><button data-action="select-alternative" data-slot="16:00" aria-pressed="false"><strong>16:00–16:30 · Анна Иванова</strong><br><small>Первичный приём · 2 500 ₽</small></button></div><label class="field"><span>Причина</span><select id="alternative-reason"><option>Специалист недоступен</option><option>Время уже занято</option><option>Изменилось расписание</option><option>По согласованию с владельцем</option><option>Другое</option></select></label><div id="alternative-review" class="detail-block" hidden></div><div class="modal-actions"><button class="secondary-button" data-action="close-modal">Назад</button><button class="primary-button" data-action="send-alternative" disabled>Отправить предложение</button></div>`);}
function rejectModal(){showModal('Отклонить заявку',`<p>Заявка останется в истории. Это демонстрационное действие прототипа.</p><label class="field"><span>Причина</span><select id="reject-reason"><option>Нет подходящего специалиста</option><option>Нет доступного времени</option><option>Услуга временно недоступна</option><option>Другое</option></select></label><label class="field"><span>Комментарий, необязательно</span><textarea rows="3" maxlength="180"></textarea></label><div class="modal-actions"><button class="secondary-button" data-action="close-modal">Отмена</button><button class="primary-button" data-action="complete-reject">Отклонить заявку</button></div>`);}
function manualModal(quick=false){
  if(quick){showModal('Новый клиент',`<p>Только демонстрационные данные, без медицинской информации.</p><form id="quick-client-form" class="form-grid"><label class="field"><span>Имя владельца</span><input name="owner" required value="Ольга Демина"></label><label class="field"><span>Телефон</span><input name="phone" required value="+7 900 000-00-00" pattern="[+0-9 ()-]{10,}"></label><label class="field"><span>Имя питомца</span><input name="pet" required value="Кекс"></label><label class="field"><span>Вид питомца</span><select name="species"><option>Кошка</option><option>Собака</option></select></label><div class="modal-actions wide"><button type="button" class="secondary-button" data-action="manual-booking">Назад</button><button class="primary-button" type="submit">Добавить клиента</button></div></form>`);return;}
  showModal('Новая запись',`<p class="prototype-disclaimer">Демонстрационная форма: отправка не вызывает backend-команду.</p><form id="manual-form" class="form-grid"><label class="field wide"><span>Клиент</span><input id="client-field" name="client" required placeholder="Начните вводить имя" value="Анна Ковалева"><small><button type="button" class="text-button" data-action="quick-client">+ Быстро добавить клиента</button></small></label><label class="field"><span>Питомец</span><select name="pet" required><option>Барсик</option><option>Марс</option></select></label><label class="field"><span>Услуга</span><select name="service" required><option>Первичный приём терапевта</option><option>Вакцинация</option></select></label><label class="field"><span>Врач</span><select name="staff" required><option>Анна Иванова</option><option>Мария Смирнова</option></select></label><label class="field"><span>Дата</span><input name="date" type="date" value="2026-08-01" required></label><label class="field"><span>Время</span><select name="time" required><option value="">Выберите время</option><option>14:30</option><option>16:00</option></select><small class="field-error" hidden>Выберите доступное время</small></label><label class="field"><span>Цена</span><input name="price" value="2 500 ₽" readonly></label><label class="field wide"><span>Комментарий</span><textarea name="comment" rows="2" maxlength="180" placeholder="Необязательно"></textarea></label><div class="modal-actions wide"><button type="button" class="secondary-button" data-action="close-modal">Отмена</button><button class="primary-button" type="submit">Создать запись</button></div></form>`);
}
function openSearch(query=''){
  appState.lastFocus=document.activeElement;backdrop.hidden=false;const panel=document.getElementById('search-panel');panel.hidden=false;const input=document.getElementById('search-input');input.value=query;renderSearch(query);input.focus();
}
function renderSearch(query){const results=document.getElementById('search-results');const values=[...appState.entries.filter(e=>e.owner).map(e=>({title:`${e.pet} · ${e.owner}`,meta:`${e.time} · ${e.service}`,id:e.id})),...staff.map(s=>({title:s.name,meta:s.specialty,id:'demo-confirmed-luna'}))];const matches=query.trim()?values.filter(v=>`${v.title} ${v.meta}`.toLowerCase().includes(query.toLowerCase())):[];results.innerHTML=!query.trim()?'<p>Введите имя клиента, питомца, сотрудника или название услуги.</p>':matches.length?matches.slice(0,6).map(v=>`<button class="search-result" data-search-entry="${v.id}"><span><strong>${v.title}</strong><small>${v.meta}</small></span><span>Открыть →</span></button>`).join(''):'<div class="empty-state"><h2>Ничего не найдено</h2><p>Проверьте запрос или откройте список клиентов.</p></div>';}
function closeSearch(){const panel=document.getElementById('search-panel');panel.hidden=true;backdrop.hidden=true;if(appState.lastFocus?.isConnected)appState.lastFocus.focus();}
function renderState(){
  if(!STATES.includes(appState.state)){controlledError(`Неизвестное состояние: ${appState.state}`);return false}if(!ROLES.includes(appState.role)){controlledError(`Неизвестная роль: ${appState.role}`);return false}if(!validDate){controlledError('Дата должна существовать и иметь формат YYYY-MM-DD');return false}
  const config=stateDefaults[appState.state]||{};if(config.role)appState.role=config.role;
  app.dataset.state=appState.state;app.dataset.role=appState.role;document.getElementById('role-label').textContent={reception:'Администратор записи',admin:'Администратор клиники',veterinarian:'Врач · целевой режим','multi-role':'Администратор и врач'}[appState.role];document.querySelectorAll('[data-admin-only]').forEach(el=>el.hidden=!['admin','multi-role'].includes(appState.role));
  if(appState.role==='veterinarian'){appState.entries=baseEntries.filter(e=>e.col===0&&!['pending','overdue'].includes(e.kind)).map(e=>({...e}));showBanner('Целевой ограниченный режим врача. Runtime authority будет определена отдельным контрактом.','info');document.querySelector('.sla-bar').hidden=true;document.querySelector('.mobile-urgent').hidden=true}else appState.entries=baseEntries.map(e=>({...e}));
  renderGrid(config.empty||config.noStaff?[]:appState.entries);renderAgenda(config.empty||config.noStaff?[]:appState.entries);renderWeek();
  document.getElementById('empty-state').hidden=!(config.empty||config.noStaff);if(config.empty||config.noStaff){document.querySelector('.sla-bar').hidden=true;document.querySelector('.mobile-urgent').hidden=true}if(config.noStaff){document.querySelector('#empty-state h2').textContent='Для этой даты не настроено расписание сотрудников';document.querySelector('#empty-state p').textContent='Проверьте рабочие часы или выберите другую дату.'}
  if(config.banner==='error')showBanner('Не удалось загрузить журнал. Повторите попытку. Ошибка не означает, что записей нет.','error');if(config.banner==='stale')showBanner('Не удалось обновить данные. Показана последняя доступная версия от 14:32. Перед изменением записи повторите обновление.','warning');if(config.forbidden){showBanner('У вас нет доступа к этой локации.','error');document.querySelectorAll('.workspace,.sla-bar,.mobile-urgent,.toolbar,.mobile-date,.bottom-nav,.sidebar nav,.clinic-switcher,.user-card,.prototype-note,.mobile-header button').forEach(element=>{element.hidden=true});document.querySelectorAll('[data-action="manual-booking"],[data-action="open-first"],[data-action="show-requests"],[data-action="open-search"],[data-action="open-filters"],[data-action="refresh"]').forEach(element=>element.remove());document.getElementById('day-grid').replaceChildren();document.getElementById('agenda-list').replaceChildren();document.getElementById('drawer-content').replaceChildren();drawer.hidden=true}if(config.conflict){showBanner('Это время уже занято. Обновите журнал или предложите другое время.','error');const e=appState.entries.find(x=>x.id==='demo-request-barsik');e.status='Требует другого времени'}
  if(config.week){toggleView('week')}if(config.filters){document.querySelector('[name=status][value=pending]').checked=true;appState.filterActive=true;document.getElementById('filter-count').textContent='1';}
  if(config.selected)openDrawer(config.selected,false);if(config.modal==='alternative')alternativeModal();if(config.modal==='reject')rejectModal();if(config.modal==='manual')manualModal();if(config.modal==='quick-client')manualModal(true);if(config.search!==undefined)openSearch(config.search);
  return true;
}
function showBanner(message,tone='warning'){const banner=document.getElementById('system-banner');banner.hidden=false;banner.dataset.tone=tone;banner.setAttribute('role',tone==='error'?'alert':'status');banner.textContent=message;}
function toggleView(view){const week=view==='week';document.getElementById('day-grid').hidden=week;document.getElementById('week-grid').hidden=!week;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));if(week)setUrl('week-view');}
function confirmEntry(button){button.disabled=true;button.textContent='Подтверждаем…';setTimeout(()=>{const entry=appState.entries.find(e=>e.id===appState.selected);if(!entry)return;entry.kind='confirmed';entry.status='Подтверждена';delete entry.sla;renderGrid(appState.entries);renderAgenda(appState.entries);openDrawer(entry.id,false);setUrl('confirmed-appointment');announce(`Запись ${entry.pet} на ${entry.time} подтверждена в демонстрационном прототипе.`);},350);}
function completeAlternative(){const selected=modal.querySelector('[data-action=select-alternative][aria-pressed=true]');if(!selected)return;const entry=appState.entries.find(e=>e.id===appState.selected);entry.kind='alternative';entry.status='Ожидает решения владельца';entry.time=selected.dataset.slot;entry.end=selected.dataset.slot==='14:30'?'15:00':'16:30';renderGrid(appState.entries);renderAgenda(appState.entries);closeModal();openDrawer(entry.id,false);setUrl('owner-decision-pending');announce('Предложение другого времени отправлено в демонстрационном прототипе. Ожидается решение владельца.');}
function applyFilters(){const active=[...document.querySelectorAll('.filters input:checked')].filter(i=>i.value!=='all');appState.filterActive=active.length>0;document.getElementById('filter-count').textContent=active.length?String(active.length):'';const actionOnly=document.querySelector('[name=action]').checked;const filtered=actionOnly?appState.entries.filter(e=>['pending','overdue'].includes(e.kind)):appState.entries;renderGrid(filtered);renderAgenda(filtered);document.getElementById('result-summary').textContent=`${filtered.length} событий · ${staff.length} сотрудника`;document.getElementById('filters').classList.remove('open');backdrop.hidden=true;setUrl('filters-active');announce(`Фильтры применены. Показано событий: ${filtered.length}.`);}

document.addEventListener('click',event=>{
  const entryButton=event.target.closest('[data-entry-id]');if(entryButton){openDrawer(entryButton.dataset.entryId);return}
  const searchEntry=event.target.closest('[data-search-entry]');if(searchEntry){closeSearch();openDrawer(searchEntry.dataset.searchEntry);return}
  const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;
  if(action==='close-drawer')closeDrawer();else if(action==='open-first'){openDrawer('demo-request-barsik');setUrl('pending-request')}else if(action==='confirm')confirmEntry(button);else if(action==='alternative')alternativeModal();else if(action==='reject')rejectModal();else if(action==='close-modal')closeModal();else if(action==='select-alternative'){modal.querySelectorAll('[data-action=select-alternative]').forEach(b=>b.setAttribute('aria-pressed','false'));button.setAttribute('aria-pressed','true');modal.querySelector('[data-action=send-alternative]').disabled=false;const review=document.getElementById('alternative-review');review.hidden=false;review.innerHTML=`<strong>Новое время: ${button.dataset.slot}</strong><br>Первичный приём · 2 500 ₽`;announce(`Выбрано время ${button.dataset.slot}`)}else if(action==='send-alternative')completeAlternative();else if(action==='complete-reject'){const entry=appState.entries.find(e=>e.id===appState.selected);entry.kind='rejected';entry.status='Отклонена';closeModal();renderGrid(appState.entries);renderAgenda(appState.entries);openDrawer(entry.id,false);announce('Заявка отклонена в демонстрационном прототипе.')}else if(action==='manual-booking'||action==='free-slot')manualModal();else if(action==='quick-client')manualModal(true);else if(action==='open-search')openSearch();else if(action==='close-search')closeSearch();else if(action==='open-filters'){appState.lastFocus=document.activeElement;document.getElementById('filters').classList.add('open');backdrop.hidden=false;document.querySelector('[data-action=close-filters]').focus()}else if(action==='close-filters'){document.getElementById('filters').classList.remove('open');backdrop.hidden=true;appState.lastFocus?.focus()}else if(action==='apply-filters')applyFilters();else if(action==='reset-filters'){document.querySelectorAll('.filters input').forEach(i=>i.checked=i.value==='all');appState.filterActive=false;renderGrid(appState.entries);renderAgenda(appState.entries);document.getElementById('filter-count').textContent='';announce('Фильтры сброшены')}else if(action==='refresh'){showBanner('Журнал обновлён в 14:34. Данные прототипа остаются синтетическими.','info');announce('Журнал обновлён')}else if(action==='show-requests')setUrl('pending-request');else if(action==='today'){appState.date='2026-08-01';setUrl(appState.state);announce('Открыт сегодняшний день')}else if(action==='week-slot'&&button.classList.contains('week-free')){announce(`Выбран свободный интервал ${button.dataset.time}`)}else if(action==='open-client')announce('Открытие клиента демонстрируется без перехода в runtime');
});
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>toggleView(button.dataset.view)));
document.getElementById('search-input').addEventListener('input',event=>renderSearch(event.target.value));
document.addEventListener('submit',event=>{event.preventDefault();if(event.target.id==='manual-form'){const data=new FormData(event.target);if(!data.get('time')){const error=event.target.querySelector('.field-error');error.hidden=false;event.target.elements.time.focus();announce('Выберите доступное время');return}const newEntry={id:'demo-manual-keks',col:0,start:13,duration:1,kind:'confirmed',time:data.get('time'),end:data.get('time')==='14:30'?'15:00':'16:30',pet:data.get('pet'),owner:data.get('client'),service:data.get('service'),staff:data.get('staff'),price:'2 500 ₽',status:'Подтверждена',source:'Ручная запись · прототип'};appState.entries.push(newEntry);closeModal();renderGrid(appState.entries);renderAgenda(appState.entries);openDrawer(newEntry.id,false);announce('Демонстрационная запись создана и показана в журнале.')}else if(event.target.id==='quick-client-form'){manualModal();const field=document.getElementById('client-field');if(field)field.value='Ольга Демина';announce('Демонстрационный клиент добавлен')}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(!modal.hidden)closeModal();else if(!document.getElementById('search-panel').hidden)closeSearch();else if(document.getElementById('filters').classList.contains('open')){document.getElementById('filters').classList.remove('open');backdrop.hidden=true;appState.lastFocus?.focus()}else if(!drawer.hidden)closeDrawer()}if(['ArrowRight','ArrowLeft','Home','End'].includes(event.key)&&event.target.matches('.entry,.agenda-card')){const entries=[...document.querySelectorAll(event.target.matches('.entry')?'.entry':'.agenda-card')];const index=entries.indexOf(event.target);let next=index+(event.key==='ArrowRight'?1:event.key==='ArrowLeft'?-1:0);if(event.key==='Home')next=0;if(event.key==='End')next=entries.length-1;entries[Math.max(0,Math.min(entries.length-1,next))]?.focus()}});
window.addEventListener('popstate',()=>location.reload());
renderState();
